
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    AbnormalCostType_NONE = 0;
    /**
     * 独立消耗
     */
    AbnormalCostType_Independence = 1;
    /**
     * 分摊消耗
     */
    AbnormalCostType_Allocation = 2;
)

