
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * actor重生模式
 */
const (
    /**
     * 默认模式（跟物件/怪物本身）
     */
    ActorResetMode_EResetOnDefault = 0;
    /**
     * 特定模式，会配模式id
     */
    ActorResetMode_EResetOnSpecial = 1;
)

