//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

const (
	/**
	 * 未定义
	 */
	ActorType_EActorType_None = 0
	/**
	 * 出生点
	 */
	ActorType_EActorType_SpawnPoint = 1
	/**
	 * 刷怪器
	 */
	ActorType_EActorType_MonsterSpawner = 2
	/**
	 * 攀爬点
	 */
	ActorType_EActorType_LaunchPad = 3
	/**
	 * 怪物
	 */
	ActorType_EActorType_Monster = 4
	/**
	 * 废弃类型，NPC统一类型为Monster
	 */
	ActorType_EActorType_NPC = 5
	/**
	 * 废弃类型，Animal统一类型为Monster
	 */
	ActorType_EActorType_Animal     = 6
	ActorType_EActorType_CheckPoint = 7
	/**
	 * 存档点
	 */
	ActorType_EActorType_RestPoint = 8
	/**
	 * 激活AI的Volume
	 */
	ActorType_EActorType_AIVolume = 9
	/**
	 * 小队管理器
	 */
	ActorType_EActorType_SquadManager = 10
	/**
	 * 接取任务用Volume
	 */
	ActorType_EActorType_QuestVolume = 11
	/**
	 * 对象生成器
	 */
	ActorType_EActorType_ObjectSpawner = 12
	/**
	 * 传送点
	 */
	ActorType_EActorType_Landmark = 13
	/**
	 * 单向门
	 */
	ActorType_EActorType_Door = 14
	/**
	 * 宝箱
	 */
	ActorType_EActorType_Chest = 15
	/**
	 * 破碎物
	 */
	ActorType_EActorType_Destruction = 16
	/**
	 * 玩家英雄
	 */
	ActorType_EActorType_Avatar = 17
	/**
	 * 区域
	 */
	ActorType_EActorType_Region = 18
	/**
	 * 物件
	 */
	ActorType_EActorType_Gadget = 19
	/**
	 * 观察点
	 */
	ActorType_EActorType_EYE_POINT = 20
	/**
	 * 队伍
	 */
	ActorType_EActorType_Team = 21
	/**
	 * 天气
	 */
	ActorType_EActorType_Weather = 22
	/**
	 * 关卡内临时对象
	 */
	ActorType_EActorType_Temp_Avatar = 23
	/**
	 * 拾取物
	 */
	ActorType_EActorType_Pickup = 24
	/**
	 * 激活关卡机关的Volume
	 */
	ActorType_EActorType_LevelDeviceVolume = 25
	/**
	 * 电梯
	 */
	ActorType_EActorType_Lift = 26
	/**
	 * 触发Buff的Volume
	 */
	ActorType_EActorType_BuffVolume = 27
	/**
	 * 通用开关
	 */
	ActorType_EActorType_CommonSwitch = 29
	/**
	 * 通用机关Spawner
	 */
	ActorType_EActorType_TrapSpawner = 30
	/**
	 * 宝箱破碎物
	 */
	ActorType_EActorType_ChestDestruction = 31
	/**
	 * 升降平台
	 */
	ActorType_EActorType_MovingPlatform = 32
	/**
	 * 梯子
	 */
	ActorType_EActorType_Ladder = 33
	/**
	 * 服务器用区域Volume
	 */
	ActorType_EActorType_ServerBoundsVolume = 34
	/**
	 * 通用信息板
	 */
	ActorType_EActorType_InformationBoard = 35
	/**
	 * 强制玩家死亡Volume
	 */
	ActorType_EActorType_KillZVolume = 36
	/**
	 * 空气墙
	 */
	ActorType_EActorType_InvisibleWall = 37
	/**
	 * 激活ObjectSpawner用的Volume
	 */
	ActorType_EActorType_ObjectVolume = 38
	/**
	 * 子弹
	 */
	ActorType_EActorType_Projectile = 39
	/**
	 * 海巡兽装置,比如炮台
	 */
	ActorType_EActorType_ShipMod = 40
	/**
	 * 任务/通用叙事物件
	 */
	ActorType_EActorType_Narrative = 41
	/**
	 * 收集物(掉落组ID直接读Item表)
	 */
	ActorType_EActorType_Collection = 42
	/**
	 * 凡器
	 */
	ActorType_EActorType_FanQi = 43
	/**
	 * 召唤物
	 */
	ActorType_EActorType_Summon = 44
	/**
	 * 攀爬区域
	 */
	ActorType_EActorType_Ledge = 45
	/**
	 * 传送器
	 */
	ActorType_EActorType_Teleporter = 46
	/**
	 * 基础交互物
	 */
	ActorType_EActorType_InteractiveActor = 47
	/**
	 * 怪物召唤装置
	 */
	ActorType_EActorType_SummonMachine = 48
	/**
	 * 场景传送门
	 */
	ActorType_EActorType_TeleporterScene = 49
	/**
	 * 随机岛礁
	 */
	ActorType_EActorType_RandomIsland = 50
	/**
	 * 美术舔图专用Volume，用于修改物件状态
	 */
	ActorType_EActorType_ArtVolume = 51
	/**
	 * 美术舔图专用物件，可被ArtVolume修改物件状态切换表现
	 */
	ActorType_EActorType_ArtMachine = 52
	/**
	 * 静海停靠点 码头
	 */
	ActorType_EActorType_Wharf = 53
	/**
	 * 可掉落的破坏物
	 */
	ActorType_EActorType_DropableDestruction = 54
	/**
	 * 召唤物生成器
	 */
	ActorType_EActorType_SummonSpawner = 55
	/**
	 * 打捞点
	 */
	ActorType_EActorType_SalvagePoint = 56
	/**
	 * 通用状态切换Actor
	 */
	ActorType_EActorType_Utility = 57
	/**
	 * GameFlwo Entity,可以直接放置的玩法单元
	 */
	ActorType_EActorType_GameFlow = 58
	/**
	 * 地图信息Actor（尺寸/迷雾信息等）
	 */
	ActorType_EActorType_MapInfo = 59
	/**
	 * 镶嵌机关
	 */
	ActorType_EActorType_InlayTrap = 60
)
