
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 随关卡加载生成
     */
    ActorSpawnMode_ESpawnOnBeginPlay = 0;
    /**
     * 触发事件生成
     */
    ActorSpawnMode_ESpawnOnTriggered = 1;
)

