
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景内Actor附带额外的默认TAG<br/>（一般系统玩法配合使用）
 */
const (
    /**
     * 无
     */
    ActorAdditionTag_NONE = 0;
    /**
     * tag1
     */
    ActorAdditionTag_TAG1 = 1;
    /**
     * tag2
     */
    ActorAdditionTag_TAG2 = 2;
    /**
     * tag3
     */
    ActorAdditionTag_TAG3 = 3;
    /**
     * tag4
     */
    ActorAdditionTag_TAG4 = 4;
    /**
     * tag5
     */
    ActorAdditionTag_TAG5 = 5;
    /**
     * tag6
     */
    ActorAdditionTag_TAG6 = 6;
    /**
     * tag7
     */
    ActorAdditionTag_TAG7 = 7;
    /**
     * tag8
     */
    ActorAdditionTag_TAG8 = 8;
    /**
     * tag9
     */
    ActorAdditionTag_TAG9 = 9;
    /**
     * tag10
     */
    ActorAdditionTag_TAG10 = 10;
    /**
     * tag11
     */
    ActorAdditionTag_TAG11 = 11;
    /**
     * tag12
     */
    ActorAdditionTag_TAG12 = 12;
)

