
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景内Actor掉落的类型
 */
const (
    /**
     * 掉落组ID
     */
    ActorDropType_DROPGROUP = 0;
    /**
     * Item表ID
     */
    ActorDropType_ITEM = 1;
)

