
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * Actor状态重置类型
 */
const (
    /**
     * 玩家上下线
     */
    ActorResetType_PlayerOffline = 0;
    /**
     * 同Scene内传送
     */
    ActorResetType_Teleport = 1;
    /**
     * 跨Scene传送
     */
    ActorResetType_Transmission = 2;
    /**
     *  听风（坐火）
     */
    ActorResetType_RestPoint = 3;
    /**
     * 玩家死亡重生
     */
    ActorResetType_TeamDeath = 4;
    /**
     * 坠落跳崖
     */
    ActorResetType_Falling = 5;
    /**
     * 回血
     */
    ActorResetType_Recover = 6;
)

