
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 在大地图的Actor可视类型
 */
const (
    /**
     * <br/>不显示
     */
    ActorVisualType_None = 0;
    /**
     * 默认显示基类的可视类型
     */
    ActorVisualType_Default = 1;
    /**
     * <br/>门
     */
    ActorVisualType_Door = 2;
    /**
     * 宝箱
     */
    ActorVisualType_Chest = 3;
    /**
     * 休息点
     */
    ActorVisualType_RestPoint = 4;
    /**
     * 电梯
     */
    ActorVisualType_Lift = 5;
    /**
     * 梯子
     */
    ActorVisualType_Ladder = 6;
    /**
     * 采集物
     */
    ActorVisualType_Pickup = 7;
    /**
     * 收集物
     */
    ActorVisualType_Collection = 8;
    /**
     * 叙事交互物
     */
    ActorVisualType_Narrative = 9;
    /**
     * 喷气开关
     */
    ActorVisualType_TrapSpawner = 10;
    /**
     * 升降平台
     */
    ActorVisualType_MovingPlatform = 11;
    /**
     * 净海传送点
     */
    ActorVisualType_JHTeleporter = 12;
    /**
     * 日常本基础
     */
    ActorVisualType_ResLevelBase = 13;
    /**
     * 日常本突破
     */
    ActorVisualType_ResLevelExceed = 14;
    /**
     * 日常本天赋
     */
    ActorVisualType_ResLevelTalent = 15;
    /**
     * 日常本装备
     */
    ActorVisualType_ResLevelEquipMark = 16;
    /**
     * 深渊入口
     */
    ActorVisualType_Maze = 17;
    /**
     * 随机陆礁
     */
    ActorVisualType_RandomIsland = 18;
    /**
     * 绝崖洞窟（藏宝洞）
     */
    ActorVisualType_TreasureCave = 19;
    /**
     * 主线入口
     */
    ActorVisualType_TeleporterSelect = 20;
    /**
     * 码头停靠
     */
    ActorVisualType_WharfBase = 21;
    /**
     * 净海固定宝箱
     */
    ActorVisualType_JHChest01 = 22;
    /**
     * 净海突现宝箱
     */
    ActorVisualType_JHCHest02 = 23;
    /**
     * 怪物生成器
     */
    ActorVisualType_MonsterSpawner = 24;
    /**
     * 净海地图信息
     */
    ActorVisualType_MapInfo = 25;
    /**
     * 与狭间
     */
    ActorVisualType_JHYXJ = 26;
    /**
     * 祈玉本-木灵
     */
    ActorVisualType_MarkMuSprite = 27;
    /**
     * 祈玉本-宝匣
     */
    ActorVisualType_MarkChest = 28;
    /**
     * 祈玉本-祈玉怪
     */
    ActorVisualType_MarkMonster = 29;
    /**
     * 祈玉本-深层门
     */
    ActorVisualType_MarkNext = 30;
    /**
     * 祈玉本入口
     */
    ActorVisualType_ResLevelMark = 31;
)

