
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 美术/战斗通用物件状态
 */
const (
    ArtMachineState_State0 = 0;
    ArtMachineState_State1 = 1;
    ArtMachineState_State2 = 2;
    ArtMachineState_State3 = 3;
    ArtMachineState_State4 = 4;
    ArtMachineState_State5 = 5;
    ArtMachineState_State6 = 6;
    ArtMachineState_State7 = 7;
    ArtMachineState_State8 = 8;
    ArtMachineState_State9 = 9;
)

