
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type AttackDataOpt struct {
    AttackDataIds []int32
    SkillProp int32
    Count int32
}

const TypeId_AttackDataOpt = -1911888095

func (*AttackDataOpt) GetTypeId() int32 {
    return -1911888095
}

func NewAttackDataOpt(_buf map[string]interface{}) (_v *AttackDataOpt, err error) {
    _v = &AttackDataOpt{}
    { var _ok_ bool; var __json_attackDataIds__ interface{}; if __json_attackDataIds__, _ok_ = _buf["attackDataIds"]; !_ok_ || __json_attackDataIds__ == nil { err = errors.New("attackDataIds error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_attackDataIds__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AttackDataIds = __x__ }}
    { var _ok_ bool; var __json_skillProp__ interface{}; if __json_skillProp__, _ok_ = _buf["skillProp"]; !_ok_ || __json_skillProp__ == nil { err = errors.New("skillProp error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_skillProp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SkillProp = __x__ }}
    { var _ok_ bool; var __json_count__ interface{}; if __json_count__, _ok_ = _buf["count"]; !_ok_ || __json_count__ == nil { err = errors.New("count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Count = __x__ }}
    return
}

