
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 无类型
     */
    AttackRangeType_ATTACK_NONE = 0;
    /**
     * 近距离
     */
    AttackRangeType_ATTACK_NEAR = 1;
    /**
     * 远距离
     */
    AttackRangeType_ATTACK_FAR = 2;
)

