
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 前方
     */
    AttackDirectionType_Front = 0;
    /**
     * 后方
     */
    AttackDirectionType_Back = 1;
    /**
     * 左侧
     */
    AttackDirectionType_Left = 2;
    /**
     * 右侧
     */
    AttackDirectionType_Right = 3;
)

