
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 中立，废弃阵营不要去用
     */
    CampType_CAMP_Neutral = 0;
    /**
     * 阵营_1，主角阵营
     */
    CampType_CAMP_1 = 1;
    /**
     * 阵营_2，圣宫阵营
     */
    CampType_CAMP_2 = 2;
    /**
     * 阵营_3，帝国阵营
     */
    CampType_CAMP_3 = 3;
    /**
     * 阵营_4，全友善阵营也不会被攻击
     */
    CampType_CAMP_4 = 4;
    /**
     * 阵营_5，仅玩家敌对
     */
    CampType_CAMP_5 = 5;
    /**
     * 阵营_6，仅对自己友好
     */
    CampType_CAMP_6 = 6;
    /**
     * 阵营_7，海乱
     */
    CampType_CAMP_7 = 7;
)

