
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type CampTbCampRelation struct {
    _dataMap map[int32]*CampCampRelationData
    _dataList []*CampCampRelationData
}

func NewCampTbCampRelation(_buf []map[string]interface{}) (*CampTbCampRelation, error) {
    _dataList := make([]*CampCampRelationData, 0, len(_buf))
    dataMap := make(map[int32]*CampCampRelationData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewCampCampRelationData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &CampTbCampRelation{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *CampTbCampRelation) GetDataMap() map[int32]*CampCampRelationData {
    return table._dataMap
}

func (table *CampTbCampRelation) GetDataList() []*CampCampRelationData {
    return table._dataList
}

func (table *CampTbCampRelation) Get(key int32) *CampCampRelationData {
    return table._dataMap[key]
}


