
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 宝箱破碎物状态
 */
const (
    /**
     * 完好
     */
    ChestDestructionState_intact = 0;
    /**
     * 已破坏
     */
    ChestDestructionState_Destroyed = 1;
)

