
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 宝箱状态
 */
const (
    /**
     * 关闭
     */
    ChestState_Closed = 0;
    /**
     * 已打开
     */
    ChestState_Opened = 1;
)

