
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    ClientInstructionType_NONE = 0;
    /**
     * 枚举使用战斗tag命名
     */
    ClientInstructionType_Event_Hero_Execution_Singleplayer_End = 1;
)

