
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 金币
     */
    CoinType_GOLD = 0;
    /**
     * 付费钻
     */
    CoinType_PAID_DIAMOND = 1;
    /**
     * 免费钻
     */
    CoinType_FREE_DIAMOND = 2;
)

