
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 等于
     */
    CompareVarType_EQUAL = 0;
    /**
     * 大于
     */
    CompareVarType_GREATER = 1;
    /**
     * 大于等于
     */
    CompareVarType_GREATER_EQUAL = 2;
    /**
     * 小于
     */
    CompareVarType_LESS = 3;
    /**
     * 小于等于
     */
    CompareVarType_LESS_EQUAL = 4;
)

