
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 传送器状态
 */
const (
    /**
     * 未激活
     */
    ConveyorState_NotActivated = 0;
    /**
     * 已激活
     */
    ConveyorState_Activated = 1;
    /**
     * 已交互
     */
    ConveyorState_Interacted = 2;
    /**
     * 禁用, 此时传送器无法进行交互, 可用于不同表现
     */
    ConveyorState_Disabled = 3;
)

