
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 冰
     */
    DamageType_Ice = 0;
    /**
     * 火
     */
    DamageType_Fire = 1;
    /**
     * 风
     */
    DamageType_Wind = 2;
    /**
     * 雷
     */
    DamageType_Thunder = 3;
    /**
     * 光/冲击
     */
    DamageType_Light = 4;
    /**
     * 暗/侵蚀
     */
    DamageType_Dark = 5;
    /**
     * 真实伤害（可带异常属性）
     */
    DamageType_Real = 6;
)

