
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 技能数据类型
 */
const (
    /**
     * 伤害
     */
    DataType_DAMAGE = 0;
    /**
     * 治疗
     */
    DataType_HEAL = 1;
    /**
     * 护盾
     */
    DataType_SHIELD = 2;
)

