
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 预埋点生效,
     */
    DeviceCollectorMod_Collector_LevelActor = 0;
    /**
     * 对主角生效
     */
    DeviceCollectorMod_Collector_Collector_MainHero = 1;
)

