
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 界面显示配置
 */
const (
    /**
     * 全部
     */
    DisplayType_All = 0;
    /**
     * 家园
     */
    DisplayType_Home = 1;
    /**
     * 家园和净海
     */
    DisplayType_HomeAndSandSea = 2;
    /**
     * 家园和战斗
     */
    DisplayType_HomeAndBattle = 3;
    /**
     * 净海
     */
    DisplayType_SandSea = 4;
    /**
     * 净海和战斗
     */
    DisplayType_SandSeaAndBattle = 5;
    /**
     * 战斗
     */
    DisplayType_Battle = 6;
)

