
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 门状态
 */
const (
    /**
     * 关门
     */
    DoorState_Closed = 0;
    /**
     * 开门
     */
    DoorState_Opened = 1;
)

