
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 操作类型
 */
const (
    EOptType_NONE = 0;
    /**
     * 加
     */
    EOptType_ADD = 1;
    /**
     * 乘
     */
    EOptType_MULTI = 2;
)

