
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 操作成功
     */
    ErrCodeEnum_SUCCESS = 0;
    ErrCodeEnum_UNKNOWN = 1;
    ErrCodeEnum_FAILED = 2;
    /**
     * 同一账号登录被踢
     */
    ErrCodeEnum_SAME_ACCOUNT_LOGIN_KICK_OUT = 3;
    /**
     * 玩家 token 不合法
     */
    ErrCodeEnum_INVALID_LOGIN_TOKEN = 4;
    ErrCodeEnum_INVALID_GAME_TICKET = 5;
    /**
     * gm命令找不到
     */
    ErrCodeEnum_GM_ACTION_NOT_FOUND = 6;
    /**
     * player not login or have logout
     */
    ErrCodeEnum_PLAYER_NOT_FOUND = 7;
    /**
     * 账号被封禁
     */
    ErrCodeEnum_ACCOUNT_BANNED = 8;
    /**
     * 关服
     */
    ErrCodeEnum_SERVER_CLOSED = 9;
    /**
     * 入参 不合法
     */
    ErrCodeEnum_INVALID_PARAM = 10;
    ErrCodeEnum_NAME_LENGTH_INVALID = 11;
    ErrCodeEnum_NOTICE_LENGTH_INVALID = 12;
    ErrCodeEnum_COST_NOT_ENOUGH = 13;
    /**
     * 配置找不到
     */
    ErrCodeEnum_CONFIG_NOT_FOUND = 14;
    ErrCodeEnum_COMPONENT_NOT_EXIST = 15;
    ErrCodeEnum_COMPONENT_CONSTRUCT_ERROR = 16;
    ErrCodeEnum_ENTER_SCENE_TOKEN_INVALID = 17;
    ErrCodeEnum_RET_PLAYER_NOT_ONLINE = 18;
    ErrCodeEnum_RECV_UNKNOWN_MSG_ID = 19;
    ErrCodeEnum_MSG_TEMP_DSABLE = 20;
    /**
     * 玩家 sdk 登录 错误
     */
    ErrCodeEnum_LOGIN_SDK_UNKNOWN = 21;
    /**
     * 玩家 sdk token 超时
     */
    ErrCodeEnum_LOGIN_SDK_TOKEN_TIME_OUT = 22;
    ErrCodeEnum_RET_ITEM_NOT_EXIST = 23;
    ErrCodeEnum_RET_ITEM_NOT_DROPABLE = 24;
    ErrCodeEnum_RET_ITEM_IS_LOCKED = 25;
    ErrCodeEnum_RET_EQUIP_WEARED_CANNOT_DROP = 26;
    ErrCodeEnum_RET_ITEM_COUNT_NOT_ENOUGH = 27;
    ErrCodeEnum_RET_BAG_FULL = 28;
    ErrCodeEnum_RET_COIN_NOT_ENOUGH = 29;
    ErrCodeEnum_RET_ITEM_CONFIG_NOT_FOUND = 30;
    ErrCodeEnum_RET_ITEM_PARAM_LIST_EMPTY = 31;
    ErrCodeEnum_RET_ITEM_TYPE_NOT_MATCH = 32;
    ErrCodeEnum_RET_ITEM_INVALID_COUNT = 33;
    ErrCodeEnum_RET_CAN_NOT_FOUND_BAG = 34;
    ErrCodeEnum_RET_WEAPON_INVALID = 35;
    ErrCodeEnum_RET_WEAPON_LV_IS_MAX = 36;
    ErrCodeEnum_RET_WEAPON_EXP_INVALID = 37;
    ErrCodeEnum_RET_WEAPON_CONFIG_NOT_FOUND = 38;
    ErrCodeEnum_RET_WEAPON_REFINE_IS_MAX = 39;
    ErrCodeEnum_RET_WEAPON_IS_LOCK = 40;
    ErrCodeEnum_RET_WEAPON_NOT_COST_SELF = 41;
    ErrCodeEnum_RET_WEAPON_SERMON_NOT_SAME = 42;
    ErrCodeEnum_RET_WEAPON_IS_WEARING = 43;
    ErrCodeEnum_RET_WEAPON_EXCEED_ALREADY = 44;
    ErrCodeEnum_RET_WEAPON_IS_WEARED = 45;
    ErrCodeEnum_RET_WEAPON_IS_NOT_WEARED = 46;
    /**
     * 未支持的使用道具效果类型
     */
    ErrCodeEnum_USE_ITEM_EFFECT_NOT_SUPPORTED = 47;
    ErrCodeEnum_RET_EQUIP_INVALID = 48;
    ErrCodeEnum_RET_EQUIP_LV_IS_MAX = 49;
    ErrCodeEnum_RET_EQUIP_EXP_INVALID = 50;
    ErrCodeEnum_RET_EQUIP_CONFIG_NOT_FOUND = 51;
    ErrCodeEnum_RET_EQUIP_REFINE_IS_MAX = 52;
    ErrCodeEnum_RET_EQUIP_IS_LOCK = 53;
    ErrCodeEnum_RET_EQUIP_NOT_COST_SELF = 54;
    ErrCodeEnum_RET_EQUIP_POS_NOT_SAME = 55;
    ErrCodeEnum_RET_EQUIP_IS_WEARING = 56;
    ErrCodeEnum_RET_EQUIP_EXCEED_ALREADY = 57;
    ErrCodeEnum_RET_EQUIP_IS_WEARED = 58;
    ErrCodeEnum_RET_EQUIP_IS_NOT_WEARED = 59;
    ErrCodeEnum_RET_EQUIP_MARK_INVALID = 60;
    ErrCodeEnum_RET_EQUIP_MARK_CONFIG_NOT_FOUND = 61;
    ErrCodeEnum_RET_EQUIP_HOLE_INVALID = 62;
    ErrCodeEnum_RET_EQUIP_MARK_QUALITY_INVALID = 63;
    ErrCodeEnum_RET_EQUIP_MARK_IS_INLAY = 64;
    ErrCodeEnum_RET_EQUIP_HOLE_NOT_INLAY = 65;
    ErrCodeEnum_RET_EQUIP_MARK_SUIT_NOUT_SAME = 66;
    ErrCodeEnum_FORMATION_CAN_NOT_FOUND = 67;
    ErrCodeEnum_FORMATION_AVATAR_COUNT_ERROR = 68;
    ErrCodeEnum_FORMATION_SKILL_COUNT_ERROR = 69;
    ErrCodeEnum_FORMATION_INVALID_ID = 70;
    /**
     * 找不到交互的目标
     */
    ErrCodeEnum_SCENE_INTERACT_NOT_FOUND_TARGET = 71;
    ErrCodeEnum_ERR_ALREADY_IN_SCENE = 72;
    /**
     * 不在场景中
     */
    ErrCodeEnum_ERR_NOT_IN_SCENE = 73;
    ErrCodeEnum_ERR_NOT_EXIST_SCENE = 74;
    ErrCodeEnum_SCENE_IS_FULL = 75;
    ErrCodeEnum_ENTITY_NOT_CONSTRUCT_CORRECT = 76;
    /**
     * 已经触发过交互
     */
    ErrCodeEnum_SCENE_INTERACT_TRIGGERED = 77;
    ErrCodeEnum_SCENE_PLAYER_NOT_FOUND = 78;
    /**
     * 不是可交互对象
     */
    ErrCodeEnum_SCENE_INTERACT_NOT_INTERACTABLE = 79;
    /**
     * 不在交互区域
     */
    ErrCodeEnum_SCENE_INTERACT_NOT_IN_RANGE = 80;
    ErrCodeEnum_SCENE_PLAYER_STATE_NOT_VALID = 81;
    ErrCodeEnum_SCENE_CAN_NOT_FOUND_CONFIG = 82;
    ErrCodeEnum_SCENE_NOT_ACTIVE_REST = 83;
    ErrCodeEnum_SCENE_NOT_FOUND_REST_CONFIG = 84;
    ErrCodeEnum_SCENE_GAME_STATE_NOT_PRE_ENTER = 85;
    ErrCodeEnum_SCENE_ALREADY_IN_CHANGE_SCENE_PROCESS = 86;
    ErrCodeEnum_SCENE_GAME_STATE_NOT_LOADING = 87;
    ErrCodeEnum_SCENE_REFRESH_MOTION_STATE_NOT_HAS_ACTIVE_ACTOR = 88;
    ErrCodeEnum_SCENE_CHECK_SPEED_NOT_HAS_ACTIVE_ACTOR = 89;
    ErrCodeEnum_SCENE_REFRESH_MOTION_STATE_NOT_ENOUGH_STAMINA = 90;
    /**
     * 发起交互的Actor不存在
     */
    ErrCodeEnum_SCENE_INTERACT_NOT_FOUND_MAN = 91;
    /**
     * 该玩家不是发起交互的Actor的控制者
     */
    ErrCodeEnum_SCENE_INTERACT_CANNOT_CONTROLLER = 92;
    /**
     * 不满足交互类型所需条件
     */
    ErrCodeEnum_SCENE_INTERACT_NOT_MET_OPTION_CONDITION = 93;
    /**
     * 交互状态没有变化
     */
    ErrCodeEnum_SCENE_INTERACT_STATE_NOT_CHANGE = 94;
    /**
     * 该物件不允许的交互类型
     */
    ErrCodeEnum_SCENE_INTERACT_NOT_ALLOW_OPTION_TYPE = 95;
    /**
     * 找不到这个商品
     */
    ErrCodeEnum_SHOP_CAN_NOT_FOUND_ITEM = 96;
    /**
     * 未到上架时间
     */
    ErrCodeEnum_SHOP_BEGIN_TIME_LIMIT = 97;
    /**
     * 已下架
     */
    ErrCodeEnum_SHOP_FINISH_TIME_LIMIT = 98;
    ErrCodeEnum_TEAM_ERROR_ALREADY_IN_TEAM = 99;
    ErrCodeEnum_TEAM_NOT_EXIST = 100;
    ErrCodeEnum_TEAM_REACH_MAX = 101;
    ErrCodeEnum_TEAM_HAVE_STARTED = 102;
    ErrCodeEnum_AVATAR_ITEM_NOT_ENOUGH = 103;
    /**
     * 等级已满
     */
    ErrCodeEnum_AVATAR_FAVORABILITY_LV_IS_MAX = 104;
    /**
     * 无效伙伴
     */
    ErrCodeEnum_AVATAR_INVALID_AVATER = 105;
    /**
     * 好感度经验无效
     */
    ErrCodeEnum_AVATAR_FAVORABILITY_EXP_INVALID = 106;
    /**
     * 好感度等级无效
     */
    ErrCodeEnum_AVATAR_FAVORABILITY_LV_INVALID = 107;
    /**
     * 好感度奖励重复领取
     */
    ErrCodeEnum_AVATAR_FAVORABILITY_AWARD_ALREADY_GOT = 108;
    /**
     * 好感度等级不足
     */
    ErrCodeEnum_AVATAR_FAVORABILITY_LV_NOT_ENOUGH = 109;
    /**
     * 好感度等级没有奖励
     */
    ErrCodeEnum_AVATAR_FAVORABILITY_LV_NOT_AWARD = 110;
    /**
     * 无效天赋配置
     */
    ErrCodeEnum_AVATAR_TALENT_INVALID_CFG = 111;
    /**
     * 天赋已升级
     */
    ErrCodeEnum_AVATAR_TALENT_ALREADY_LV_UP = 112;
    /**
     * 天赋前置未解锁
     */
    ErrCodeEnum_AVATAR_TALENT_PRE_NOT_UNLOCK = 113;
    /**
     * 天赋前置等级未升级
     */
    ErrCodeEnum_AVATAR_TALENT_PRE_LV_NOT_LV_UP = 114;
    /**
     * 天赋升级已满
     */
    ErrCodeEnum_AVATAR_TALENT_LV_IS_MAX = 115;
    /**
     * 伙伴等级不足
     */
    ErrCodeEnum_AVATAR_TALENT_AVATAR_LEVEL_NOT_ENOUGH = 116;
    /**
     * 核心等级不足
     */
    ErrCodeEnum_AVATAR_TALENT_CORE_LEVEL_NOT_ENOUGH = 117;
    /**
     * 天赋点不足
     */
    ErrCodeEnum_AVATAR_TALENT_POINT_NOT_ENOUGH = 118;
    /**
     * 无效命座配置
     */
    ErrCodeEnum_AVATAR_CONSTELLATION_INVALID_CFG = 119;
    /**
     * 命座解锁已满
     */
    ErrCodeEnum_AVATAR_CONSTELLATION_UNLOCK_COUNT_MAX = 120;
    /**
     * 命座解锁已解锁
     */
    ErrCodeEnum_AVATAR_CONSTELLATION_UNLOCK_ALREADY = 121;
    /**
     * 昵称含有屏蔽字符
     */
    ErrCodeEnum_CHANGE_NICKNAME_MASK_WORD = 122;
    /**
     * 昵称已被使用
     */
    ErrCodeEnum_CHANGE_NICKNAME_USED = 123;
    /**
     * 昵称长度不在规定范围内
     */
    ErrCodeEnum_CHANGE_NICKNAME_LENGTH = 124;
    /**
     * 头像还未解锁
     */
    ErrCodeEnum_CHANGE_ICON_IS_LOCKED = 125;
    /**
     * 无效邮件id
     */
    ErrCodeEnum_MAIL_ID_INVALID = 126;
    /**
     * 邮件过期
     */
    ErrCodeEnum_MAIL_TIME_OUT = 127;
    /**
     * 邮件已过期
     */
    ErrCodeEnum_MAIL_ALREADY_GOT_AWARD = 128;
    /**
     * 邮件收藏重复设置
     */
    ErrCodeEnum_MAIL_ALREADY_SET_COLLECT = 129;
    /**
     * 卡组未开放
     */
    ErrCodeEnum_GACHA_GROUP_NOT_OPENING = 130;
    /**
     * 无效掉落
     */
    ErrCodeEnum_GACHA_DROP_INVALID = 131;
    /**
     * 实体找不到
     */
    ErrCodeEnum_ENTITY_NOT_FOUND = 132;
    /**
     * 实体控制者不合法
     */
    ErrCodeEnum_ENTITY_CONTOLLER_NOT_VALALID = 133;
    /**
     * 实体不是战斗单元
     */
    ErrCodeEnum_ENTIRY_NOT_BATTLE_UNIT = 134;
    /**
     * 无效深渊
     */
    ErrCodeEnum_MAZE_INVALID = 135;
    /**
     * 重复领取奖励
     */
    ErrCodeEnum_MAZE_RECEIVE_STAR_REWARD_ALREADY = 136;
    /**
     * 无效奖励
     */
    ErrCodeEnum_MAZE_STAR_REWARD_INVALID = 137;
    /**
     * 无效深渊层
     */
    ErrCodeEnum_MAZE_LAYER_INVALID = 138;
    /**
     * 深渊层没有节点
     */
    ErrCodeEnum_MAZE_LAYER_NOT_NODE = 139;
    /**
     * 错误的挑战深渊层
     */
    ErrCodeEnum_MAZE_CHALLENGE_LAYER_NO_SAME = 140;
    /**
     * 挑战没有开始
     */
    ErrCodeEnum_MAZE_CHALLENGE_NOT_START = 141;
    /**
     * 挑战超时
     */
    ErrCodeEnum_MAZE_CHALLENGE_TIME_OUT = 142;
    /**
     * 深渊星数不足
     */
    ErrCodeEnum_MAZE_STAR_COUNT_NOT_ENOUGH = 143;
    /**
     * 深渊场景id错误
     */
    ErrCodeEnum_MAZE_SENCE_ID_ERROR = 144;
    /**
     * 深渊节点重复挑战
     */
    ErrCodeEnum_MAZE_NODE_CHALLENGE_ALREADY = 145;
    /**
     * 深渊队伍不匹配
     */
    ErrCodeEnum_MAZE_CHALLENGE_FORMATION_INVALID = 146;
    /**
     * 深层深渊已过期
     */
    ErrCodeEnum_MAZE_DOWN_TIME_OUT = 147;
    /**
     * 特权超过最大持续时间
     */
    ErrCodeEnum_PRIVILEGE_EXPIRE_TIME_MAX = 148;
    /**
     * 特权无效
     */
    ErrCodeEnum_PRIVILEGE_INVALID = 149;
    /**
     * 资源关卡已发现过
     */
    ErrCodeEnum_RESOURCE_LEVEL_ENTRANCE_IS_DISCOVERED = 150;
    /**
     * 关卡id无效
     */
    ErrCodeEnum_RESOURCE_LEVEL_ID_INVALID = 151;
    /**
     * 关卡难度无效
     */
    ErrCodeEnum_RESOURCE_LEVEL_DIFFICULTY_INVALID = 152;
    /**
     * 世界等级不足
     */
    ErrCodeEnum_RESOURCE_LEVEL_WORLD_LEVEL_NOT_ENOUGH = 153;
    /**
     * 难度不符
     */
    ErrCodeEnum_RESOURCE_LEVEL_DIFFICULTY_NOT_SAME = 154;
    /**
     * 体力不足
     */
    ErrCodeEnum_RESOURCE_LEVEL_POWER_NOT_ENOUGH = 155;
    /**
     * 场景id无效
     */
    ErrCodeEnum_SCENE_ID_INVALID = 156;
    /**
     * 后备疲劳不足
     */
    ErrCodeEnum_FATIGUE_STANDBY_NOT_ENOUGH = 157;
    /**
     * 收集奖励已领
     */
    ErrCodeEnum_COLLECT_REWARD_ALREADY = 158;
    /**
     * 收集道具不足
     */
    ErrCodeEnum_COLLECT_ITEM_NOT_ENOUGH = 159;
    /**
     * 关卡id无效
     */
    ErrCodeEnum_RANDOM_ISLAND_LEVEL_ID_INVALID = 160;
    /**
     * 关卡世界等级无效
     */
    ErrCodeEnum_RANDOM_ISLAND_LEVEL_WORLD_LEVEL_INVALID = 161;
    /**
     * 没有伙伴
     */
    ErrCodeEnum_TRAIN_LEVEL_NOT_HAS_AVATAR = 162;
    /**
     * 没找到活动
     */
    ErrCodeEnum_ACTIVITY_NOT_FOUND = 163;
    /**
     * 活动无效
     */
    ErrCodeEnum_ACTIVITY_IS_INVALID = 164;
    /**
     * 活动奖励已领
     */
    ErrCodeEnum_ACTIVITY_REWARD_ALREADY = 165;
    /**
     * 陆礁超时
     */
    ErrCodeEnum_RANDOM_ACTOR_TIME_OUT = 166;
    /**
     * 该系统已关闭
     */
    ErrCodeEnum_SYSTEM_CLOSE = 167;
    /**
     * 玩家等级奖励重复领取
     */
    ErrCodeEnum_ROLE_LEVEL_REWARD_ALREADY = 168;
    /**
     * 账号注销
     */
    ErrCodeEnum_CLOSE_ACCOUNT = 169;
    /**
     * 商品tag找不到
     */
    ErrCodeEnum_SHOP_TAG_NOT_FOUND = 170;
    /**
     * 商品tag关闭
     */
    ErrCodeEnum_SHOP_TAG_CLOSE = 171;
    /**
     * 商品没解锁
     */
    ErrCodeEnum_SHOP_ITEM_NOT_UNLOCK = 172;
    /**
     * 不在白名单内
     */
    ErrCodeEnum_NOT_ON_WHITE_LIST = 173;
    /**
     * 玩家等级不足
     */
    ErrCodeEnum_PLAYER_LEVEL_NOT_ENOUGH = 174;
    /**
     * 场景不允许传送
     */
    ErrCodeEnum_SCENE_NOT_TELEPORT = 175;
    /**
     * 抽卡次数不足
     */
    ErrCodeEnum_GACHA_PULL_COUNT_NOT_ENOUGH = 176;
    /**
     * 非sdk登录
     */
    ErrCodeEnum_SHOP_NOT_SDK_LOGIN = 177;
    /**
     * 物品回收重复
     */
    ErrCodeEnum_ITEM_RECYCLE_DUPE = 178;
    /**
     * 物品不可回收
     */
    ErrCodeEnum_ITEM_RECYCLE_CANT_RECYCLE = 179;
    /**
     * 回收数量超过上限
     */
    ErrCodeEnum_ITEM_RECYCLE_TOO_MANY = 180;
    /**
     * 不可回收装备中的物品
     */
    ErrCodeEnum_ITEM_RECYCLE_IS_EQUIPED = 181;
    /**
     * 高稀有度道具不可回收
     */
    ErrCodeEnum_ITEM_RECYCLE_OVER_QUALITY = 182;
    /**
     * 回收道具不是同种类型
     */
    ErrCodeEnum_ITEM_RECYCLE_NOT_SAME_BAG = 183;
    /**
     * 回收参数错误
     */
    ErrCodeEnum_ITEM_RECYCLE_PARAM_FAIL = 184;
    /**
     * 无效的场景区域
     */
    ErrCodeEnum_INVALID_SERVER_BOUND_VOLUME = 185;
    /**
     * 道具快速合成目标道具充满足
     */
    ErrCodeEnum_ITEM_FAST_SYNTHESIS_ITEM_ENOUGH = 186;
    /**
     * boss本挑战次数不足
     */
    ErrCodeEnum_BOSS_LEVEL_CHALLENGE_COUNT_NOT_ENOUGH = 187;
    /**
     * boss挑战本未解锁
     */
    ErrCodeEnum_BOSS_LEVEL_CHALLENGE_LEVEL_NOT_UNLCOK = 188;
    /**
     * boss挑战本buff无效
     */
    ErrCodeEnum_BOSS_LEVEL_BUFF_INVALID = 189;
    /**
     * 背包已满,道具发送到邮件
     */
    ErrCodeEnum_BAG_FULL_TO_MAIL = 190;
    /**
     * 无效本源
     */
    ErrCodeEnum_ASTROLABE_IS_INVALID = 191;
    /**
     * 本源锁定
     */
    ErrCodeEnum_ASTROLABE_IS_LOCK = 192;
    /**
     * 本源已激活
     */
    ErrCodeEnum_ASTROLABE_IS_ACTIVATED = 193;
    /**
     * 本源重复镶嵌
     */
    ErrCodeEnum_ASTROLABE_SLOT_INLAYED_ALREADY = 194;
    /**
     * 本源孔位和祈玉类型不一致
     */
    ErrCodeEnum_ASTROLABE_SLOT_MARK_TYPE_NOT_SAME = 195;
    /**
     * 商品购买超过限制
     */
    ErrCodeEnum_SHOP_BUY_LIMIT_EXCEEDED = 196;
    /**
     * 该祈玉副本未解锁
     */
    ErrCodeEnum_MARK_LEVEL_NOT_UNLOCK = 197;
    /**
     * 祈玉副本消耗道具不足
     */
    ErrCodeEnum_MARK_LEVEL_COST_ITEM_LACK = 198;
    /**
     * 祈玉副本没有节点
     */
    ErrCodeEnum_MARK_LEVEL_NOT_NODE = 199;
    /**
     * 道具guid重复
     */
    ErrCodeEnum_RET_ITEM_DUPE = 200;
    /**
     * 家园等级已满
     */
    ErrCodeEnum_HOME_LEVEL_MAX = 201;
    /**
     * 家园经验不够
     */
    ErrCodeEnum_HOME_EXP_NOT_REACH = 202;
    /**
     * 愿心已满,不能继续获得
     */
    ErrCodeEnum_HOME_EXP_FULL = 203;
    /**
     * 上一次祷告还未结束,不能开始
     */
    ErrCodeEnum_HOME_WISH_STATUS_ERROR = 204;
    /**
     * 祷告次数已达上限
     */
    ErrCodeEnum_HOME_WISH_DAY_COUNT_MAX = 205;
    /**
     * 没有设置祷告英雄
     */
    ErrCodeEnum_HOME_WISH_NO_AVATAR = 206;
    /**
     * 祷告英雄重复
     */
    ErrCodeEnum_HOME_WISH_AVATAR_DUPE = 207;
    /**
     * 没有找到祷告英雄
     */
    ErrCodeEnum_HOME_WISH_AVATAR_NOT_FOUND = 208;
    /**
     * 祷告英雄超过家园上限
     */
    ErrCodeEnum_HOME_WISH_AVATAR_TOO_MUCH = 209;
    /**
     * 祷告还未结束,不能收取
     */
    ErrCodeEnum_HOME_WISH_NOT_FINISH = 210;
    /**
     * 任务未完成
     */
    ErrCodeEnum_QUEST_NOT_FINISH = 211;
    /**
     * 已经在一个互动了
     */
    ErrCodeEnum_INTIMACY_INTERACTING = 212;
    /**
     * 配方未学习
     */
    ErrCodeEnum_ITEM_CRAFT_RECIPE_NOT_LEARN = 213;
    /**
     * 配方已经学习过
     */
    ErrCodeEnum_ITEM_CRAFT_ALREADY_LEARNED = 214;
    /**
     * 缺少配方物品
     */
    ErrCodeEnum_ITEM_CRAFT_NO_RECIPE_ITEM = 215;
    /**
     * 功能未解锁
     */
    ErrCodeEnum_SYSTEM_LOCKING = 216;
)

