
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 凡器状态
 */
const (
    /**
     * 未解锁
     */
    FanQiState_Locked = 0;
    /**
     * 已解锁
     */
    FanQiState_UnLocked = 1;
)

