
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 公式类型
 */
const (
    FormulationEnum_NONE = 0;
    /**
     * 自己定
     */
    FormulationEnum_EFormulate_1 = 1;
)

