
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    FuncHideType_NONE = 0;
    /**
     * 在深渊关卡中
     */
    FuncHideType_MAZE = 1;
    /**
     * 在战斗状态下
     */
    FuncHideType_BATTLE = 2;
    /**
     * 资源副本中
     */
    FuncHideType_RESOURCE = 3;
    /**
     * 随机陆礁
     */
    FuncHideType_RandomIsland = 4;
    /**
     * 教学关卡
     */
    FuncHideType_TeachLevel = 5;
    /**
     * 新添加的枚举要这个枚举前面
     */
    FuncHideType_MAX = 6;
)

