
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 玩法召唤物的类型
 */
const (
    /**
     * 零能装置
     */
    GamePlaySummonedType_ZERO_ENERGY = 0;
    /**
     * 寄生虫
     */
    GamePlaySummonedType_PARASITE = 1;
)

