
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type HerodataHeroData struct {
    Id int64
    CapsuleHalfHeight float32
    HeroAttributes map[int32]int32
    BreakWeaponCount int32
    ISDurability int32
}

const TypeId_HerodataHeroData = 1453097710

func (*HerodataHeroData) GetTypeId() int32 {
    return 1453097710
}

func NewHerodataHeroData(_buf map[string]interface{}) (_v *HerodataHeroData, err error) {
    _v = &HerodataHeroData{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_CapsuleHalfHeight__ interface{}; if __json_CapsuleHalfHeight__, _ok_ = _buf["CapsuleHalfHeight"]; !_ok_ || __json_CapsuleHalfHeight__ == nil { err = errors.New("CapsuleHalfHeight error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_CapsuleHalfHeight__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.CapsuleHalfHeight = __x__ }}
    { var _ok_ bool; var __json_Hero_Attributes__ interface{}; if __json_Hero_Attributes__, _ok_ = _buf["Hero_Attributes"]; !_ok_ || __json_Hero_Attributes__ == nil { err = errors.New("Hero_Attributes error"); return } else { var __x__ map[int32]int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok_ = (__json_Hero_Attributes__).([]interface{}); !_ok_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make(map[int32]int32)
                    
                    for _, _e0_ := range _arr0_ {
                        var _kv0_ []interface{}
                        if _kv0_, _ok0_ = _e0_.([]interface{}); !_ok0_ || len(_kv0_) != 2 { err = errors.New("__x__ error"); return }
                        var _key0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _kv0_[0].(float64); !_ok_ { err = errors.New("_key0_ error"); return }; _key0_ = int32(_x_) }
                        var _value0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _kv0_[1].(float64); !_ok_ { err = errors.New("_value0_ error"); return }; _value0_ = int32(_x_) }
                        __x__[_key0_] = _value0_
                    }
                    }; _v.HeroAttributes = __x__ }}
    { var _ok_ bool; var __json_BreakWeaponCount__ interface{}; if __json_BreakWeaponCount__, _ok_ = _buf["BreakWeaponCount"]; !_ok_ || __json_BreakWeaponCount__ == nil { err = errors.New("BreakWeaponCount error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_BreakWeaponCount__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BreakWeaponCount = __x__ }}
    { var _ok_ bool; var __json_IS_Durability__ interface{}; if __json_IS_Durability__, _ok_ = _buf["IS_Durability"]; !_ok_ || __json_IS_Durability__ == nil { err = errors.New("IS_Durability error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_IS_Durability__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ISDurability = __x__ }}
    return
}

