
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * None
     */
    HeroPropGroup_NONE = 0;
    /**
     * 基础生命
     */
    HeroPropGroup_A1 = 1;
    /**
     * 基础生命倍率
     */
    HeroPropGroup_A2 = 2;
    /**
     * 基础生命加值
     */
    HeroPropGroup_A3 = 3;
    /**
     * 额外生命倍率
     */
    HeroPropGroup_A4 = 4;
    /**
     * 额外生命加值
     */
    HeroPropGroup_A5 = 5;
    /**
     * 基础攻击
     */
    HeroPropGroup_B1 = 6;
    /**
     * 基础攻击倍率
     */
    HeroPropGroup_B2 = 7;
    /**
     * 基础攻击加值
     */
    HeroPropGroup_B3 = 8;
    /**
     * 额外攻击倍率
     */
    HeroPropGroup_B4 = 9;
    /**
     * 额外攻击加值
     */
    HeroPropGroup_B5 = 10;
    /**
     * 基础防御
     */
    HeroPropGroup_C1 = 11;
    /**
     * 基础防御倍率
     */
    HeroPropGroup_C2 = 12;
    /**
     * 基础防御加值
     */
    HeroPropGroup_C3 = 13;
    /**
     * 额外防御倍率
     */
    HeroPropGroup_C4 = 14;
    /**
     * 额外防御加值
     */
    HeroPropGroup_C5 = 15;
)

