
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 属性展示类型
 */
const (
    /**
     * 无类型
     */
    HeroPropDisplayType_NONE = 0;
    /**
     * 百分比
     */
    HeroPropDisplayType_Percentage = 1;
    /**
     * 属性增长或消耗
     */
    HeroPropDisplayType_RatePerSeconds = 2;
    /**
     * 速度
     */
    HeroPropDisplayType_Velocity = 3;
)

