
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type HerodataPropsGroup struct {
    Group int32
    PropIdList []int32
}

const TypeId_HerodataPropsGroup = -1756095335

func (*HerodataPropsGroup) GetTypeId() int32 {
    return -1756095335
}

func NewHerodataPropsGroup(_buf map[string]interface{}) (_v *HerodataPropsGroup, err error) {
    _v = &HerodataPropsGroup{}
    { var _ok_ bool; var __json_Group__ interface{}; if __json_Group__, _ok_ = _buf["Group"]; !_ok_ || __json_Group__ == nil { err = errors.New("Group error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Group__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Group = __x__ }}
    { var _ok_ bool; var __json_PropIdList__ interface{}; if __json_PropIdList__, _ok_ = _buf["PropIdList"]; !_ok_ || __json_PropIdList__ == nil { err = errors.New("PropIdList error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_PropIdList__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.PropIdList = __x__ }}
    return
}

