
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type HerodataTbHeroData struct {
    _dataMap map[int64]*HerodataHeroData
    _dataList []*HerodataHeroData
}

func NewHerodataTbHeroData(_buf []map[string]interface{}) (*HerodataTbHeroData, error) {
    _dataList := make([]*HerodataHeroData, 0, len(_buf))
    dataMap := make(map[int64]*HerodataHeroData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewHerodataHeroData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &HerodataTbHeroData{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *HerodataTbHeroData) GetDataMap() map[int64]*HerodataHeroData {
    return table._dataMap
}

func (table *HerodataTbHeroData) GetDataList() []*HerodataHeroData {
    return table._dataList
}

func (table *HerodataTbHeroData) Get(key int64) *HerodataHeroData {
    return table._dataMap[key]
}


