
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 有Prop_Rate时，必须紧跟着Prop属性下一行，只能往后面加枚举，不能中间插入
     */
    HeroProp_NONE = 0;
    /**
     * 最大生命值
     */
    HeroProp_MaxHealth = 1;
    /**
     * 初始生命值
     */
    HeroProp_Health = 2;
    /**
     * 攻击力
     */
    HeroProp_Attack = 3;
    /**
     * 防御力
     */
    HeroProp_Defense = 4;
    /**
     * 暴击率
     */
    HeroProp_Critical_Rate = 5;
    /**
     * 暴击伤害倍率
     */
    HeroProp_Critical_DamageRate = 6;
    /**
     * 最大韧性
     */
    HeroProp_MaxPoise = 7;
    /**
     * 韧性
     */
    HeroProp_Poise = 8;
    /**
     * 当前最大韧性比例
     */
    HeroProp_MaxPoiseCurrentRate = 9;
    /**
     * 韧性延迟回复时间
     */
    HeroProp_Poise_RecoverDelay = 10;
    /**
     * 韧性回复速度
     */
    HeroProp_Poise_Recover = 11;
    /**
     * 韧性回复速度率
     */
    HeroProp_Poise_Recover_Rate = 12;
    /**
     * 通用伤害减免
     */
    HeroProp_DamageReduction = 13;
    /**
     * 通用伤害加成
     */
    HeroProp_AmplifyDamage = 14;
    /**
     * 冰属性抗性
     */
    HeroProp_IceResistance = 15;
    /**
     * 火属性抗性
     */
    HeroProp_FireResistance = 16;
    /**
     * 风属性抗性
     */
    HeroProp_WindResistance = 17;
    /**
     * 雷属性抗性
     */
    HeroProp_ThunderResistance = 18;
    /**
     * 冲击属性抗性
     */
    HeroProp_LightResistance = 19;
    /**
     * 侵蚀属性抗性
     */
    HeroProp_DarkResistance = 20;
    /**
     * 体力上限
     */
    HeroProp_MaxStamina = 21;
    /**
     * 初始体力
     */
    HeroProp_Stamina = 22;
    /**
     * 体力恢复频率（单位毫秒）
     */
    HeroProp_Stamina_Recover_Freq = 23;
    /**
     * 体力回复速度
     */
    HeroProp_Stamina_Recover = 24;
    /**
     * 体力回复倍率（攻击中）
     */
    HeroProp_Stamina_Recover_Attack_Rate = 25;
    /**
     * 体力爆缸后CD
     */
    HeroProp_Stamina_Overheat = 26;
    /**
     * 体力消耗速度
     */
    HeroProp_Stamina_Consume = 27;
    /**
     * 必杀槽上限
     */
    HeroProp_MaxExSkillEnergy = 28;
    /**
     * 初始必杀槽
     */
    HeroProp_ExSkillEnergy = 29;
    /**
     * 必杀槽回复
     */
    HeroProp_ExSkillEnergy_Recover = 30;
    /**
     * 特殊槽预留1
     */
    HeroProp_SP0 = 31;
    /**
     * 特殊槽预留2
     */
    HeroProp_MaxSP0 = 32;
    /**
     * 特殊槽预留3
     */
    HeroProp_SP_Param3 = 33;
    /**
     * 特殊槽预留4
     */
    HeroProp_SP_Param4 = 34;
    /**
     * 最大行走速度
     */
    HeroProp_MaxWalkSpeed = 35;
    /**
     * 最大跑步速度
     */
    HeroProp_MaxRunSpeed = 36;
    /**
     * 最大疾跑速度
     */
    HeroProp_MaxSprintSpeed = 37;
    /**
     * 等级
     */
    HeroProp_Level = 38;
    /**
     * 霸体
     */
    HeroProp_SuperArmor = 39;
    /**
     * 弹刀值
     */
    HeroProp_Repell = 40;
    /**
     * 最大生命值总倍率
     */
    HeroProp_MaxHealth_Total_Rate = 41;
    /**
     * 最大生命加值
     */
    HeroProp_MaxHealth_Ext = 42;
    /**
     * 攻击力总倍率
     */
    HeroProp_Attack_Total_Rate = 43;
    /**
     * 攻击力加值
     */
    HeroProp_Attack_Ext = 44;
    /**
     * 防御力总倍率
     */
    HeroProp_Defense_Total_Rate = 45;
    /**
     * 防御力加值
     */
    HeroProp_Defense_Ext = 46;
    /**
     * 武器最大生命值
     */
    HeroProp_Weapon_MaxHealth = 47;
    /**
     * 武器最大生命值倍率
     */
    HeroProp_Weapon_MaxHealth_Rate = 48;
    /**
     * 武器攻击力
     */
    HeroProp_Weapon_Attack = 49;
    /**
     * 武器攻击力率
     */
    HeroProp_Weapon_Attack_Rate = 50;
    /**
     * 武器防御力
     */
    HeroProp_Weapon_Defense = 51;
    /**
     * 武器防御力率
     */
    HeroProp_Weapon_Defense_Rate = 52;
    /**
     * 装备最大生命值
     */
    HeroProp_Equip_MaxHealth = 53;
    /**
     * 装备最大生命值倍率
     */
    HeroProp_Equip_MaxHealth_Rate = 54;
    /**
     * 装备攻击力
     */
    HeroProp_Equip_Attack = 55;
    /**
     * 装备攻击力率
     */
    HeroProp_Equip_Attack_Rate = 56;
    /**
     * 装备防御力
     */
    HeroProp_Equip_Defense = 57;
    /**
     * 装备防御力率
     */
    HeroProp_Equip_Defense_Rate = 58;
    /**
     * 天赋最大生命值
     */
    HeroProp_Talent_MaxHealth = 59;
    /**
     * 天赋最大生命值倍率
     */
    HeroProp_Talent_MaxHealth_Rate = 60;
    /**
     * 天赋攻击力
     */
    HeroProp_Talent_Attack = 61;
    /**
     * 天赋攻击力率
     */
    HeroProp_Talent_Attack_Rate = 62;
    /**
     * 天赋防御力
     */
    HeroProp_Talent_Defense = 63;
    /**
     * 天赋防御力率
     */
    HeroProp_Talent_Defense_Rate = 64;
    /**
     * 特殊槽2参数1
     */
    HeroProp_SP1 = 65;
    /**
     * 特殊槽2参数2
     */
    HeroProp_MaxSP1 = 66;
    /**
     * 特殊槽2参数3
     */
    HeroProp_SP1_Param3 = 67;
    /**
     * 特殊槽2参数4
     */
    HeroProp_SP1_Param4 = 68;
    /**
     * 伤害倍率提升
     */
    HeroProp_Damage_Ratio_Rate = 69;
    /**
     * 怪物冰属性抗性增加（作用怪物）
     */
    HeroProp_IceResistance_Ext = 70;
    /**
     * 怪物火属性抗性增加（作用怪物）
     */
    HeroProp_FireResistance_Ext = 71;
    /**
     * 怪物风属性抗性增加（作用怪物）
     */
    HeroProp_ThunderResistance_Ext = 72;
    /**
     * 怪物雷属性抗性增加（作用怪物）
     */
    HeroProp_WindResistance_Ext = 73;
    /**
     * 怪物冲击属性抗性增加（作用怪物）
     */
    HeroProp_LightResistance_Ext = 74;
    /**
     * 怪物侵蚀属性抗性增加（作用怪物）
     */
    HeroProp_DarkResistance_Ext = 75;
    /**
     * 怪物冰属性抗性减免（作用角色）
     */
    HeroProp_IceResistance_Reduction = 76;
    /**
     * 怪物火属性抗性减免（作用角色）
     */
    HeroProp_FireResistance_Reduction = 77;
    /**
     * 怪物风属性抗性减免（作用角色）
     */
    HeroProp_ThunderResistance_Reduction = 78;
    /**
     * 怪物雷属性抗性减免（作用角色）
     */
    HeroProp_WindResistance_Reduction = 79;
    /**
     * 怪物冲击属性抗性减免（作用角色）
     */
    HeroProp_LightResistance_Reduction = 80;
    /**
     * 怪物侵蚀属性抗性减免（作用角色）
     */
    HeroProp_DarkResistance_Reduction = 81;
    /**
     * 延迟开始恢复体力（单位毫秒）
     */
    HeroProp_Stamina_RecoverDelay = 82;
    /**
     * 瞬间脉冲速度
     */
    HeroProp_ImmediatelyPulseSpeed = 83;
    /**
     * 冰属性异常条
     */
    HeroProp_Ice_Abnormal = 84;
    /**
     * 冰属性异常条最大值
     */
    HeroProp_Ice_Abnormal_Max = 85;
    /**
     * 火属性异常条
     */
    HeroProp_Fire_Abnormal = 86;
    /**
     * 火属性异常条最大值
     */
    HeroProp_Fire_Abnormal_Max = 87;
    /**
     * 风属性异常条
     */
    HeroProp_Wind_Abnormal = 88;
    /**
     * 风属性异常条最大值
     */
    HeroProp_Wind_Abnormal_Max = 89;
    /**
     * 电属性异常条
     */
    HeroProp_Thunder_Abnormal = 90;
    /**
     * 电属性异常条最大值
     */
    HeroProp_Thunder_Abnormal_Max = 91;
    /**
     * 光属性异常条
     */
    HeroProp_Light_Abnormal = 92;
    /**
     * 光属性异常条最大值
     */
    HeroProp_Light_Abnormal_Max = 93;
    /**
     * 暗属性异常条
     */
    HeroProp_Dark_Abnormal = 94;
    /**
     * 暗属性异常条最大值
     */
    HeroProp_Dark_Abnormal_Max = 95;
    /**
     * 目标受到的冰属性异常积攒率
     */
    HeroProp_Ice_Abnormal_Rate = 96;
    /**
     * 目标受到的火属性异常积攒率
     */
    HeroProp_Fire_Abnormal_Rate = 97;
    /**
     * 目标受到的风属性异常积攒率
     */
    HeroProp_Wind_Abnormal_Rate = 98;
    /**
     * 目标受到的电属性异常积攒率
     */
    HeroProp_Thunder_Abnormal_Rate = 99;
    /**
     * 目标受到的光属性异常积攒率
     */
    HeroProp_Light_Abnormal_Rate = 100;
    /**
     * 目标受到的暗属性异常积攒率
     */
    HeroProp_Dark_Abnormal_Rate = 101;
    /**
     * 属性亲和
     */
    HeroProp_Element_Quantity = 102;
    /**
     * 属性强度
     */
    HeroProp_Element_Strength = 103;
    /**
     * 异常伤害倍率
     */
    HeroProp_abnormal_damageRate = 104;
    /**
     * 虚弱BuffID
     */
    HeroProp_WeaknessBuffID = 105;
    /**
     * SP0获取倍率
     */
    HeroProp_SP0_gainrate = 106;
    /**
     * SP0消耗倍率
     */
    HeroProp_SP0_consumerate = 107;
    /**
     * SP1获取倍率
     */
    HeroProp_SP1_gainrate = 108;
    /**
     * SP1消耗倍率
     */
    HeroProp_SP1_consumerate = 109;
    /**
     * 必杀回复倍率
     */
    HeroProp_EX_EnergyRate = 110;
    /**
     * 穿透率
     */
    HeroProp_PentrationRate = 111;
    /**
     * 穿透值
     */
    HeroProp_PentrationValue = 112;
    /**
     * 穿透值%
     */
    HeroProp_PentrationValueRate = 113;
    /**
     * 穿透抵抗值
     */
    HeroProp_PentrationDefense = 114;
    /**
     * 穿透抵抗值%
     */
    HeroProp_PentrationDefenseRata = 115;
    /**
     * 未穿透减伤率
     */
    HeroProp_PentrationReduce = 116;
    /**
     * 耐久度
     */
    HeroProp_Durability = 117;
    /**
     * 最大耐久度
     */
    HeroProp_MaxDurability = 118;
    /**
     * 耐久度%
     */
    HeroProp_DurabilityRate = 119;
    /**
     * 护甲攻击
     */
    HeroProp_ArmorAttack = 120;
    /**
     * 护甲攻击%
     */
    HeroProp_ArmorAttackRate = 121;
    /**
     * 护甲伤害减免率
     */
    HeroProp_ArmorReduce = 122;
    /**
     * 攻击距离
     */
    HeroProp_Distance = 123;
    /**
     * 开始衰减距离
     */
    HeroProp_DistanceMin = 124;
    /**
     * 衰减结束距离
     */
    HeroProp_DistanceMax = 125;
    /**
     * 最大衰减率
     */
    HeroProp_DistanceReduceMax = 126;
    /**
     * 最小衰减率
     */
    HeroProp_DistanceReduceMin = 127;
    /**
     * 衰减率
     */
    HeroProp_DistanceReduce = 128;
    /**
     * 冰印记层数
     */
    HeroProp_Ice_Abnormal_Layer = 129;
    /**
     * 火印记层数
     */
    HeroProp_Fire_Abnormal_Layer = 130;
    /**
     * 风印记层数
     */
    HeroProp_Wind_Abnormal_Layer = 131;
    /**
     * 电印记层数
     */
    HeroProp_Thunder_Abnormal_Layer = 132;
    /**
     * 光印记层数
     */
    HeroProp_Light_Abnormal_Layer = 133;
    /**
     * 暗印记层数
     */
    HeroProp_Dark_Abnormal_Layer = 134;
    /**
     * 冰印记最大层数
     */
    HeroProp_Ice_Abnormal_MaxLayer = 135;
    /**
     * 火印记最大层数
     */
    HeroProp_Fire_Abnormal_MaxLayer = 136;
    /**
     * 风印记最大层数
     */
    HeroProp_Wind_Abnormal_MaxLayer = 137;
    /**
     * 电印记最大层数
     */
    HeroProp_Thunder_Abnormal_MaxLayer = 138;
    /**
     * 光印记最大层数
     */
    HeroProp_Light_Abnormal_MaxLayer = 139;
    /**
     * 暗印记最大层数
     */
    HeroProp_Dark_Abnormal_MaxLayer = 140;
    /**
     * 水平位移缩放率
     */
    HeroProp_HorizontalMoving_Ratio_Rate = 141;
    /**
     * 滑翔体力上限
     */
    HeroProp_MaxStamina_glide = 142;
    /**
     * 滑翔初始体力
     */
    HeroProp_Stamina_glide = 143;
    /**
     * 滑翔体力恢复速度
     */
    HeroProp_Stamina_glide_Recover = 144;
    /**
     * 滑翔最大速度
     */
    HeroProp_MaxGlideSpeed = 145;
    /**
     * 全元素异常累积效率提升
     */
    HeroProp_Abnormal_Rate_increased = 146;
    /**
     * 火元素异常累积效率提升
     */
    HeroProp_Fire_Abnormal_Rate_increased = 147;
    /**
     * 冰元素异常累积效率提升
     */
    HeroProp_Ice_Abnormal_Rate_increased = 148;
    /**
     * 雷元素异常累积效率提升
     */
    HeroProp_Thunder_Abnormal_Rate_increased = 149;
    /**
     * 风元素异常累积效率提升
     */
    HeroProp_Wind_Abnormal_Rate_increased = 150;
    /**
     * 光元素异常累积效率提升
     */
    HeroProp_Light_Abnormal_Rate_increased = 151;
    /**
     * 暗元素异常累积效率提升
     */
    HeroProp_Dark_Abnormal_Rate_increased = 152;
    /**
     * 秩序减抗
     */
    HeroProp_OrderResistance_Red_Ext = 153;
    /**
     * 复仇减抗
     */
    HeroProp_RevengeResistance_Red_Ext = 154;
    /**
     * 征服减抗
     */
    HeroProp_ConquerResistance_Red_Ext = 155;
    /**
     * 求知减抗
     */
    HeroProp_KnowledgeResistance_Red_Ext = 156;
    /**
     * 同心减抗
     */
    HeroProp_UnitedResistance_Red_Ext = 157;
    /**
     * 丰饶减抗
     */
    HeroProp_AbundanceResistance_Red_Ext = 158;
    /**
     * 天人减抗
     */
    HeroProp_SupremeResistance_Red_Ext = 159;
    /**
     * 火元素伤害加成
     */
    HeroProp_Fire_Damage_Rate = 160;
    /**
     * 冰元素伤害加成
     */
    HeroProp_Ice_Damage_Rate = 161;
    /**
     * 雷元素伤害加成
     */
    HeroProp_Thunder_Damage_Rate = 162;
    /**
     * 风元素伤害加成
     */
    HeroProp_Wind_Damage_Rate = 163;
    /**
     * 光元素伤害加成
     */
    HeroProp_Light_Damage_Rate = 164;
    /**
     * 暗元素伤害加成
     */
    HeroProp_Dark_Damage_Rate = 165;
    /**
     * 默认喷气能量上限
     */
    HeroProp_MaxDefaultAirInjectionEnergy = 166;
    /**
     * 充能喷气能量上限
     */
    HeroProp_MaxChargeAirInjectionEnergy = 167;
    /**
     * 初始喷气能量
     */
    HeroProp_AirInjectionEnergy = 168;
    /**
     * 恢复喷气能量速度
     */
    HeroProp_RecoverAirInjectionEnergySpeed = 169;
    /**
     * 结晶扩散系数
     */
    HeroProp_Element_Infection_Rate = 170;
    /**
     * 结晶扩散半径
     */
    HeroProp_Element_Infection_Distance = 171;
    /**
     * 标记能量（怪物用-无最大值）
     */
    HeroProp_MarkedEnergy = 172;
    /**
     * 受击吸附位移系数
     */
    HeroProp_HitDisplacement_Ratio = 173;
    /**
     * 载重值
     */
    HeroProp_Weight = 174;
    /**
     * 属性类型(元素属性)
     */
    HeroProp_Attribute = 175;
    /**
     * 通用治疗加成
     */
    HeroProp_AmplifyHeal = 176;
    /**
     * 通用治疗加成（外围系统用）
     */
    HeroProp_AmplifyHeal_Sys = 177;
    /**
     * 初始护盾值
     */
    HeroProp_Shield = 178;
    /**
     * 根据炮同时发射子弹数不同进行倍率修正
     */
    HeroProp_Attack_Ratio_Adjust = 179;
    /**
     * 通用的伤害加成/减少(攻击方)
     */
    HeroProp_AmplifyDamage_Rate = 180;
    /**
     * 通用的伤害加成/减免(防御方)
     */
    HeroProp_DamageReduction_Rate = 181;
    /**
     * 伤害补正（/10000）
     */
    HeroProp_DamageCorrection = 182;
    /**
     * 对此类伤害进行%提升或降低
     */
    HeroProp_Damage_Rate = 183;
    /**
     * 护盾值加值
     */
    HeroProp_Shield_Ext = 184;
    /**
     * 全元素伤害加成
     */
    HeroProp_Allelement_Damage_Rate = 185;
    /**
     * 枚举最大值（在该行上方新增属性）
     */
    HeroProp_Max = 186;
)

