
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 0
     */
    HitPowerType_None = 0;
    /**
     * 1
     */
    HitPowerType_BlendAttack = 1;
    /**
     * 2
     */
    HitPowerType_LightAttack = 2;
    /**
     * 3
     */
    HitPowerType_HeavyAttack = 3;
    /**
     * 4
     */
    HitPowerType_ChargeAttack = 4;
    /**
     * 5
     */
    HitPowerType_ThrowAttack = 5;
)

