
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 无受击
     */
    HitType_Hit_None = 0;
    /**
     * 受击融合
     */
    HitType_Hit_Blend = 1;
    /**
     * 小受击
     */
    HitType_Hit_Light = 2;
    /**
     * 大受击
     */
    HitType_Hit_Heavy = 3;
    /**
     * 击退
     */
    HitType_Hit_KnockOffLight = 4;
    /**
     * 大击飞
     */
    HitType_Hit_KnockOffHeavy = 5;
    /**
     * 挑空
     */
    HitType_Hit_Rise = 6;
    /**
     * 击倒
     */
    HitType_Hit_Smash = 7;
    /**
     * 弹开
     */
    HitType_Hit_Repell = 8;
    /**
     * 处决小受击
     */
    HitType_Hit_ExecutionLight = 9;
    /**
     * 处决大受击
     */
    HitType_Hit_ExecutionHeavy = 10;
    /**
     * 拼刀-击退
     */
    HitType_Hit_Parry_KnockBack = 11;
    /**
     * 拼刀-击飞
     */
    HitType_Hit_Parry_KnockOff = 12;
    /**
     * 拼刀-特殊
     */
    HitType_Hit_Parry_Special = 13;
    /**
     * 拼刀-其他
     */
    HitType_Hit_Parry_Other = 14;
    /**
     * 空中弹地
     */
    HitType_AirHit_Bounce = 15;
    /**
     * 空中击落
     */
    HitType_AirHit_Smash = 16;
    /**
     * 空中小受击
     */
    HitType_AirHit_Light = 17;
    /**
     * 空中大受击
     */
    HitType_AirHit_Heavy = 18;
    /**
     * 墙弹
     */
    HitType_AirHit_WallBounce = 19;
)

