
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 在大地图的Icon可视类型
 */
const (
    /**
     * 无
     */
    IconShowType_None = 0;
    /**
     * 完全隐藏
     */
    IconShowType_Hide = 1;
    /**
     * 完全显示
     */
    IconShowType_Show = 2;
    /**
     * 受迷雾影响
     */
    IconShowType_UnderFog = 3;
)

