
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未镶嵌
     */
    InlayTrapState_Not_Inlayed = 0;
    /**
     * 镶嵌
     */
    InlayTrapState_Inlayed = 1;
    /**
     * 举起
     */
    InlayTrapState_Lifted = 2;
)

