
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 说明百科显示类型
 */
const (
    InstructionShowType_NONE = 0;
    /**
     * 图文
     */
    InstructionShowType_PICTURE = 1;
    /**
     * 提示
     */
    InstructionShowType_TIPS = 2;
)

