
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    InstructionType_NONE = 0;
    /**
     * 战斗
     */
    InstructionType_BATTLE = 1;
    /**
     * 怪物
     */
    InstructionType_MONSTER = 2;
    /**
     * 系统
     */
    InstructionType_SYSTEM = 3;
    /**
     * 探索
     */
    InstructionType_RESEARCH = 4;
    /**
     * 常识
     */
    InstructionType_WORLDOUTLOOK = 5;
    /**
     * 新添加的枚举要这个枚举前面
     */
    InstructionType_MAX = 6;
)

