
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 说明百科的图文形式
 */
const (
    InstructionShowMode_NONE = 0;
    /**
     * 图片
     */
    InstructionShowMode_PICTURE = 1;
    /**
     * 视频
     */
    InstructionShowMode_VIDEO = 2;
)

