
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 交互按钮
 */
const (
    /**
     * 无
     */
    InteractionType_None = 0;
    /**
     * 传送至此
     */
    InteractionType_Teleport = 1;
    /**
     * 追踪
     */
    InteractionType_Trace = 2;
    /**
     * 追踪并传送
     */
    InteractionType_TraceAndTeleport = 3;
    /**
     * 打开内部地图
     */
    InteractionType_OpenMap = 4;
    /**
     * 传送至最近的一个可被传送的点
     */
    InteractionType_TeleportNearby = 5;
)

