
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 交互条件类型
 */
const (
    /**
     * 默认
     */
    InteractConditionType_Default = 0;
    /**
     * 交互物角度
     */
    InteractConditionType_ObjectAngle = 1;
    /**
     * 消耗道具
     */
    InteractConditionType_CostItem = 2;
    /**
     * 玩家Tag
     */
    InteractConditionType_PlayerTag = 3;
    /**
     * 交互物自身状态
     */
    InteractConditionType_OwnerState = 4;
    /**
     * 关联实例状态
     */
    InteractConditionType_LinkedInstancesStateCheck = 5;
    /**
     * 消耗零能
     */
    InteractConditionType_CostEnergy = 6;
)

