
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 基础交互物状态
 */
const (
    /**
     * 未激活
     */
    InteractiveActorState_NotActivated = 0;
    /**
     * 已激活
     */
    InteractiveActorState_Activated = 1;
    /**
     * 已完成
     */
    InteractiveActorState_Finished = 2;
)

