
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 交互模式
 */
const (
    /**
     * 不可交互
     */
    InteractMode_NONE = 0;
    /**
     * 访问交互, 进入交互范围显示交互UI
     */
    InteractMode_VISIT = 1;
    /**
     * 自动交互, 进入交互范围自动触发
     */
    InteractMode_AUTO = 2;
)

