
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 空气墙状态
 */
const (
    /**
     * 隐藏
     */
    InvisibleWallState_Hide = 0;
    /**
     * 激活
     */
    InvisibleWallState_Activated = 1;
)

