
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 空气墙类型
 */
const (
    /**
     * 带折返逻辑
     */
    InvisibleWallType_TypeA = 0;
    /**
     * 静态空气墙
     */
    InvisibleWallType_TypeB = 1;
)

