
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    KickOutType_NONE = 0;
    /**
     * GM踢人
     */
    KickOutType_GmBanRole = 1;
    /**
     * 重新登录
     */
    KickOutType_Relogin = 2;
    /**
     * 关服
     */
    KickOutType_ServerClosed = 3;
    /**
     * 注销账号
     */
    KickOutType_CloseAccount = 4;
    /**
     * 返回登录界面
     */
    KickOutType_BackToLogin = 5;
)

