
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未激活
     */
    LevelDeviceVolumeState_NotActivated = 0;
    /**
     * 已激活
     */
    LevelDeviceVolumeState_Activated = 1;
)

