
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * None
     */
    LevelLogicState_None = 0;
    /**
     * 是否激活
     */
    LevelLogicState_IsActivated = 1;
    /**
     * 能否交互
     */
    LevelLogicState_CanInteract = 2;
    /**
     * 是否锁定
     */
    LevelLogicState_IsLocked = 4;
)

