
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景内Actor加载的状态
 */
const (
    LevelLayerTagState_NONE = 0;
    LevelLayerTagState_LOADED = 1;
    LevelLayerTagState_WAIT_LOAD = 2;
    LevelLayerTagState_WAIT_REMOVE = 3;
    LevelLayerTagState_REMOVED = 4;
    LevelLayerTagState_WAIT_CLIENT_PRE_LOAD = 5;
)

