
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 锁定的类型
 */
const (
    /**
     * 解锁
     */
    LockState_UnLocked = 0;
    /**
     * 锁定
     */
    LockState_Locked = 1;
)

