
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未定义
     */
    LogicType_NONE = 0;
    /**
     * 与
     */
    LogicType_AND = 1;
    /**
     * 或
     */
    LogicType_OR = 2;
    /**
     * 非
     */
    LogicType_NOT = 3;
    /**
     * 第一个是必要条件，剩下逻辑或
     */
    LogicType_A_AND_ETCOR = 4;
    /**
     * 前两个是必要条件，剩下逻辑或
     */
    LogicType_A_AND_B_AND_ETCOR = 5;
    /**
     * 第一个是充分条件, 剩下逻辑与
     */
    LogicType_A_OR_ETCAND = 6;
    /**
     * 前两个是充分条件, 剩下逻辑与
     */
    LogicType_A_OR_B_OR_ETCAND = 7;
    /**
     * 满足前两个条件或剩下的所有条件
     */
    LogicType_A_AND_B_OR_ETCAND = 8;
)

