
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 关闭
     */
    MovingPlatformState_Closed = 0;
    /**
     * 自动运行
     */
    MovingPlatformState_Auto = 1;
)

