
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 叙事物件状态
 */
const (
    /**
     * 可交互状态
     */
    NarrativeActorState_Interact = 0;
    /**
     * 交互完成
     */
    NarrativeActorState_Finished = 1;
)

