
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 上一波里指定怪物死亡
     */
    NextBatchCondition_ELastBatchDead = 0;
    /**
     * 当上一波生成完后
     */
    NextBatchCondition_ELastBatchSpawned = 1;
    /**
     * 上一波怪全部死亡后
     */
    NextBatchCondition_ELastBatchAllDead = 2;
)

