
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 交互的操作类型
 */
const (
    /**
     * 默认
     */
    OptionType_Default = 0;
    /**
     * 解锁
     */
    OptionType_Unlock = 1;
    /**
     * 打开
     */
    OptionType_Open = 2;
    /**
     * 关闭
     */
    OptionType_Close = 3;
    /**
     * 拾取
     */
    OptionType_Collect = 4;
    /**
     * 激活
     */
    OptionType_Activate = 5;
    /**
     * 休息(休息点坐火)
     */
    OptionType_Rest = 6;
    /**
     * 破坏
     */
    OptionType_Destroy = 7;
    /**
     * 离开坐火
     */
    OptionType_Leave_Rest = 8;
    /**
     * 解谜
     */
    OptionType_Solve_Puzzle = 9;
    /**
     * 对话
     */
    OptionType_Talk = 10;
    /**
     * 传送
     */
    OptionType_Teleport = 11;
    /**
     * 完成AVG
     */
    OptionType_Finish_AVG = 12;
    /**
     * 深渊
     */
    OptionType_Maze = 13;
    /**
     * 关闭激活
     */
    OptionType_DeActivate = 14;
    /**
     * 恢复血量(海巡兽)
     */
    OptionType_Recover = 15;
    /**
     * 唤醒（唤醒NPC）
     */
    OptionType_Wake = 16;
    /**
     * 出生,仅限内部逻辑使用
     */
    OptionType_Spawn = 17;
)

