
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * params 枚举
 */
const (
    ParamKeyEnum_NONE = 0;
    /**
     * 玩家死亡后要启动的BUFF id
     */
    ParamKeyEnum_EXAMPLE_PARAM = 1;
    ParamKeyEnum_BUFF_WEAKNESS = 2;
    /**
     * 死亡复活后，必杀能量保留的比例（万分比）
     */
    ParamKeyEnum_DEATH_RETAIN_EX_RATIO = 3;
    /**
     * 死亡复活后，SP0能量保留的比例（万分比）
     */
    ParamKeyEnum_DEATH_RETAIN_SP0_RATIO = 4;
    /**
     * 死亡复活后，SP1能量保留的比例（万分比）
     */
    ParamKeyEnum_DEATH_RETAIN_SP1_RATIO = 5;
    /**
     * 海巡兽-防御等级参数
     */
    ParamKeyEnum_FML_DEF_1 = 6;
    /**
     * 海巡兽-防御基础参数
     */
    ParamKeyEnum_FML_DEF_2 = 7;
    /**
     * 海巡兽-穿透公式基础常数1
     */
    ParamKeyEnum_FML_PEN_C = 8;
    /**
     * 海巡兽-穿透公式基础常数2（万分比）
     */
    ParamKeyEnum_FML_PEN_K = 9;
    /**
     * 通用-掉落Actor路径
     */
    ParamKeyEnum_DROP_ACTOR_PATH = 10;
    /**
     * 伤害飘字灰字判定（怪物抗性≥该数值，则飘字为灰色）
     */
    ParamKeyEnum_DAMAGE_TEXT_RESIST = 11;
    /**
     * 玩家附属零能功能-蓝图组件路径
     */
    ParamKeyEnum_SPRIT_ENERGY_COM_PATH = 12;
    /**
     * 最大护盾值基于最大生命值的转化参数
     */
    ParamKeyEnum_MAXSHIELD_MULTIPLIER = 13;
)

