
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未拾取
     */
    PickupState_Unpicked = 0;
    /**
     * 已拾取
     */
    PickupState_Picked = 1;
)

