
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未定义
     */
    Quality_NONE = 0;
    /**
     * 白
     */
    Quality_WHITE = 1;
    /**
     * 绿
     */
    Quality_GREEN = 2;
    /**
     * 蓝
     */
    Quality_BLUE = 3;
    /**
     * 紫
     */
    Quality_PURPLE = 4;
    /**
     * 橙
     */
    Quality_ORANGE = 5;
    /**
     * 灰
     */
    Quality_GREAY = 6;
)

