
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type QuestGoalDesc struct {
    ExecType int32
    Type int32
    Config string
    Desc string
}

const TypeId_QuestGoalDesc = 281008934

func (*QuestGoalDesc) GetTypeId() int32 {
    return 281008934
}

func NewQuestGoalDesc(_buf map[string]interface{}) (_v *QuestGoalDesc, err error) {
    _v = &QuestGoalDesc{}
    { var _ok_ bool; var __json_ExecType__ interface{}; if __json_ExecType__, _ok_ = _buf["ExecType"]; !_ok_ || __json_ExecType__ == nil { err = errors.New("ExecType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ExecType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExecType = __x__ }}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_Config__ interface{}; if __json_Config__, _ok_ = _buf["Config"]; !_ok_ || __json_Config__ == nil { err = errors.New("Config error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_Config__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Config = __x__ }}
    { var _ok_ bool; var __json_Desc__ interface{}; if __json_Desc__, _ok_ = _buf["Desc"]; !_ok_ || __json_Desc__ == nil { err = errors.New("Desc error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_Desc__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc = __x__ }}
    return
}

