
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 任务开始
     */
    QuestAnnounceType_QUEST_BEGIN = 0;
    /**
     * 任务结束
     */
    QuestAnnounceType_QUEST_FINISH = 1;
)

