
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type QuestTbChapter struct {
    _dataMap map[int64]*QuestChapterCnf
    _dataList []*QuestChapterCnf
}

func NewQuestTbChapter(_buf []map[string]interface{}) (*QuestTbChapter, error) {
    _dataList := make([]*QuestChapterCnf, 0, len(_buf))
    dataMap := make(map[int64]*QuestChapterCnf)

    for _, _ele_ := range _buf {
        if _v, err2 := NewQuestChapterCnf(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &QuestTbChapter{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *QuestTbChapter) GetDataMap() map[int64]*QuestChapterCnf {
    return table._dataMap
}

func (table *QuestTbChapter) GetDataList() []*QuestChapterCnf {
    return table._dataList
}

func (table *QuestTbChapter) Get(key int64) *QuestChapterCnf {
    return table._dataMap[key]
}


