
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type QuestQuestStepCnf struct {
    QuestId int64
    Id int64
    IsFlowStep bool
    BPreCheck bool
    Tag string
    PrevStepIds []int64
    Order int32
    AcceptMode []*QuestAcceptMode
    Version int64
    SceneId int32
    BoShow bool
    Hidden bool
    FinishParent bool
    FailParent bool
    IsRewind bool
    IsClientExec bool
    BeginExec []*QuestExec
    FinishCondComb int32
    FinishCond []*QuestContent
    ProgressFinishExec []*QuestExec
    FinishExec []*QuestExec
    FailCondComb int32
    FailCond []*QuestContent
    FailExec []*QuestExec
    UnitRootId int64
    IsRollBackNode bool
    ResetLandmarkId int64
}

const TypeId_QuestQuestStepCnf = -1375436455

func (*QuestQuestStepCnf) GetTypeId() int32 {
    return -1375436455
}

func NewQuestQuestStepCnf(_buf map[string]interface{}) (_v *QuestQuestStepCnf, err error) {
    _v = &QuestQuestStepCnf{}
    { var _ok_ bool; var __json_QuestId__ interface{}; if __json_QuestId__, _ok_ = _buf["QuestId"]; !_ok_ || __json_QuestId__ == nil { err = errors.New("QuestId error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_QuestId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.QuestId = __x__ }}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_IsFlowStep__ interface{}; if __json_IsFlowStep__, _ok_ = _buf["IsFlowStep"]; !_ok_ || __json_IsFlowStep__ == nil { err = errors.New("IsFlowStep error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_IsFlowStep__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsFlowStep = __x__ }}
    { var _ok_ bool; var __json_bPreCheck__ interface{}; if __json_bPreCheck__, _ok_ = _buf["bPreCheck"]; !_ok_ || __json_bPreCheck__ == nil { err = errors.New("bPreCheck error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_bPreCheck__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.BPreCheck = __x__ }}
    { var _ok_ bool; var __json_Tag__ interface{}; if __json_Tag__, _ok_ = _buf["Tag"]; !_ok_ || __json_Tag__ == nil { err = errors.New("Tag error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_Tag__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Tag = __x__ }}
    { var _ok_ bool; var __json_PrevStepIds__ interface{}; if __json_PrevStepIds__, _ok_ = _buf["PrevStepIds"]; !_ok_ || __json_PrevStepIds__ == nil { err = errors.New("PrevStepIds error"); return } else { var __x__ []int64;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_PrevStepIds__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int64, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int64
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int64(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.PrevStepIds = __x__ }}
    { var _ok_ bool; var __json_Order__ interface{}; if __json_Order__, _ok_ = _buf["Order"]; !_ok_ || __json_Order__ == nil { err = errors.New("Order error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Order__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Order = __x__ }}
    { var _ok_ bool; var __json_AcceptMode__ interface{}; if __json_AcceptMode__, _ok_ = _buf["AcceptMode"]; !_ok_ || __json_AcceptMode__ == nil { err = errors.New("AcceptMode error"); return } else { var __x__ []*QuestAcceptMode;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AcceptMode__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestAcceptMode, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestAcceptMode
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestAcceptMode(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AcceptMode = __x__ }}
    { var _ok_ bool; var __json_Version__ interface{}; if __json_Version__, _ok_ = _buf["Version"]; !_ok_ || __json_Version__ == nil { err = errors.New("Version error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Version__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Version = __x__ }}
    { var _ok_ bool; var __json_SceneId__ interface{}; if __json_SceneId__, _ok_ = _buf["SceneId"]; !_ok_ || __json_SceneId__ == nil { err = errors.New("SceneId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SceneId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SceneId = __x__ }}
    { var _ok_ bool; var __json_BoShow__ interface{}; if __json_BoShow__, _ok_ = _buf["BoShow"]; !_ok_ || __json_BoShow__ == nil { err = errors.New("BoShow error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_BoShow__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.BoShow = __x__ }}
    { var _ok_ bool; var __json_Hidden__ interface{}; if __json_Hidden__, _ok_ = _buf["Hidden"]; !_ok_ || __json_Hidden__ == nil { err = errors.New("Hidden error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_Hidden__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Hidden = __x__ }}
    { var _ok_ bool; var __json_FinishParent__ interface{}; if __json_FinishParent__, _ok_ = _buf["FinishParent"]; !_ok_ || __json_FinishParent__ == nil { err = errors.New("FinishParent error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_FinishParent__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.FinishParent = __x__ }}
    { var _ok_ bool; var __json_FailParent__ interface{}; if __json_FailParent__, _ok_ = _buf["FailParent"]; !_ok_ || __json_FailParent__ == nil { err = errors.New("FailParent error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_FailParent__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.FailParent = __x__ }}
    { var _ok_ bool; var __json_IsRewind__ interface{}; if __json_IsRewind__, _ok_ = _buf["IsRewind"]; !_ok_ || __json_IsRewind__ == nil { err = errors.New("IsRewind error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_IsRewind__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsRewind = __x__ }}
    { var _ok_ bool; var __json_IsClientExec__ interface{}; if __json_IsClientExec__, _ok_ = _buf["IsClientExec"]; !_ok_ || __json_IsClientExec__ == nil { err = errors.New("IsClientExec error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_IsClientExec__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsClientExec = __x__ }}
    { var _ok_ bool; var __json_BeginExec__ interface{}; if __json_BeginExec__, _ok_ = _buf["BeginExec"]; !_ok_ || __json_BeginExec__ == nil { err = errors.New("BeginExec error"); return } else { var __x__ []*QuestExec;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_BeginExec__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestExec, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestExec
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestExec(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.BeginExec = __x__ }}
    { var _ok_ bool; var __json_FinishCondComb__ interface{}; if __json_FinishCondComb__, _ok_ = _buf["FinishCondComb"]; !_ok_ || __json_FinishCondComb__ == nil { err = errors.New("FinishCondComb error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_FinishCondComb__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.FinishCondComb = __x__ }}
    { var _ok_ bool; var __json_FinishCond__ interface{}; if __json_FinishCond__, _ok_ = _buf["FinishCond"]; !_ok_ || __json_FinishCond__ == nil { err = errors.New("FinishCond error"); return } else { var __x__ []*QuestContent;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_FinishCond__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestContent, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestContent
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestContent(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.FinishCond = __x__ }}
    { var _ok_ bool; var __json_ProgressFinishExec__ interface{}; if __json_ProgressFinishExec__, _ok_ = _buf["ProgressFinishExec"]; !_ok_ || __json_ProgressFinishExec__ == nil { err = errors.New("ProgressFinishExec error"); return } else { var __x__ []*QuestExec;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ProgressFinishExec__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestExec, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestExec
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestExec(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ProgressFinishExec = __x__ }}
    { var _ok_ bool; var __json_FinishExec__ interface{}; if __json_FinishExec__, _ok_ = _buf["FinishExec"]; !_ok_ || __json_FinishExec__ == nil { err = errors.New("FinishExec error"); return } else { var __x__ []*QuestExec;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_FinishExec__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestExec, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestExec
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestExec(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.FinishExec = __x__ }}
    { var _ok_ bool; var __json_FailCondComb__ interface{}; if __json_FailCondComb__, _ok_ = _buf["FailCondComb"]; !_ok_ || __json_FailCondComb__ == nil { err = errors.New("FailCondComb error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_FailCondComb__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.FailCondComb = __x__ }}
    { var _ok_ bool; var __json_FailCond__ interface{}; if __json_FailCond__, _ok_ = _buf["FailCond"]; !_ok_ || __json_FailCond__ == nil { err = errors.New("FailCond error"); return } else { var __x__ []*QuestContent;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_FailCond__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestContent, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestContent
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestContent(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.FailCond = __x__ }}
    { var _ok_ bool; var __json_FailExec__ interface{}; if __json_FailExec__, _ok_ = _buf["FailExec"]; !_ok_ || __json_FailExec__ == nil { err = errors.New("FailExec error"); return } else { var __x__ []*QuestExec;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_FailExec__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestExec, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestExec
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestExec(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.FailExec = __x__ }}
    { var _ok_ bool; var __json_UnitRootId__ interface{}; if __json_UnitRootId__, _ok_ = _buf["UnitRootId"]; !_ok_ || __json_UnitRootId__ == nil { err = errors.New("UnitRootId error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UnitRootId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.UnitRootId = __x__ }}
    { var _ok_ bool; var __json_IsRollBackNode__ interface{}; if __json_IsRollBackNode__, _ok_ = _buf["IsRollBackNode"]; !_ok_ || __json_IsRollBackNode__ == nil { err = errors.New("IsRollBackNode error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_IsRollBackNode__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsRollBackNode = __x__ }}
    { var _ok_ bool; var __json_ResetLandmarkId__ interface{}; if __json_ResetLandmarkId__, _ok_ = _buf["ResetLandmarkId"]; !_ok_ || __json_ResetLandmarkId__ == nil { err = errors.New("ResetLandmarkId error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ResetLandmarkId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.ResetLandmarkId = __x__ }}
    return
}

