
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 空
     */
    QuestContentType_DEFAULT = 0;
    /**
     * entityId(typeId), count
     */
    QuestContentType_KILL_MONSTER = 1;
    /**
     * monsterguid, entityId, 
     */
    QuestContentType_KILL_TARGET = 2;
    /**
     * itemId , count
     */
    QuestContentType_OBTAIN_ITEM = 3;
    /**
     * volumeguid
     */
    QuestContentType_ARRIVE_POS = 4;
    /**
     * sceneId
     */
    QuestContentType_ENTER_SCENE = 5;
    /**
     * guid
     */
    QuestContentType_INTERACT_ACTOR = 6;
    /**
     * 完成带领玩法
     */
    QuestContentType_OPEN_LEADING_MODE = 7;
    /**
     * 完成跟随玩法
     */
    QuestContentType_OPEN_FOLLOW_MODE = 8;
    /**
     * 达成物件状态
     */
    QuestContentType_CHECK_ACTOR_STATE = 9;
    /**
     * 任务状态等于
     */
    QuestContentType_STATE_EQUAL = 10;
    /**
     * 任务状态不等于
     */
    QuestContentType_STATE_NOT_EQUAL = 11;
    /**
     * 未定义
     */
    QuestContentType_CHECK_INVENTORY_ITEM = 12;
    /**
     * 阅读完引导界面
     */
    QuestContentType_READING_GUIDE_DIALOG = 13;
    /**
     * preassignedID，treeeNodeID
     */
    QuestContentType_DIALOGUE_NODE_FINISHED = 14;
    /**
     * preassignedID，String Tag
     */
    QuestContentType_DIALOGUE_TAG_ADDED = 15;
    /**
     * configid, count
     */
    QuestContentType_INTERACT_CONFIG_ID = 16;
    /**
     * level
     */
    QuestContentType_ROLE_LEVEL_UP = 17;
    /**
     * preassignedID, [String1- AVG资产软引用路劲，String2- 本地化Key]
     */
    QuestContentType_WAIT_AVG_FINISHED = 18;
    /**
     * questId
     */
    QuestContentType_QUEST_FINISHED = 19;
    /**
     * eventId
     */
    QuestContentType_LISTEN_EVENT = 20;
    /**
     * 任务值条件判断
     */
    QuestContentType_QUEST_WAIT_QUESTVAR = 21;
    /**
     * 等待GameFlow结束
     */
    QuestContentType_WAIT_GAME_FLOW_FINISHED = 22;
)

