
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 禁用音频
     */
    QuestAudioStateSwitch_DISABLE_AUDIO = 0;
    /**
     * 启用音频
     */
    QuestAudioStateSwitch_ENABLE_AUDIO = 1;
)

