
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    QuestProcessMode_NONE = 0;
    /**
     * 累加
     */
    QuestProcessMode_ADD = 1;
    /**
     * 设置
     */
    QuestProcessMode_SET = 2;
)

