
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 关闭导航显示
     */
    QuestTargetShowSwitch_CLOSE = 0;
    /**
     * 开启导航显示
     */
    QuestTargetShowSwitch_OPEN = 1;
)

