
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 倒计时开始(继续）
     */
    QuestCountDownType_BEGIN_OR_CONTINUE = 0;
    /**
     * 倒计时暂停
     */
    QuestCountDownType_PAUSE = 1;
)

