
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 空
     */
    QuestLockType_DEFAULT = 0;
    /**
     * level
     */
    QuestLockType_ROLE_LEVEL_UP = 1;
    /**
     * questId
     */
    QuestLockType_QUEST_FINISHED = 2;
    /**
     * questId
     */
    QuestLockType_QUEST_FINISHED_STEP = 3;
)

