
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 自动完成
     */
    QuestFinishMethod_NONE = 0;
    /**
     * 手动完成
     */
    QuestFinishMethod_MANUAL = 1;
)

