
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type QuestQuestCnf struct {
    Id int64
    IsDisable bool
    Type int32
    SceneId int32
    AcceptCondComb int32
    AcceptCond []*QuestAcceptCondition
    UnlockCondComb int32
    UnlockCond []*QuestLock
    FinishMethod int32
    Cancelable bool
    Repeatable bool
    GameFlowLoop bool
    MinRewindQuest int64
    ChildQuestMap map[int64]*QuestQuestStepCnf
    ChildQuestList []*QuestQuestStepCnf
    RewardIdList int32
    ChapterId int32
}

const TypeId_QuestQuestCnf = -1266038587

func (*QuestQuestCnf) GetTypeId() int32 {
    return -1266038587
}

func NewQuestQuestCnf(_buf map[string]interface{}) (_v *QuestQuestCnf, err error) {
    _v = &QuestQuestCnf{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_isDisable__ interface{}; if __json_isDisable__, _ok_ = _buf["isDisable"]; !_ok_ || __json_isDisable__ == nil { err = errors.New("isDisable error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_isDisable__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsDisable = __x__ }}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_SceneId__ interface{}; if __json_SceneId__, _ok_ = _buf["SceneId"]; !_ok_ || __json_SceneId__ == nil { err = errors.New("SceneId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SceneId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SceneId = __x__ }}
    { var _ok_ bool; var __json_AcceptCondComb__ interface{}; if __json_AcceptCondComb__, _ok_ = _buf["AcceptCondComb"]; !_ok_ || __json_AcceptCondComb__ == nil { err = errors.New("AcceptCondComb error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_AcceptCondComb__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AcceptCondComb = __x__ }}
    { var _ok_ bool; var __json_AcceptCond__ interface{}; if __json_AcceptCond__, _ok_ = _buf["AcceptCond"]; !_ok_ || __json_AcceptCond__ == nil { err = errors.New("AcceptCond error"); return } else { var __x__ []*QuestAcceptCondition;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AcceptCond__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestAcceptCondition, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestAcceptCondition
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestAcceptCondition(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AcceptCond = __x__ }}
    { var _ok_ bool; var __json_UnlockCondComb__ interface{}; if __json_UnlockCondComb__, _ok_ = _buf["UnlockCondComb"]; !_ok_ || __json_UnlockCondComb__ == nil { err = errors.New("UnlockCondComb error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UnlockCondComb__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockCondComb = __x__ }}
    { var _ok_ bool; var __json_UnlockCond__ interface{}; if __json_UnlockCond__, _ok_ = _buf["UnlockCond"]; !_ok_ || __json_UnlockCond__ == nil { err = errors.New("UnlockCond error"); return } else { var __x__ []*QuestLock;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_UnlockCond__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestLock, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestLock
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestLock(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.UnlockCond = __x__ }}
    { var _ok_ bool; var __json_FinishMethod__ interface{}; if __json_FinishMethod__, _ok_ = _buf["FinishMethod"]; !_ok_ || __json_FinishMethod__ == nil { err = errors.New("FinishMethod error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_FinishMethod__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.FinishMethod = __x__ }}
    { var _ok_ bool; var __json_Cancelable__ interface{}; if __json_Cancelable__, _ok_ = _buf["Cancelable"]; !_ok_ || __json_Cancelable__ == nil { err = errors.New("Cancelable error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_Cancelable__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Cancelable = __x__ }}
    { var _ok_ bool; var __json_Repeatable__ interface{}; if __json_Repeatable__, _ok_ = _buf["Repeatable"]; !_ok_ || __json_Repeatable__ == nil { err = errors.New("Repeatable error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_Repeatable__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Repeatable = __x__ }}
    { var _ok_ bool; var __json_GameFlowLoop__ interface{}; if __json_GameFlowLoop__, _ok_ = _buf["GameFlowLoop"]; !_ok_ || __json_GameFlowLoop__ == nil { err = errors.New("GameFlowLoop error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_GameFlowLoop__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.GameFlowLoop = __x__ }}
    { var _ok_ bool; var __json_MinRewindQuest__ interface{}; if __json_MinRewindQuest__, _ok_ = _buf["MinRewindQuest"]; !_ok_ || __json_MinRewindQuest__ == nil { err = errors.New("MinRewindQuest error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_MinRewindQuest__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.MinRewindQuest = __x__ }}
    { var _ok_ bool; var __json_ChildQuestMap__ interface{}; if __json_ChildQuestMap__, _ok_ = _buf["ChildQuestMap"]; !_ok_ || __json_ChildQuestMap__ == nil { err = errors.New("ChildQuestMap error"); return } else { var __x__ map[int64]*QuestQuestStepCnf;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok_ = (__json_ChildQuestMap__).([]interface{}); !_ok_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make(map[int64]*QuestQuestStepCnf)
                    
                    for _, _e0_ := range _arr0_ {
                        var _kv0_ []interface{}
                        if _kv0_, _ok0_ = _e0_.([]interface{}); !_ok0_ || len(_kv0_) != 2 { err = errors.New("__x__ error"); return }
                        var _key0_ int64
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _kv0_[0].(float64); !_ok_ { err = errors.New("_key0_ error"); return }; _key0_ = int64(_x_) }
                        var _value0_ *QuestQuestStepCnf
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _kv0_[1].(map[string]interface{}); !_ok_ { err = errors.New("_value0_ error"); return }; if _value0_, err = NewQuestQuestStepCnf(_x_); err != nil { return } }
                        __x__[_key0_] = _value0_
                    }
                    }; _v.ChildQuestMap = __x__ }}
    { var _ok_ bool; var __json_ChildQuestList__ interface{}; if __json_ChildQuestList__, _ok_ = _buf["ChildQuestList"]; !_ok_ || __json_ChildQuestList__ == nil { err = errors.New("ChildQuestList error"); return } else { var __x__ []*QuestQuestStepCnf;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ChildQuestList__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*QuestQuestStepCnf, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *QuestQuestStepCnf
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewQuestQuestStepCnf(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ChildQuestList = __x__ }}
    { var _ok_ bool; var __json_RewardIdList__ interface{}; if __json_RewardIdList__, _ok_ = _buf["RewardIdList"]; !_ok_ || __json_RewardIdList__ == nil { err = errors.New("RewardIdList error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RewardIdList__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RewardIdList = __x__ }}
    { var _ok_ bool; var __json_ChapterId__ interface{}; if __json_ChapterId__, _ok_ = _buf["ChapterId"]; !_ok_ || __json_ChapterId__ == nil { err = errors.New("ChapterId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ChapterId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ChapterId = __x__ }}
    return
}

