
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 主线
     */
    QuestType_MAINLINE = 0;
    /**
     * 支线
     */
    QuestType_SIDE = 1;
    /**
     * 日常
     */
    QuestType_DAILY = 2;
    /**
     * 深渊玩法
     */
    QuestType_Maze = 3;
    /**
     * 隐藏
     */
    QuestType_Hide = 4;
    /**
     * 挑战类任务
     */
    QuestType_Challenge = 5;
    /**
     * Game_Flow
     */
    QuestType_GameFlow = 6;
    /**
     * 多人关卡
     */
    QuestType_MMOLevelFlow = 9;
    /**
     * 资源关卡
     */
    QuestType_ResourceLevel = 10;
    /**
     * 随机岛礁关卡
     */
    QuestType_Randomisland = 11;
    /**
     * 教学关卡
     */
    QuestType_TeachingLevel = 12;
    /**
     * 世界等级突破
     */
    QuestType_WorldLevelExceed = 13;
    /**
     * 突破副本
     */
    QuestType_ExceedLevel = 14;
    /**
     * 活动任务
     */
    QuestType_Activity = 15;
    /**
     * Boss关卡
     */
    QuestType_BossLevel = 16;
    /**
     * Boss挑战关卡
     */
    QuestType_BossChallengeLevel = 17;
)

