
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 空
     */
    QuestAcceptConditionType_DEFAULT = 0;
    /**
     * level
     */
    QuestAcceptConditionType_ROLE_LEVEL_UP = 1;
    /**
     * questId
     */
    QuestAcceptConditionType_QUEST_FINISHED = 2;
    /**
     * preassignedID，String Tag
     */
    QuestAcceptConditionType_DIALOGUE_TAG_ADDED = 3;
    /**
     * preassignedID, [String1- AVG资产软引用路劲，String2- 本地化Key]
     */
    QuestAcceptConditionType_WAIT_AVG_FINISHED = 4;
    /**
     * entityId(typeId), count
     */
    QuestAcceptConditionType_KILL_MONSTER = 5;
    /**
     * itemId , count
     */
    QuestAcceptConditionType_OBTAIN_ITEM = 6;
    /**
     * guid
     */
    QuestAcceptConditionType_INTERACT_ACTOR = 7;
    /**
     * configid, count
     */
    QuestAcceptConditionType_INTERACT_CONFIG_ID = 8;
    /**
     * 加载某个LevelInstance
     */
    QuestAcceptConditionType_LOAD_LEVEL_INSTANCE = 9;
    /**
     * avatarId,level
     */
    QuestAcceptConditionType_FAVORABILITY_LEVEL = 10;
)

