
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type QuestQuestGlobalVar struct {
    Id int32
    DefaultValue int32
}

const TypeId_QuestQuestGlobalVar = 124458094

func (*QuestQuestGlobalVar) GetTypeId() int32 {
    return 124458094
}

func NewQuestQuestGlobalVar(_buf map[string]interface{}) (_v *QuestQuestGlobalVar, err error) {
    _v = &QuestQuestGlobalVar{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_DefaultValue__ interface{}; if __json_DefaultValue__, _ok_ = _buf["DefaultValue"]; !_ok_ || __json_DefaultValue__ == nil { err = errors.New("DefaultValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_DefaultValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DefaultValue = __x__ }}
    return
}

