
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 自动接取任务
     */
    QuestAcceptModeType_EAutoAccept = 0;
    /**
     * Quest Volume接取任务
     */
    QuestAcceptModeType_EVolumeAccept = 1;
    /**
     * 对话节点接取
     */
    QuestAcceptModeType_DialogueNodeAccept = 2;
    /**
     * AVG结束后接取
     */
    QuestAcceptModeType_WaitAvgFinished = 3;
)

