//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type QuestTbQuest struct {
	_dataMap  map[int64]*QuestQuestCnf
	_dataList []*QuestQuestCnf
}

func NewQuestTbQuest(_buf []map[string]interface{}) (*QuestTbQuest, error) {
	_dataList := make([]*QuestQuestCnf, 0, len(_buf))
	dataMap := make(map[int64]*QuestQuestCnf)

	for _, _ele_ := range _buf {
		if _v, err2 := NewQuestQuestCnf(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &QuestTbQuest{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *QuestTbQuest) GetDataMap() map[int64]*QuestQuestCnf {
	return table._dataMap
}

func (table *QuestTbQuest) GetDataList() []*QuestQuestCnf {
	return table._dataList
}

func (table *QuestTbQuest) Get(key int64) (*QuestQuestCnf, *QuestQuestCnf) {
	return table._dataMap[key], nil
}
