
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type QuestChapterCnf struct {
    Id int64
    Hidden bool
    BeginQuestId int32
    EndQuestId int32
}

const TypeId_QuestChapterCnf = -1721373062

func (*QuestChapterCnf) GetTypeId() int32 {
    return -1721373062
}

func NewQuestChapterCnf(_buf map[string]interface{}) (_v *QuestChapterCnf, err error) {
    _v = &QuestChapterCnf{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Hidden__ interface{}; if __json_Hidden__, _ok_ = _buf["Hidden"]; !_ok_ || __json_Hidden__ == nil { err = errors.New("Hidden error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_Hidden__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Hidden = __x__ }}
    { var _ok_ bool; var __json_BeginQuestId__ interface{}; if __json_BeginQuestId__, _ok_ = _buf["BeginQuestId"]; !_ok_ || __json_BeginQuestId__ == nil { err = errors.New("BeginQuestId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_BeginQuestId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BeginQuestId = __x__ }}
    { var _ok_ bool; var __json_EndQuestId__ interface{}; if __json_EndQuestId__, _ok_ = _buf["EndQuestId"]; !_ok_ || __json_EndQuestId__ == nil { err = errors.New("EndQuestId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_EndQuestId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.EndQuestId = __x__ }}
    return
}

