
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 已经领取
     */
    QuestState_NONE = 0;
    /**
     * 已经完成
     */
    QuestState_FINISHED = 1;
    /**
     * 已经失败
     */
    QuestState_FAILED = 2;
    /**
     * 已经被终止
     */
    QuestState_CANCELED = 3;
    /**
     * 锁定任务
     */
    QuestState_LOCKED = 4;
    /**
     * 可领取
     */
    QuestState_CAN_RECEIVE = 5;
)

