
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    QuestFailedReason_NONE = 0;
    /**
     * 玩家死亡
     */
    QuestFailedReason_PLAYER_DEAD = 1;
    /**
     * 进入场景
     */
    QuestFailedReason_ENTER_SCENE = 2;
    /**
     * 卡死重置
     */
    QuestFailedReason_STUCK_RESET = 3;
)

