
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type QuestCondition struct {
}

const TypeId_QuestCondition = 1514413689

func (*QuestCondition) GetTypeId() int32 {
    return 1514413689
}

func NewQuestCondition(_buf map[string]interface{}) (interface{}, error) {
    var id string
    var _ok_ bool
    if id, _ok_ = _buf["$type"].(string) ; !_ok_ {
        return nil, errors.New("type id missing")
    }
    switch id {
        case "QuestAcceptMode": _v, err := NewQuestAcceptMode(_buf); if err != nil { return nil, errors.New("questacceptmode") } else { return _v, nil }
        case "QuestAcceptCondition": _v, err := NewQuestAcceptCondition(_buf); if err != nil { return nil, errors.New("questacceptcondition") } else { return _v, nil }
        case "QuestLock": _v, err := NewQuestLock(_buf); if err != nil { return nil, errors.New("questlock") } else { return _v, nil }
        default: return nil, errors.New("unknown type id")
    }
}


