
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type QuestAcceptCondition struct {
    Type int32
    Param []int64
    StringParam []string
}

const TypeId_QuestAcceptCondition = -776555567

func (*QuestAcceptCondition) GetTypeId() int32 {
    return -776555567
}

func NewQuestAcceptCondition(_buf map[string]interface{}) (_v *QuestAcceptCondition, err error) {
    _v = &QuestAcceptCondition{}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_Param__ interface{}; if __json_Param__, _ok_ = _buf["Param"]; !_ok_ || __json_Param__ == nil { err = errors.New("Param error"); return } else { var __x__ []int64;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Param__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int64, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int64
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int64(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Param = __x__ }}
    { var _ok_ bool; var __json_StringParam__ interface{}; if __json_StringParam__, _ok_ = _buf["StringParam"]; !_ok_ || __json_StringParam__ == nil { err = errors.New("StringParam error"); return } else { var __x__ []string;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_StringParam__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]string, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ string
                        {  if _list_v0_, _ok_ = _e0_.(string); !_ok_ { err = errors.New("_list_v0_ error"); return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.StringParam = __x__ }}
    return
}

