
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 随机岛礁状态
 */
const (
    /**
     * 未激活
     */
    RandomIslandState_NotActivated = 0;
    /**
     * 已激活
     */
    RandomIslandState_Activated = 1;
    /**
     * 可见态
     */
    RandomIslandState_Visible = 2;
)

