
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 重生区域状态
 */
const (
    /**
     * 未激活
     */
    RespawnVolumeState_NotActivated = 0;
    /**
     * 已激活
     */
    RespawnVolumeState_Activated = 1;
)

