
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SceneArea struct {
    Id int32
    AreaId int32
    LvlId int32
}

const TypeId_SceneArea = 2033835215

func (*SceneArea) GetTypeId() int32 {
    return 2033835215
}

func NewSceneArea(_buf map[string]interface{}) (_v *SceneArea, err error) {
    _v = &SceneArea{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_AreaId__ interface{}; if __json_AreaId__, _ok_ = _buf["AreaId"]; !_ok_ || __json_AreaId__ == nil { err = errors.New("AreaId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_AreaId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AreaId = __x__ }}
    { var _ok_ bool; var __json_LvlId__ interface{}; if __json_LvlId__, _ok_ = _buf["LvlId"]; !_ok_ || __json_LvlId__ == nil { err = errors.New("LvlId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LvlId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LvlId = __x__ }}
    return
}

