
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景内玩家操作定义,支持到28种操作类型
 */
const (
    /**
     * 不能做任何操作
     */
    SceneOptionType_NONE = 0;
    /**
     * 重生
     */
    SceneOptionType_REBORN = 1;
    /**
     * 移动
     */
    SceneOptionType_MOVE = 2;
    /**
     * 使用道具
     */
    SceneOptionType_USE_ITEM = 4;
    /**
     * 允许所有操作
     */
    SceneOptionType_ALL = 268435455;
)

