
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SceneTbScene struct {
    _dataMap map[int32]*SceneScene
    _dataList []*SceneScene
}

func NewSceneTbScene(_buf []map[string]interface{}) (*SceneTbScene, error) {
    _dataList := make([]*SceneScene, 0, len(_buf))
    dataMap := make(map[int32]*SceneScene)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSceneScene(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SceneTbScene{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SceneTbScene) GetDataMap() map[int32]*SceneScene {
    return table._dataMap
}

func (table *SceneTbScene) GetDataList() []*SceneScene {
    return table._dataList
}

func (table *SceneTbScene) Get(key int32) *SceneScene {
    return table._dataMap[key]
}


