
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SceneSceneObject struct {
    Id int64
    DropGroupId int32
}

const TypeId_SceneSceneObject = -1078258583

func (*SceneSceneObject) GetTypeId() int32 {
    return -1078258583
}

func NewSceneSceneObject(_buf map[string]interface{}) (_v *SceneSceneObject, err error) {
    _v = &SceneSceneObject{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_DropGroupId__ interface{}; if __json_DropGroupId__, _ok_ = _buf["DropGroupId"]; !_ok_ || __json_DropGroupId__ == nil { err = errors.New("DropGroupId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_DropGroupId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DropGroupId = __x__ }}
    return
}

