
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景的Loading类型
 */
const (
    /**
     * 默认loading
     */
    SceneLoadingType_ELoading_Default = 0;
    /**
     * 深渊场景内loading
     */
    SceneLoadingType_ELoading_Maze = 1;
    /**
     * 深渊场景换队伍
     */
    SceneLoadingType_ELoading_Maze_Change_Team = 2;
)

