
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景主控的角色类型
 */
const (
    /**
     * 人形主控
     */
    ScenePlayerMode_HUMAN = 0;
    /**
     * 海巡兽主控
     */
    ScenePlayerMode_SAND_BOAT = 1;
    /**
     * 攻城仓主控
     */
    ScenePlayerMode_DROP_POD = 2;
)

