
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * Hero角色
     */
    SceneAvatarSubType_EAvatarType_Hero = 0;
    /**
     * 海巡兽
     */
    SceneAvatarSubType_EAvatarType_Ship = 1;
    /**
     * 攻城仓
     */
    SceneAvatarSubType_EAvatarType_DropPod = 2;
)

