
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SceneTbVisualObject struct {
    _dataMap map[int32]*SceneVisualObject
    _dataList []*SceneVisualObject
}

func NewSceneTbVisualObject(_buf []map[string]interface{}) (*SceneTbVisualObject, error) {
    _dataList := make([]*SceneVisualObject, 0, len(_buf))
    dataMap := make(map[int32]*SceneVisualObject)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSceneVisualObject(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Type] = _v
        }
    }
    return &SceneTbVisualObject{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SceneTbVisualObject) GetDataMap() map[int32]*SceneVisualObject {
    return table._dataMap
}

func (table *SceneTbVisualObject) GetDataList() []*SceneVisualObject {
    return table._dataList
}

func (table *SceneTbVisualObject) Get(key int32) *SceneVisualObject {
    return table._dataMap[key]
}


