
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SceneTbLevel struct {
    _dataMap map[int32]*SceneLevel
    _dataList []*SceneLevel
}

func NewSceneTbLevel(_buf []map[string]interface{}) (*SceneTbLevel, error) {
    _dataList := make([]*SceneLevel, 0, len(_buf))
    dataMap := make(map[int32]*SceneLevel)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSceneLevel(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SceneTbLevel{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SceneTbLevel) GetDataMap() map[int32]*SceneLevel {
    return table._dataMap
}

func (table *SceneTbLevel) GetDataList() []*SceneLevel {
    return table._dataList
}

func (table *SceneTbLevel) Get(key int32) *SceneLevel {
    return table._dataMap[key]
}


