
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SceneScene struct {
    Id int32
    UnlockId int32
    NotTeleport bool
    NotAutoRest bool
    Type int32
    VisionLevel int32
    PlayerMode int32
    SpawnPointTag string
    LevelSafeAreaLocation *Vector3
    BackgroundMusic string
}

const TypeId_SceneScene = -1359440758

func (*SceneScene) GetTypeId() int32 {
    return -1359440758
}

func NewSceneScene(_buf map[string]interface{}) (_v *SceneScene, err error) {
    _v = &SceneScene{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_unlockId__ interface{}; if __json_unlockId__, _ok_ = _buf["unlockId"]; !_ok_ || __json_unlockId__ == nil { err = errors.New("unlockId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_unlockId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockId = __x__ }}
    { var _ok_ bool; var __json_notTeleport__ interface{}; if __json_notTeleport__, _ok_ = _buf["notTeleport"]; !_ok_ || __json_notTeleport__ == nil { err = errors.New("notTeleport error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_notTeleport__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.NotTeleport = __x__ }}
    { var _ok_ bool; var __json_notAutoRest__ interface{}; if __json_notAutoRest__, _ok_ = _buf["notAutoRest"]; !_ok_ || __json_notAutoRest__ == nil { err = errors.New("notAutoRest error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_notAutoRest__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.NotAutoRest = __x__ }}
    { var _ok_ bool; var __json_type__ interface{}; if __json_type__, _ok_ = _buf["type"]; !_ok_ || __json_type__ == nil { err = errors.New("type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_VisionLevel__ interface{}; if __json_VisionLevel__, _ok_ = _buf["VisionLevel"]; !_ok_ || __json_VisionLevel__ == nil { err = errors.New("VisionLevel error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_VisionLevel__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.VisionLevel = __x__ }}
    { var _ok_ bool; var __json_PlayerMode__ interface{}; if __json_PlayerMode__, _ok_ = _buf["PlayerMode"]; !_ok_ || __json_PlayerMode__ == nil { err = errors.New("PlayerMode error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_PlayerMode__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.PlayerMode = __x__ }}
    { var _ok_ bool; var __json_SpawnPointTag__ interface{}; if __json_SpawnPointTag__, _ok_ = _buf["SpawnPointTag"]; !_ok_ || __json_SpawnPointTag__ == nil { err = errors.New("SpawnPointTag error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_SpawnPointTag__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SpawnPointTag = __x__ }}
    { var _ok_ bool; var __json_LevelSafeAreaLocation__ interface{}; if __json_LevelSafeAreaLocation__, _ok_ = _buf["LevelSafeAreaLocation"]; !_ok_ || __json_LevelSafeAreaLocation__ == nil { err = errors.New("LevelSafeAreaLocation error"); return } else { var __x__ *Vector3;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_LevelSafeAreaLocation__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewVector3(_x_); err != nil { return } }; _v.LevelSafeAreaLocation = __x__ }}
    { var _ok_ bool; var __json_Background_Music__ interface{}; if __json_Background_Music__, _ok_ = _buf["Background_Music"]; !_ok_ || __json_Background_Music__ == nil { err = errors.New("Background_Music error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_Background_Music__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.BackgroundMusic = __x__ }}
    return
}

