
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未定义
     */
    SceneType_NONE = 0;
    /**
     * 玩家的开放世界场景
     */
    SceneType_WORLD = 1;
    /**
     * 箱庭关卡
     */
    SceneType_LEVEL = 2;
    /**
     * 深渊副本房间场景
     */
    SceneType_MAZE_ROOM = 3;
    /**
     * 资源关卡
     */
    SceneType_RESOURCE = 4;
    /**
     * 随机岛礁
     */
    SceneType_RANDOM_ISLAND = 5;
    /**
     * 世界等级突破
     */
    SceneType_WORLD_LEVEL_EXCEED = 6;
    /**
     * 训练关卡
     */
    SceneType_TRAINING = 7;
    /**
     * 与狭间
     */
    SceneType_YU_XIA_JIAN = 8;
    /**
     * 家园
     */
    SceneType_HOME = 9;
    /**
     * boss关卡
     */
    SceneType_BOSS = 10;
    /**
     * 祈玉副本
     */
    SceneType_MARK = 11;
)

