
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SceneVisualObject struct {
    Type int32
    CanTeleport bool
    CanRecover bool
    CanReborn bool
}

const TypeId_SceneVisualObject = 1941000417

func (*SceneVisualObject) GetTypeId() int32 {
    return 1941000417
}

func NewSceneVisualObject(_buf map[string]interface{}) (_v *SceneVisualObject, err error) {
    _v = &SceneVisualObject{}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_CanTeleport__ interface{}; if __json_CanTeleport__, _ok_ = _buf["CanTeleport"]; !_ok_ || __json_CanTeleport__ == nil { err = errors.New("CanTeleport error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_CanTeleport__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanTeleport = __x__ }}
    { var _ok_ bool; var __json_CanRecover__ interface{}; if __json_CanRecover__, _ok_ = _buf["CanRecover"]; !_ok_ || __json_CanRecover__ == nil { err = errors.New("CanRecover error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_CanRecover__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanRecover = __x__ }}
    { var _ok_ bool; var __json_CanReborn__ interface{}; if __json_CanReborn__, _ok_ = _buf["CanReborn"]; !_ok_ || __json_CanReborn__ == nil { err = errors.New("CanReborn error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_CanReborn__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanReborn = __x__ }}
    return
}

