
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbSkillLevelValue struct {
    _dataMap map[int32]*SkilldataSkillLevelValue
    _dataList []*SkilldataSkillLevelValue
}

func NewSkilldataTbSkillLevelValue(_buf []map[string]interface{}) (*SkilldataTbSkillLevelValue, error) {
    _dataList := make([]*SkilldataSkillLevelValue, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataSkillLevelValue)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataSkillLevelValue(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbSkillLevelValue{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbSkillLevelValue) GetDataMap() map[int32]*SkilldataSkillLevelValue {
    return table._dataMap
}

func (table *SkilldataTbSkillLevelValue) GetDataList() []*SkilldataSkillLevelValue {
    return table._dataList
}

func (table *SkilldataTbSkillLevelValue) Get(key int32) *SkilldataSkillLevelValue {
    return table._dataMap[key]
}


