
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkilldataSkillLevelValue struct {
    ID int32
    GroupID int32
    SkillValue string
    SkillValueL10n string
}

const TypeId_SkilldataSkillLevelValue = -1195657493

func (*SkilldataSkillLevelValue) GetTypeId() int32 {
    return -1195657493
}

func NewSkilldataSkillLevelValue(_buf map[string]interface{}) (_v *SkilldataSkillLevelValue, err error) {
    _v = &SkilldataSkillLevelValue{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_GroupID__ interface{}; if __json_GroupID__, _ok_ = _buf["GroupID"]; !_ok_ || __json_GroupID__ == nil { err = errors.New("GroupID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_GroupID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GroupID = __x__ }}
    { var _ok_ bool; var __json_SkillValue__ interface{}; if __json_SkillValue__, _ok_ = _buf["SkillValue"]; !_ok_ || __json_SkillValue__ == nil { err = errors.New("SkillValue error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_SkillValue__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SkillValue = __x__ }}
    { var _ok_ bool; var __json_SkillValue_L10n__ interface{}; if __json_SkillValue_L10n__, _ok_ = _buf["SkillValue_L10n"]; !_ok_ || __json_SkillValue_L10n__ == nil { err = errors.New("SkillValue_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_SkillValue_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SkillValueL10n = __x__ }}
    return
}

