
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbHeroGA struct {
    _dataMap map[int32]*SkilldataHeroGA
    _dataList []*SkilldataHeroGA
}

func NewSkilldataTbHeroGA(_buf []map[string]interface{}) (*SkilldataTbHeroGA, error) {
    _dataList := make([]*SkilldataHeroGA, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataHeroGA)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataHeroGA(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbHeroGA{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbHeroGA) GetDataMap() map[int32]*SkilldataHeroGA {
    return table._dataMap
}

func (table *SkilldataTbHeroGA) GetDataList() []*SkilldataHeroGA {
    return table._dataList
}

func (table *SkilldataTbHeroGA) Get(key int32) *SkilldataHeroGA {
    return table._dataMap[key]
}


