
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbMontageCost struct {
    _dataMap map[int32]*SkilldataMontageCost
    _dataList []*SkilldataMontageCost
}

func NewSkilldataTbMontageCost(_buf []map[string]interface{}) (*SkilldataTbMontageCost, error) {
    _dataList := make([]*SkilldataMontageCost, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataMontageCost)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataMontageCost(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbMontageCost{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbMontageCost) GetDataMap() map[int32]*SkilldataMontageCost {
    return table._dataMap
}

func (table *SkilldataTbMontageCost) GetDataList() []*SkilldataMontageCost {
    return table._dataList
}

func (table *SkilldataTbMontageCost) Get(key int32) *SkilldataMontageCost {
    return table._dataMap[key]
}


