
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkilldataSkillLevelValueGroup struct {
    ID int32
}

const TypeId_SkilldataSkillLevelValueGroup = -1421415852

func (*SkilldataSkillLevelValueGroup) GetTypeId() int32 {
    return -1421415852
}

func NewSkilldataSkillLevelValueGroup(_buf map[string]interface{}) (_v *SkilldataSkillLevelValueGroup, err error) {
    _v = &SkilldataSkillLevelValueGroup{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    return
}

