
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbSkillLevel struct {
    _dataMap map[int32]*SkilldataSkillLevel
    _dataList []*SkilldataSkillLevel
}

func NewSkilldataTbSkillLevel(_buf []map[string]interface{}) (*SkilldataTbSkillLevel, error) {
    _dataList := make([]*SkilldataSkillLevel, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataSkillLevel)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataSkillLevel(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbSkillLevel{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbSkillLevel) GetDataMap() map[int32]*SkilldataSkillLevel {
    return table._dataMap
}

func (table *SkilldataTbSkillLevel) GetDataList() []*SkilldataSkillLevel {
    return table._dataList
}

func (table *SkilldataTbSkillLevel) Get(key int32) *SkilldataSkillLevel {
    return table._dataMap[key]
}


