
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkilldataSkillLevel struct {
    ID int32
    SkillID int32
    Level int32
    UpSkillProps []*SkillPropOpt
    PercentParameter []int32
    FixedParameter []int32
}

const TypeId_SkilldataSkillLevel = 403264038

func (*SkilldataSkillLevel) GetTypeId() int32 {
    return 403264038
}

func NewSkilldataSkillLevel(_buf map[string]interface{}) (_v *SkilldataSkillLevel, err error) {
    _v = &SkilldataSkillLevel{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_SkillID__ interface{}; if __json_SkillID__, _ok_ = _buf["SkillID"]; !_ok_ || __json_SkillID__ == nil { err = errors.New("SkillID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SkillID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SkillID = __x__ }}
    { var _ok_ bool; var __json_Level__ interface{}; if __json_Level__, _ok_ = _buf["Level"]; !_ok_ || __json_Level__ == nil { err = errors.New("Level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Level = __x__ }}
    { var _ok_ bool; var __json_UpSkillProps__ interface{}; if __json_UpSkillProps__, _ok_ = _buf["UpSkillProps"]; !_ok_ || __json_UpSkillProps__ == nil { err = errors.New("UpSkillProps error"); return } else { var __x__ []*SkillPropOpt;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_UpSkillProps__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*SkillPropOpt, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *SkillPropOpt
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewSkillPropOpt(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.UpSkillProps = __x__ }}
    { var _ok_ bool; var __json_PercentParameter__ interface{}; if __json_PercentParameter__, _ok_ = _buf["PercentParameter"]; !_ok_ || __json_PercentParameter__ == nil { err = errors.New("PercentParameter error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_PercentParameter__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.PercentParameter = __x__ }}
    { var _ok_ bool; var __json_FixedParameter__ interface{}; if __json_FixedParameter__, _ok_ = _buf["FixedParameter"]; !_ok_ || __json_FixedParameter__ == nil { err = errors.New("FixedParameter error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_FixedParameter__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.FixedParameter = __x__ }}
    return
}

