
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbComboMontage struct {
    _dataMap map[int32]*SkilldataComboMontage
    _dataList []*SkilldataComboMontage
}

func NewSkilldataTbComboMontage(_buf []map[string]interface{}) (*SkilldataTbComboMontage, error) {
    _dataList := make([]*SkilldataComboMontage, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataComboMontage)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataComboMontage(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbComboMontage{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbComboMontage) GetDataMap() map[int32]*SkilldataComboMontage {
    return table._dataMap
}

func (table *SkilldataTbComboMontage) GetDataList() []*SkilldataComboMontage {
    return table._dataList
}

func (table *SkilldataTbComboMontage) Get(key int32) *SkilldataComboMontage {
    return table._dataMap[key]
}


