
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbSkillLevelValueGroup struct {
    _dataMap map[int32]*SkilldataSkillLevelValueGroup
    _dataList []*SkilldataSkillLevelValueGroup
}

func NewSkilldataTbSkillLevelValueGroup(_buf []map[string]interface{}) (*SkilldataTbSkillLevelValueGroup, error) {
    _dataList := make([]*SkilldataSkillLevelValueGroup, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataSkillLevelValueGroup)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataSkillLevelValueGroup(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbSkillLevelValueGroup{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbSkillLevelValueGroup) GetDataMap() map[int32]*SkilldataSkillLevelValueGroup {
    return table._dataMap
}

func (table *SkilldataTbSkillLevelValueGroup) GetDataList() []*SkilldataSkillLevelValueGroup {
    return table._dataList
}

func (table *SkilldataTbSkillLevelValueGroup) Get(key int32) *SkilldataSkillLevelValueGroup {
    return table._dataMap[key]
}


