
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkilldataSkill struct {
    ID int32
    HeroCnfId int32
    SkillType int32
    Combos []int32
    MontageActions []int32
    LevelLimit int32
}

const TypeId_SkilldataSkill = -1282103298

func (*SkilldataSkill) GetTypeId() int32 {
    return -1282103298
}

func NewSkilldataSkill(_buf map[string]interface{}) (_v *SkilldataSkill, err error) {
    _v = &SkilldataSkill{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_HeroCnfId__ interface{}; if __json_HeroCnfId__, _ok_ = _buf["HeroCnfId"]; !_ok_ || __json_HeroCnfId__ == nil { err = errors.New("HeroCnfId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_HeroCnfId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HeroCnfId = __x__ }}
    { var _ok_ bool; var __json_SkillType__ interface{}; if __json_SkillType__, _ok_ = _buf["SkillType"]; !_ok_ || __json_SkillType__ == nil { err = errors.New("SkillType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SkillType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SkillType = __x__ }}
    { var _ok_ bool; var __json_Combos__ interface{}; if __json_Combos__, _ok_ = _buf["Combos"]; !_ok_ || __json_Combos__ == nil { err = errors.New("Combos error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Combos__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Combos = __x__ }}
    { var _ok_ bool; var __json_MontageActions__ interface{}; if __json_MontageActions__, _ok_ = _buf["MontageActions"]; !_ok_ || __json_MontageActions__ == nil { err = errors.New("MontageActions error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_MontageActions__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.MontageActions = __x__ }}
    { var _ok_ bool; var __json_LevelLimit__ interface{}; if __json_LevelLimit__, _ok_ = _buf["LevelLimit"]; !_ok_ || __json_LevelLimit__ == nil { err = errors.New("LevelLimit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LevelLimit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LevelLimit = __x__ }}
    return
}

