
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkilldataMontageCost struct {
    ID int32
    Formulation int32
    StaminaCostValue int32
    StaminaCostRatioType int32
    StaminaCostRatio int32
    HpCostValue int32
    HpCostRatioType int32
    HpCostRatio int32
    ExSkillEnergyCostValue int32
    ExSkillEnergyCostRatioType int32
    ExSkillEnergyCostRatio int32
    SPCostValue int32
    SPCostRatioType int32
    SPCostRatio int32
    SP1CostValue int32
    SP1CostRatioType int32
    SP1CostRatio int32
    AbnormalCostType int32
    AbnormalCostProp []int32
    AbnormalCostValue int32
    AbnormalCostConversion []int32
    AbnormalCostConversionValue []int32
}

const TypeId_SkilldataMontageCost = 1231117681

func (*SkilldataMontageCost) GetTypeId() int32 {
    return 1231117681
}

func NewSkilldataMontageCost(_buf map[string]interface{}) (_v *SkilldataMontageCost, err error) {
    _v = &SkilldataMontageCost{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_Formulation__ interface{}; if __json_Formulation__, _ok_ = _buf["Formulation"]; !_ok_ || __json_Formulation__ == nil { err = errors.New("Formulation error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Formulation__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Formulation = __x__ }}
    { var _ok_ bool; var __json_StaminaCostValue__ interface{}; if __json_StaminaCostValue__, _ok_ = _buf["StaminaCostValue"]; !_ok_ || __json_StaminaCostValue__ == nil { err = errors.New("StaminaCostValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_StaminaCostValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StaminaCostValue = __x__ }}
    { var _ok_ bool; var __json_StaminaCostRatioType__ interface{}; if __json_StaminaCostRatioType__, _ok_ = _buf["StaminaCostRatioType"]; !_ok_ || __json_StaminaCostRatioType__ == nil { err = errors.New("StaminaCostRatioType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_StaminaCostRatioType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StaminaCostRatioType = __x__ }}
    { var _ok_ bool; var __json_StaminaCostRatio__ interface{}; if __json_StaminaCostRatio__, _ok_ = _buf["StaminaCostRatio"]; !_ok_ || __json_StaminaCostRatio__ == nil { err = errors.New("StaminaCostRatio error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_StaminaCostRatio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StaminaCostRatio = __x__ }}
    { var _ok_ bool; var __json_HpCostValue__ interface{}; if __json_HpCostValue__, _ok_ = _buf["HpCostValue"]; !_ok_ || __json_HpCostValue__ == nil { err = errors.New("HpCostValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_HpCostValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HpCostValue = __x__ }}
    { var _ok_ bool; var __json_HpCostRatioType__ interface{}; if __json_HpCostRatioType__, _ok_ = _buf["HpCostRatioType"]; !_ok_ || __json_HpCostRatioType__ == nil { err = errors.New("HpCostRatioType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_HpCostRatioType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HpCostRatioType = __x__ }}
    { var _ok_ bool; var __json_HpCostRatio__ interface{}; if __json_HpCostRatio__, _ok_ = _buf["HpCostRatio"]; !_ok_ || __json_HpCostRatio__ == nil { err = errors.New("HpCostRatio error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_HpCostRatio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HpCostRatio = __x__ }}
    { var _ok_ bool; var __json_ExSkillEnergyCostValue__ interface{}; if __json_ExSkillEnergyCostValue__, _ok_ = _buf["ExSkillEnergyCostValue"]; !_ok_ || __json_ExSkillEnergyCostValue__ == nil { err = errors.New("ExSkillEnergyCostValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ExSkillEnergyCostValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExSkillEnergyCostValue = __x__ }}
    { var _ok_ bool; var __json_ExSkillEnergyCostRatioType__ interface{}; if __json_ExSkillEnergyCostRatioType__, _ok_ = _buf["ExSkillEnergyCostRatioType"]; !_ok_ || __json_ExSkillEnergyCostRatioType__ == nil { err = errors.New("ExSkillEnergyCostRatioType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ExSkillEnergyCostRatioType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExSkillEnergyCostRatioType = __x__ }}
    { var _ok_ bool; var __json_ExSkillEnergyCostRatio__ interface{}; if __json_ExSkillEnergyCostRatio__, _ok_ = _buf["ExSkillEnergyCostRatio"]; !_ok_ || __json_ExSkillEnergyCostRatio__ == nil { err = errors.New("ExSkillEnergyCostRatio error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ExSkillEnergyCostRatio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExSkillEnergyCostRatio = __x__ }}
    { var _ok_ bool; var __json_SPCostValue__ interface{}; if __json_SPCostValue__, _ok_ = _buf["SPCostValue"]; !_ok_ || __json_SPCostValue__ == nil { err = errors.New("SPCostValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SPCostValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SPCostValue = __x__ }}
    { var _ok_ bool; var __json_SPCostRatioType__ interface{}; if __json_SPCostRatioType__, _ok_ = _buf["SPCostRatioType"]; !_ok_ || __json_SPCostRatioType__ == nil { err = errors.New("SPCostRatioType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SPCostRatioType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SPCostRatioType = __x__ }}
    { var _ok_ bool; var __json_SPCostRatio__ interface{}; if __json_SPCostRatio__, _ok_ = _buf["SPCostRatio"]; !_ok_ || __json_SPCostRatio__ == nil { err = errors.New("SPCostRatio error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SPCostRatio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SPCostRatio = __x__ }}
    { var _ok_ bool; var __json_SP1CostValue__ interface{}; if __json_SP1CostValue__, _ok_ = _buf["SP1CostValue"]; !_ok_ || __json_SP1CostValue__ == nil { err = errors.New("SP1CostValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SP1CostValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SP1CostValue = __x__ }}
    { var _ok_ bool; var __json_SP1CostRatioType__ interface{}; if __json_SP1CostRatioType__, _ok_ = _buf["SP1CostRatioType"]; !_ok_ || __json_SP1CostRatioType__ == nil { err = errors.New("SP1CostRatioType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SP1CostRatioType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SP1CostRatioType = __x__ }}
    { var _ok_ bool; var __json_SP1CostRatio__ interface{}; if __json_SP1CostRatio__, _ok_ = _buf["SP1CostRatio"]; !_ok_ || __json_SP1CostRatio__ == nil { err = errors.New("SP1CostRatio error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_SP1CostRatio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SP1CostRatio = __x__ }}
    { var _ok_ bool; var __json_AbnormalCostType__ interface{}; if __json_AbnormalCostType__, _ok_ = _buf["AbnormalCostType"]; !_ok_ || __json_AbnormalCostType__ == nil { err = errors.New("AbnormalCostType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_AbnormalCostType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AbnormalCostType = __x__ }}
    { var _ok_ bool; var __json_AbnormalCostProp__ interface{}; if __json_AbnormalCostProp__, _ok_ = _buf["AbnormalCostProp"]; !_ok_ || __json_AbnormalCostProp__ == nil { err = errors.New("AbnormalCostProp error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AbnormalCostProp__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AbnormalCostProp = __x__ }}
    { var _ok_ bool; var __json_AbnormalCostValue__ interface{}; if __json_AbnormalCostValue__, _ok_ = _buf["AbnormalCostValue"]; !_ok_ || __json_AbnormalCostValue__ == nil { err = errors.New("AbnormalCostValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_AbnormalCostValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AbnormalCostValue = __x__ }}
    { var _ok_ bool; var __json_AbnormalCostConversion__ interface{}; if __json_AbnormalCostConversion__, _ok_ = _buf["AbnormalCostConversion"]; !_ok_ || __json_AbnormalCostConversion__ == nil { err = errors.New("AbnormalCostConversion error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AbnormalCostConversion__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AbnormalCostConversion = __x__ }}
    { var _ok_ bool; var __json_AbnormalCostConversionValue__ interface{}; if __json_AbnormalCostConversionValue__, _ok_ = _buf["AbnormalCostConversionValue"]; !_ok_ || __json_AbnormalCostConversionValue__ == nil { err = errors.New("AbnormalCostConversionValue error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AbnormalCostConversionValue__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AbnormalCostConversionValue = __x__ }}
    return
}

