
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbGACombox struct {
    _dataMap map[int32]*SkilldataGACombo
    _dataList []*SkilldataGACombo
}

func NewSkilldataTbGACombox(_buf []map[string]interface{}) (*SkilldataTbGACombox, error) {
    _dataList := make([]*SkilldataGACombo, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataGACombo)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataGACombo(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbGACombox{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbGACombox) GetDataMap() map[int32]*SkilldataGACombo {
    return table._dataMap
}

func (table *SkilldataTbGACombox) GetDataList() []*SkilldataGACombo {
    return table._dataList
}

func (table *SkilldataTbGACombox) Get(key int32) *SkilldataGACombo {
    return table._dataMap[key]
}


