
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkillPropOpt struct {
    SkillProp int32
    Opt int32
    Count int32
}

const TypeId_SkillPropOpt = -1661482785

func (*SkillPropOpt) GetTypeId() int32 {
    return -1661482785
}

func NewSkillPropOpt(_buf map[string]interface{}) (_v *SkillPropOpt, err error) {
    _v = &SkillPropOpt{}
    { var _ok_ bool; var __json_skillProp__ interface{}; if __json_skillProp__, _ok_ = _buf["skillProp"]; !_ok_ || __json_skillProp__ == nil { err = errors.New("skillProp error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_skillProp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SkillProp = __x__ }}
    { var _ok_ bool; var __json_opt__ interface{}; if __json_opt__, _ok_ = _buf["opt"]; !_ok_ || __json_opt__ == nil { err = errors.New("opt error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_opt__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Opt = __x__ }}
    { var _ok_ bool; var __json_count__ interface{}; if __json_count__, _ok_ = _buf["count"]; !_ok_ || __json_count__ == nil { err = errors.New("count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Count = __x__ }}
    return
}

