
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkilldataMontageAttackData struct {
    ID int32
    GATag string
    AttackDataIds []int32
    BuffIDs []int32
    SkillCostIDs []int32
    BattleTimeDilationK []int32
}

const TypeId_SkilldataMontageAttackData = 541708470

func (*SkilldataMontageAttackData) GetTypeId() int32 {
    return 541708470
}

func NewSkilldataMontageAttackData(_buf map[string]interface{}) (_v *SkilldataMontageAttackData, err error) {
    _v = &SkilldataMontageAttackData{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_GATag__ interface{}; if __json_GATag__, _ok_ = _buf["GATag"]; !_ok_ || __json_GATag__ == nil { err = errors.New("GATag error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_GATag__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.GATag = __x__ }}
    { var _ok_ bool; var __json_AttackData_Ids__ interface{}; if __json_AttackData_Ids__, _ok_ = _buf["AttackData_Ids"]; !_ok_ || __json_AttackData_Ids__ == nil { err = errors.New("AttackData_Ids error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AttackData_Ids__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AttackDataIds = __x__ }}
    { var _ok_ bool; var __json_BuffIDs__ interface{}; if __json_BuffIDs__, _ok_ = _buf["BuffIDs"]; !_ok_ || __json_BuffIDs__ == nil { err = errors.New("BuffIDs error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_BuffIDs__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.BuffIDs = __x__ }}
    { var _ok_ bool; var __json_SkillCostIDs__ interface{}; if __json_SkillCostIDs__, _ok_ = _buf["SkillCostIDs"]; !_ok_ || __json_SkillCostIDs__ == nil { err = errors.New("SkillCostIDs error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_SkillCostIDs__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.SkillCostIDs = __x__ }}
    { var _ok_ bool; var __json_BattleTimeDilationK__ interface{}; if __json_BattleTimeDilationK__, _ok_ = _buf["BattleTimeDilationK"]; !_ok_ || __json_BattleTimeDilationK__ == nil { err = errors.New("BattleTimeDilationK error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_BattleTimeDilationK__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.BattleTimeDilationK = __x__ }}
    return
}

