
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SkilldataGACombo struct {
    ID int32
    ConfigID int32
    AbilityTags string
    AbilityPath string
    Combos []int32
    MontageActions []int32
    BuffIDs []int32
    SkillCostIDs []int32
}

const TypeId_SkilldataGACombo = 1551777633

func (*SkilldataGACombo) GetTypeId() int32 {
    return 1551777633
}

func NewSkilldataGACombo(_buf map[string]interface{}) (_v *SkilldataGACombo, err error) {
    _v = &SkilldataGACombo{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_ConfigID__ interface{}; if __json_ConfigID__, _ok_ = _buf["ConfigID"]; !_ok_ || __json_ConfigID__ == nil { err = errors.New("ConfigID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ConfigID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ConfigID = __x__ }}
    { var _ok_ bool; var __json_AbilityTags__ interface{}; if __json_AbilityTags__, _ok_ = _buf["AbilityTags"]; !_ok_ || __json_AbilityTags__ == nil { err = errors.New("AbilityTags error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_AbilityTags__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.AbilityTags = __x__ }}
    { var _ok_ bool; var __json_AbilityPath__ interface{}; if __json_AbilityPath__, _ok_ = _buf["AbilityPath"]; !_ok_ || __json_AbilityPath__ == nil { err = errors.New("AbilityPath error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_AbilityPath__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.AbilityPath = __x__ }}
    { var _ok_ bool; var __json_Combos__ interface{}; if __json_Combos__, _ok_ = _buf["Combos"]; !_ok_ || __json_Combos__ == nil { err = errors.New("Combos error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Combos__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Combos = __x__ }}
    { var _ok_ bool; var __json_MontageActions__ interface{}; if __json_MontageActions__, _ok_ = _buf["MontageActions"]; !_ok_ || __json_MontageActions__ == nil { err = errors.New("MontageActions error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_MontageActions__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.MontageActions = __x__ }}
    { var _ok_ bool; var __json_BuffIDs__ interface{}; if __json_BuffIDs__, _ok_ = _buf["BuffIDs"]; !_ok_ || __json_BuffIDs__ == nil { err = errors.New("BuffIDs error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_BuffIDs__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.BuffIDs = __x__ }}
    { var _ok_ bool; var __json_SkillCostIDs__ interface{}; if __json_SkillCostIDs__, _ok_ = _buf["SkillCostIDs"]; !_ok_ || __json_SkillCostIDs__ == nil { err = errors.New("SkillCostIDs error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_SkillCostIDs__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.SkillCostIDs = __x__ }}
    return
}

