
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SkilldataTbSkillData struct {
    _dataMap map[int32]*SkilldataSkillData
    _dataList []*SkilldataSkillData
}

func NewSkilldataTbSkillData(_buf []map[string]interface{}) (*SkilldataTbSkillData, error) {
    _dataList := make([]*SkilldataSkillData, 0, len(_buf))
    dataMap := make(map[int32]*SkilldataSkillData)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkilldataSkillData(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &SkilldataTbSkillData{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkilldataTbSkillData) GetDataMap() map[int32]*SkilldataSkillData {
    return table._dataMap
}

func (table *SkilldataTbSkillData) GetDataList() []*SkilldataSkillData {
    return table._dataList
}

func (table *SkilldataTbSkillData) Get(key int32) *SkilldataSkillData {
    return table._dataMap[key]
}


