
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * Spanwer上配置大类型
 */
const (
    /**
     * 默认
     */
    SpawnerConfigType_Default = 0;
    /**
     * 交互物类型配置
     */
    SpawnerConfigType_Interact = 1;
)

