
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 召唤装置状态
 */
const (
    /**
     * 未激活
     */
    SummonMachineState_NotActivated = 0;
    /**
     * 已激活
     */
    SummonMachineState_Activated = 1;
    /**
     * 已关闭
     */
    SummonMachineState_Closed = 2;
)

