
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 召唤装置激活模式
 */
const (
    /**
     * 通过ObjectVolume激活触发
     */
    SummonMachineActiveMode_ObjectVolume_Trigger = 0;
    /**
     * 通过外部事件触发（目前暂时通过流程节点控制触发）
     */
    SummonMachineActiveMode_Event_Trigger = 1;
)

