
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SysTbCommonUnlock struct {
    _dataMap map[int32]*SysCommonUnlock
    _dataList []*SysCommonUnlock
}

func NewSysTbCommonUnlock(_buf []map[string]interface{}) (*SysTbCommonUnlock, error) {
    _dataList := make([]*SysCommonUnlock, 0, len(_buf))
    dataMap := make(map[int32]*SysCommonUnlock)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSysCommonUnlock(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SysTbCommonUnlock{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SysTbCommonUnlock) GetDataMap() map[int32]*SysCommonUnlock {
    return table._dataMap
}

func (table *SysTbCommonUnlock) GetDataList() []*SysCommonUnlock {
    return table._dataList
}

func (table *SysTbCommonUnlock) Get(key int32) *SysCommonUnlock {
    return table._dataMap[key]
}


