
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SysInitCnf struct {
    Id int32
    Values []*SysInitParams
    Label bool
    Longnum int64
}

const TypeId_SysInitCnf = 1979716586

func (*SysInitCnf) GetTypeId() int32 {
    return 1979716586
}

func NewSysInitCnf(_buf map[string]interface{}) (_v *SysInitCnf, err error) {
    _v = &SysInitCnf{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_values__ interface{}; if __json_values__, _ok_ = _buf["values"]; !_ok_ || __json_values__ == nil { err = errors.New("values error"); return } else { var __x__ []*SysInitParams;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_values__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*SysInitParams, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *SysInitParams
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewSysInitParams(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Values = __x__ }}
    { var _ok_ bool; var __json_label__ interface{}; if __json_label__, _ok_ = _buf["label"]; !_ok_ || __json_label__ == nil { err = errors.New("label error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_label__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Label = __x__ }}
    { var _ok_ bool; var __json_longnum__ interface{}; if __json_longnum__, _ok_ = _buf["longnum"]; !_ok_ || __json_longnum__ == nil { err = errors.New("longnum error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_longnum__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Longnum = __x__ }}
    return
}

