
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SysInstruction struct {
    Id int32
    Type int32
    GameTag string
    Sort int32
    InstructionType int32
    Show bool
    OnlyBattleHUDShow bool
    Time int32
    UnLockOptType int32
    UnlockCnds []*UnLockCondBean
    PicRes1 string
    SubName1 string
    SubName1L10n string
    Desc1 string
    Desc1L10n string
    PicRes2 string
    SubName2 string
    SubName2L10n string
    Desc2 string
    Desc2L10n string
    PicRes3 string
    SubName3 string
    SubName3L10n string
    Desc3 string
    Desc3L10n string
    PicRes4 string
    SubName4 string
    Desc4 string
    PicRes5 string
    SubName5 string
    Desc5 string
    PicRes6 string
    SubName6 string
    Desc6 string
    PicRes7 string
    SubName7 string
    Desc7 string
    PicRes8 string
    SubName8 string
    Desc8 string
    FunDesc string
    FunDescL10n string
}

const TypeId_SysInstruction = 462372557

func (*SysInstruction) GetTypeId() int32 {
    return 462372557
}

func NewSysInstruction(_buf map[string]interface{}) (_v *SysInstruction, err error) {
    _v = &SysInstruction{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_GameTag__ interface{}; if __json_GameTag__, _ok_ = _buf["GameTag"]; !_ok_ || __json_GameTag__ == nil { err = errors.New("GameTag error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_GameTag__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.GameTag = __x__ }}
    { var _ok_ bool; var __json_Sort__ interface{}; if __json_Sort__, _ok_ = _buf["Sort"]; !_ok_ || __json_Sort__ == nil { err = errors.New("Sort error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Sort__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Sort = __x__ }}
    { var _ok_ bool; var __json_InstructionType__ interface{}; if __json_InstructionType__, _ok_ = _buf["InstructionType"]; !_ok_ || __json_InstructionType__ == nil { err = errors.New("InstructionType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_InstructionType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.InstructionType = __x__ }}
    { var _ok_ bool; var __json_Show__ interface{}; if __json_Show__, _ok_ = _buf["Show"]; !_ok_ || __json_Show__ == nil { err = errors.New("Show error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_Show__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Show = __x__ }}
    { var _ok_ bool; var __json_OnlyBattleHUDShow__ interface{}; if __json_OnlyBattleHUDShow__, _ok_ = _buf["OnlyBattleHUDShow"]; !_ok_ || __json_OnlyBattleHUDShow__ == nil { err = errors.New("OnlyBattleHUDShow error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_OnlyBattleHUDShow__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.OnlyBattleHUDShow = __x__ }}
    { var _ok_ bool; var __json_Time__ interface{}; if __json_Time__, _ok_ = _buf["Time"]; !_ok_ || __json_Time__ == nil { err = errors.New("Time error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Time__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Time = __x__ }}
    { var _ok_ bool; var __json_UnLockOptType__ interface{}; if __json_UnLockOptType__, _ok_ = _buf["UnLockOptType"]; !_ok_ || __json_UnLockOptType__ == nil { err = errors.New("UnLockOptType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UnLockOptType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnLockOptType = __x__ }}
    { var _ok_ bool; var __json_unlock_cnds__ interface{}; if __json_unlock_cnds__, _ok_ = _buf["unlock_cnds"]; !_ok_ || __json_unlock_cnds__ == nil { err = errors.New("unlock_cnds error"); return } else { var __x__ []*UnLockCondBean;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_unlock_cnds__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*UnLockCondBean, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *UnLockCondBean
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewUnLockCondBean(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.UnlockCnds = __x__ }}
    { var _ok_ bool; var __json_pic_res1__ interface{}; if __json_pic_res1__, _ok_ = _buf["pic_res1"]; !_ok_ || __json_pic_res1__ == nil { err = errors.New("pic_res1 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res1__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes1 = __x__ }}
    { var _ok_ bool; var __json_sub_name1__ interface{}; if __json_sub_name1__, _ok_ = _buf["sub_name1"]; !_ok_ || __json_sub_name1__ == nil { err = errors.New("sub_name1 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name1__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName1 = __x__ }}
    { var _ok_ bool; var __json_sub_name1_L10n__ interface{}; if __json_sub_name1_L10n__, _ok_ = _buf["sub_name1_L10n"]; !_ok_ || __json_sub_name1_L10n__ == nil { err = errors.New("sub_name1_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name1_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName1L10n = __x__ }}
    { var _ok_ bool; var __json_desc_1__ interface{}; if __json_desc_1__, _ok_ = _buf["desc_1"]; !_ok_ || __json_desc_1__ == nil { err = errors.New("desc_1 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_1__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc1 = __x__ }}
    { var _ok_ bool; var __json_desc_1_L10n__ interface{}; if __json_desc_1_L10n__, _ok_ = _buf["desc_1_L10n"]; !_ok_ || __json_desc_1_L10n__ == nil { err = errors.New("desc_1_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_1_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc1L10n = __x__ }}
    { var _ok_ bool; var __json_pic_res2__ interface{}; if __json_pic_res2__, _ok_ = _buf["pic_res2"]; !_ok_ || __json_pic_res2__ == nil { err = errors.New("pic_res2 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res2__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes2 = __x__ }}
    { var _ok_ bool; var __json_sub_name2__ interface{}; if __json_sub_name2__, _ok_ = _buf["sub_name2"]; !_ok_ || __json_sub_name2__ == nil { err = errors.New("sub_name2 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name2__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName2 = __x__ }}
    { var _ok_ bool; var __json_sub_name2_L10n__ interface{}; if __json_sub_name2_L10n__, _ok_ = _buf["sub_name2_L10n"]; !_ok_ || __json_sub_name2_L10n__ == nil { err = errors.New("sub_name2_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name2_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName2L10n = __x__ }}
    { var _ok_ bool; var __json_desc_2__ interface{}; if __json_desc_2__, _ok_ = _buf["desc_2"]; !_ok_ || __json_desc_2__ == nil { err = errors.New("desc_2 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_2__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc2 = __x__ }}
    { var _ok_ bool; var __json_desc_2_L10n__ interface{}; if __json_desc_2_L10n__, _ok_ = _buf["desc_2_L10n"]; !_ok_ || __json_desc_2_L10n__ == nil { err = errors.New("desc_2_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_2_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc2L10n = __x__ }}
    { var _ok_ bool; var __json_pic_res3__ interface{}; if __json_pic_res3__, _ok_ = _buf["pic_res3"]; !_ok_ || __json_pic_res3__ == nil { err = errors.New("pic_res3 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res3__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes3 = __x__ }}
    { var _ok_ bool; var __json_sub_name3__ interface{}; if __json_sub_name3__, _ok_ = _buf["sub_name3"]; !_ok_ || __json_sub_name3__ == nil { err = errors.New("sub_name3 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name3__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName3 = __x__ }}
    { var _ok_ bool; var __json_sub_name3_L10n__ interface{}; if __json_sub_name3_L10n__, _ok_ = _buf["sub_name3_L10n"]; !_ok_ || __json_sub_name3_L10n__ == nil { err = errors.New("sub_name3_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name3_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName3L10n = __x__ }}
    { var _ok_ bool; var __json_desc_3__ interface{}; if __json_desc_3__, _ok_ = _buf["desc_3"]; !_ok_ || __json_desc_3__ == nil { err = errors.New("desc_3 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_3__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc3 = __x__ }}
    { var _ok_ bool; var __json_desc_3_L10n__ interface{}; if __json_desc_3_L10n__, _ok_ = _buf["desc_3_L10n"]; !_ok_ || __json_desc_3_L10n__ == nil { err = errors.New("desc_3_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_3_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc3L10n = __x__ }}
    { var _ok_ bool; var __json_pic_res4__ interface{}; if __json_pic_res4__, _ok_ = _buf["pic_res4"]; !_ok_ || __json_pic_res4__ == nil { err = errors.New("pic_res4 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res4__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes4 = __x__ }}
    { var _ok_ bool; var __json_sub_name4__ interface{}; if __json_sub_name4__, _ok_ = _buf["sub_name4"]; !_ok_ || __json_sub_name4__ == nil { err = errors.New("sub_name4 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name4__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName4 = __x__ }}
    { var _ok_ bool; var __json_desc_4__ interface{}; if __json_desc_4__, _ok_ = _buf["desc_4"]; !_ok_ || __json_desc_4__ == nil { err = errors.New("desc_4 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_4__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc4 = __x__ }}
    { var _ok_ bool; var __json_pic_res5__ interface{}; if __json_pic_res5__, _ok_ = _buf["pic_res5"]; !_ok_ || __json_pic_res5__ == nil { err = errors.New("pic_res5 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res5__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes5 = __x__ }}
    { var _ok_ bool; var __json_sub_name5__ interface{}; if __json_sub_name5__, _ok_ = _buf["sub_name5"]; !_ok_ || __json_sub_name5__ == nil { err = errors.New("sub_name5 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name5__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName5 = __x__ }}
    { var _ok_ bool; var __json_desc_5__ interface{}; if __json_desc_5__, _ok_ = _buf["desc_5"]; !_ok_ || __json_desc_5__ == nil { err = errors.New("desc_5 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_5__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc5 = __x__ }}
    { var _ok_ bool; var __json_pic_res6__ interface{}; if __json_pic_res6__, _ok_ = _buf["pic_res6"]; !_ok_ || __json_pic_res6__ == nil { err = errors.New("pic_res6 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res6__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes6 = __x__ }}
    { var _ok_ bool; var __json_sub_name6__ interface{}; if __json_sub_name6__, _ok_ = _buf["sub_name6"]; !_ok_ || __json_sub_name6__ == nil { err = errors.New("sub_name6 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name6__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName6 = __x__ }}
    { var _ok_ bool; var __json_desc_6__ interface{}; if __json_desc_6__, _ok_ = _buf["desc_6"]; !_ok_ || __json_desc_6__ == nil { err = errors.New("desc_6 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_6__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc6 = __x__ }}
    { var _ok_ bool; var __json_pic_res7__ interface{}; if __json_pic_res7__, _ok_ = _buf["pic_res7"]; !_ok_ || __json_pic_res7__ == nil { err = errors.New("pic_res7 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res7__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes7 = __x__ }}
    { var _ok_ bool; var __json_sub_name7__ interface{}; if __json_sub_name7__, _ok_ = _buf["sub_name7"]; !_ok_ || __json_sub_name7__ == nil { err = errors.New("sub_name7 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name7__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName7 = __x__ }}
    { var _ok_ bool; var __json_desc_7__ interface{}; if __json_desc_7__, _ok_ = _buf["desc_7"]; !_ok_ || __json_desc_7__ == nil { err = errors.New("desc_7 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_7__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc7 = __x__ }}
    { var _ok_ bool; var __json_pic_res8__ interface{}; if __json_pic_res8__, _ok_ = _buf["pic_res8"]; !_ok_ || __json_pic_res8__ == nil { err = errors.New("pic_res8 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_pic_res8__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PicRes8 = __x__ }}
    { var _ok_ bool; var __json_sub_name8__ interface{}; if __json_sub_name8__, _ok_ = _buf["sub_name8"]; !_ok_ || __json_sub_name8__ == nil { err = errors.New("sub_name8 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_sub_name8__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.SubName8 = __x__ }}
    { var _ok_ bool; var __json_desc_8__ interface{}; if __json_desc_8__, _ok_ = _buf["desc_8"]; !_ok_ || __json_desc_8__ == nil { err = errors.New("desc_8 error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc_8__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc8 = __x__ }}
    { var _ok_ bool; var __json_fun_desc__ interface{}; if __json_fun_desc__, _ok_ = _buf["fun_desc"]; !_ok_ || __json_fun_desc__ == nil { err = errors.New("fun_desc error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_fun_desc__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.FunDesc = __x__ }}
    { var _ok_ bool; var __json_fun_desc_L10n__ interface{}; if __json_fun_desc_L10n__, _ok_ = _buf["fun_desc_L10n"]; !_ok_ || __json_fun_desc_L10n__ == nil { err = errors.New("fun_desc_L10n error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_fun_desc_L10n__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.FunDescL10n = __x__ }}
    return
}

