
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SysTbInitCnf struct {
    _dataMap map[int32]*SysInitCnf
    _dataList []*SysInitCnf
}

func NewSysTbInitCnf(_buf []map[string]interface{}) (*SysTbInitCnf, error) {
    _dataList := make([]*SysInitCnf, 0, len(_buf))
    dataMap := make(map[int32]*SysInitCnf)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSysInitCnf(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SysTbInitCnf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SysTbInitCnf) GetDataMap() map[int32]*SysInitCnf {
    return table._dataMap
}

func (table *SysTbInitCnf) GetDataList() []*SysInitCnf {
    return table._dataList
}

func (table *SysTbInitCnf) Get(key int32) *SysInitCnf {
    return table._dataMap[key]
}


