
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SysGlobalParams struct {
    Id int32
    INTARRAY []int32
    Vector3 *Vector3
    INT int32
    STRING string
}

const TypeId_SysGlobalParams = -71935830

func (*SysGlobalParams) GetTypeId() int32 {
    return -71935830
}

func NewSysGlobalParams(_buf map[string]interface{}) (_v *SysGlobalParams, err error) {
    _v = &SysGlobalParams{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_INT_ARRAY__ interface{}; if __json_INT_ARRAY__, _ok_ = _buf["INT_ARRAY"]; !_ok_ || __json_INT_ARRAY__ == nil { err = errors.New("INT_ARRAY error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_INT_ARRAY__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.INTARRAY = __x__ }}
    { var _ok_ bool; var __json_Vector3__ interface{}; if __json_Vector3__, _ok_ = _buf["Vector3"]; !_ok_ || __json_Vector3__ == nil { err = errors.New("Vector3 error"); return } else { var __x__ *Vector3;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_Vector3__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewVector3(_x_); err != nil { return } }; _v.Vector3 = __x__ }}
    { var _ok_ bool; var __json_INT__ interface{}; if __json_INT__, _ok_ = _buf["INT"]; !_ok_ || __json_INT__ == nil { err = errors.New("INT error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_INT__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.INT = __x__ }}
    { var _ok_ bool; var __json_STRING__ interface{}; if __json_STRING__, _ok_ = _buf["STRING"]; !_ok_ || __json_STRING__ == nil { err = errors.New("STRING error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_STRING__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.STRING = __x__ }}
    return
}

