
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 系统功能菜单
 */
const (
    SysFunMenu_NONE = 0;
    /**
     * 背包
     */
    SysFunMenu_BAG_PACK = 1;
    /**
     * 商店
     */
    SysFunMenu_SHOP = 2;
    /**
     * 活动
     */
    SysFunMenu_ACTIVITY = 3;
    /**
     * 伙伴
     */
    SysFunMenu_AVATAR = 4;
    /**
     * 编队
     */
    SysFunMenu_FORMATION = 5;
    /**
     * 菜单
     */
    SysFunMenu_GAMEMENU = 6;
    /**
     * 说明
     */
    SysFunMenu_INSTRUCTION = 7;
    /**
     * 武器强化
     */
    SysFunMenu_WEAPONDEVELOP = 8;
    /**
     * 抽卡
     */
    SysFunMenu_GachaMain = 9;
    /**
     * 装备强化
     */
    SysFunMenu_EQUIPMENTDEVELOP = 10;
    /**
     * 任务
     */
    SysFunMenu_QUEST = 11;
    /**
     * 大地图
     */
    SysFunMenu_BIGMAP = 12;
    /**
     * 深渊
     */
    SysFunMenu_Maze = 13;
    /**
     * 净海指南
     */
    SysFunMenu_DungeonManual = 14;
    /**
     * 资源本
     */
    SysFunMenu_ResourceLevel = 15;
    /**
     * 好感
     */
    SysFunMenu_Favorability = 16;
    /**
     * 随机陆礁
     */
    SysFunMenu_RandomIsland = 17;
    /**
     * 教学关卡
     */
    SysFunMenu_TeachLevel = 18;
    /**
     * 基础关卡
     */
    SysFunMenu_TeachLevelBASE = 19;
    /**
     * 进阶关卡
     */
    SysFunMenu_TeachLevelADVANCED = 20;
    /**
     * 角色关卡
     */
    SysFunMenu_TeachLevelAVATAR = 21;
    /**
     * 海巡兽殖装
     */
    SysFunMenu_ShipTalent = 22;
    /**
     * 成就
     */
    SysFunMenu_Achievement = 23;
    /**
     * 每日任务
     */
    SysFunMenu_DailyQuest = 24;
    /**
     * 净海见闻
     */
    SysFunMenu_GuideQuest = 25;
    /**
     * 星轨
     */
    SysFunMenu_AVATARWEAPON = 26;
    /**
     * 天赋
     */
    SysFunMenu_AVATARTALENT = 27;
    /**
     * 装备
     */
    SysFunMenu_AVATAREQUIPMENT = 28;
    /**
     * 溯源
     */
    SysFunMenu_AVATARCONSTELLATION = 29;
    /**
     * 苍浪陆礁
     */
    SysFunMenu_RESLVBASE = 30;
    /**
     * 跃升之泉
     */
    SysFunMenu_RESLVEXCEED = 31;
    /**
     * 真识遗迹
     */
    SysFunMenu_RESLVTALENT = 32;
    /**
     * 武甲秘库
     */
    SysFunMenu_RESLVEQUIPMARK = 33;
    /**
     * 与狭间
     */
    SysFunMenu_YXJ = 34;
    /**
     * 净海区域集市
     */
    SysFunMenu_JHAreaMarket = 35;
    /**
     * 邮件
     */
    SysFunMenu_MAIL = 36;
    /**
     * 净海
     */
    SysFunMenu_SANDSEA = 37;
    /**
     * 等级奖励
     */
    SysFunMenu_LEVELREWARD = 38;
    /**
     * 净海地图按钮
     */
    SysFunMenu_JHMapButton = 39;
    /**
     * 前往净海按钮
     */
    SysFunMenu_ToJHButton = 40;
    /**
     * 净海区域商店
     */
    SysFunMenu_JHAreaShop = 41;
    /**
     * 净海箱庭地图按钮
     */
    SysFunMenu_JHLevelMap = 42;
    /**
     * 祈玉背包
     */
    SysFunMenu_MarkBagPack = 43;
    /**
     * boss本
     */
    SysFunMenu_BossLevel = 44;
    /**
     * 祈玉本
     */
    SysFunMenu_MarkLevel = 45;
    /**
     * 家园
     */
    SysFunMenu_HOME = 46;
    /**
     * 合成
     */
    SysFunMenu_SYNTHESIS = 47;
    /**
     * 零能系统
     */
    SysFunMenu_ZERO_ENERGY = 48;
    /**
     * 寄生虫系统
     */
    SysFunMenu_PARASITE = 49;
    /**
     * 新添加的枚举要这个枚举前面
     */
    SysFunMenu_MAX = 50;
)

