
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 系统初始化功能列表
 */
const (
    SysInitType_NONE = 0;
    /**
     * 角色初始化
     */
    SysInitType_INIT_AVATAR = 1;
    /**
     * 道具初始化
     */
    SysInitType_INIT_ITEMS = 2;
    /**
     * 场景初始化ID
     */
    SysInitType_INIT_SCENE_ID = 3;
    /**
     * 多人场景初始化ID
     */
    SysInitType_INIT_MMO_SCENE_ID = 4;
    /**
     * 海巡兽初始化
     */
    SysInitType_INIT_SHIP = 5;
    /**
     * 编队初始化
     */
    SysInitType_INIT_FORMATION = 6;
    /**
     * 海巡兽出现的场景
     */
    SysInitType_INIT_SHIP_SCENE_ID = 7;
    /**
     * 初始疲劳
     */
    SysInitType_INIT_FATIGUE = 8;
    /**
     * 初始备用疲劳
     */
    SysInitType_INIT_STANDBYFATIGUE = 9;
    /**
     * 玩家昵称唯一
     */
    SysInitType_INIT_NICKNAME_UNIQUE = 10;
    /**
     * 净海默认传送点
     */
    SysInitType_INIT_SANDSEA_TELEPORTER_ID = 11;
    /**
     * 卡死重置的CD
     */
    SysInitType_STUCK_RESET_CD = 12;
    /**
     * 家园场景ID
     */
    SysInitType_INIT_GARDEN_SCENE_ID = 13;
    /**
     * 攻城仓ID
     */
    SysInitType_INIT_DROPPOD = 14;
)

