
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    TbScene *SceneTbScene
    TbLevel *SceneTbLevel
    TbArea *SceneTbArea
    TbSceneObject *SceneTbSceneObject
    TbVisualObject *SceneTbVisualObject
    TbInitCnf *SysTbInitCnf
    TbInstruction *SysTbInstruction
    TbGlobalParams *SysTbGlobalParams
    TbChapter *QuestTbChapter
    TbQuest *QuestTbQuest
    TbQuestStep *QuestTbQuestStep
    TbQuestGlobalVar *QuestTbQuestGlobalVar
    TbWorldLevelExceed *WorldLevelTbWorldLevelExceed
    TbWorldLevelTypeDesc *WorldLevelTbWorldLevelTypeDesc
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("scene_tbscene") ; err != nil {
        return nil, err
    }
    if tables.TbScene, err = NewSceneTbScene(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("scene_tblevel") ; err != nil {
        return nil, err
    }
    if tables.TbLevel, err = NewSceneTbLevel(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("scene_tbarea") ; err != nil {
        return nil, err
    }
    if tables.TbArea, err = NewSceneTbArea(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("scene_tbsceneobject") ; err != nil {
        return nil, err
    }
    if tables.TbSceneObject, err = NewSceneTbSceneObject(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("scene_tbvisualobject") ; err != nil {
        return nil, err
    }
    if tables.TbVisualObject, err = NewSceneTbVisualObject(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("sys_tbinitcnf") ; err != nil {
        return nil, err
    }
    if tables.TbInitCnf, err = NewSysTbInitCnf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("sys_tbinstruction") ; err != nil {
        return nil, err
    }
    if tables.TbInstruction, err = NewSysTbInstruction(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("sys_tbglobalparams") ; err != nil {
        return nil, err
    }
    if tables.TbGlobalParams, err = NewSysTbGlobalParams(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("quest_tbchapter") ; err != nil {
        return nil, err
    }
    if tables.TbChapter, err = NewQuestTbChapter(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("quest_tbquest") ; err != nil {
        return nil, err
    }
    if tables.TbQuest, err = NewQuestTbQuest(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("quest_tbqueststep") ; err != nil {
        return nil, err
    }
    if tables.TbQuestStep, err = NewQuestTbQuestStep(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("quest_tbquestglobalvar") ; err != nil {
        return nil, err
    }
    if tables.TbQuestGlobalVar, err = NewQuestTbQuestGlobalVar(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("worldlevel_tbworldlevelexceed") ; err != nil {
        return nil, err
    }
    if tables.TbWorldLevelExceed, err = NewWorldLevelTbWorldLevelExceed(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("worldlevel_tbworldleveltypedesc") ; err != nil {
        return nil, err
    }
    if tables.TbWorldLevelTypeDesc, err = NewWorldLevelTbWorldLevelTypeDesc(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


