
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 敌人
     */
    TargetType_Enemy = 0;
    /**
     * 队友
     */
    TargetType_Friend = 1;
    /**
     * 自己
     */
    TargetType_Self = 2;
    /**
     * 所有人
     */
    TargetType_All = 3;
    /**
     * 除了自己的所有人
     */
    TargetType_AllExcludeSelf = 4;
)

