
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景传送门状态
 */
const (
    /**
     * 未激活
     */
    TeleporterSceneState_NotActivated = 0;
    /**
     * 已激活
     */
    TeleporterSceneState_Activated = 1;
    /**
     * 已交互
     */
    TeleporterSceneState_Interacted = 2;
)

