
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 通用触发机关状态，在A和B之间切换
 */
const (
    /**
     * 状态A
     */
    TriggerDeviceState_StateA = 0;
    /**
     * 状态B
     */
    TriggerDeviceState_StateB = 1;
)

