
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未定义
     */
    UIType_NONE = 0;
    /**
     * 战斗
     */
    UIType_BATTLE = 1;
    /**
     * 家园
     */
    UIType_HOMELAND = 2;
    /**
     * 净海
     */
    UIType_SAND_OCEAN = 3;
    /**
     * 副本
     */
    UIType_DUNGEON = 4;
    /**
     * 攻城仓玩法
     */
    UIType_DROPPOD = 5;
)

