
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 条件并且或者（&amp;&amp; ||）
 */
const (
    /**
     * 无
     */
    UnLockOpt_NONE = 0;
    /**
     * 并且
     */
    UnLockOpt_AND = 1;
    /**
     * 或者
     */
    UnLockOpt_OR = 2;
)

