
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type UnLockCondBean struct {
    CndId int32
    Value int64
}

const TypeId_UnLockCondBean = -1527728746

func (*UnLockCondBean) GetTypeId() int32 {
    return -1527728746
}

func NewUnLockCondBean(_buf map[string]interface{}) (_v *UnLockCondBean, err error) {
    _v = &UnLockCondBean{}
    { var _ok_ bool; var __json_cndId__ interface{}; if __json_cndId__, _ok_ = _buf["cndId"]; !_ok_ || __json_cndId__ == nil { err = errors.New("cndId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_cndId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CndId = __x__ }}
    { var _ok_ bool; var __json_value__ interface{}; if __json_value__, _ok_ = _buf["value"]; !_ok_ || __json_value__ == nil { err = errors.New("value error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_value__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Value = __x__ }}
    return
}

