
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 解锁的条件类型
 */
const (
    UnLockCnd_NONE = 0;
    /**
     * 玩家等级
     */
    UnLockCnd_PLAYER_LEVEL = 1;
    /**
     * 主线任务完成
     */
    UnLockCnd_MAIN_TASK = 2;
    /**
     * 系统功能解锁
     */
    UnLockCnd_SYSTEM_UNLOCK = 3;
    /**
     * 任务步骤完成
     */
    UnLockCnd_QUEST_STEP = 4;
    /**
     * 对应SysFunMenu
     */
    UnLockCnd_OPEN_INTERFACE = 5;
    /**
     * 任务QuestExec主动触发的解锁
     */
    UnLockCnd_QUEST_EXEC = 6;
    /**
     * 参数:角色id
     */
    UnLockCnd_GET_AVATAR = 7;
    /**
     * guidestepID
     */
    UnLockCnd_GUIDE_STEP = 8;
    /**
     * 条件参数根据需求专做
     */
    UnLockCnd_TAG_UNLOCK = 9;
    /**
     * 海巡兽天赋id
     */
    UnLockCnd_SHIP_TALENT_UNLOCK = 10;
)

