
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 场景内Actor的视野分层
 */
const (
    /**
     * 正常视距: 80M内可见
     */
    VisionLevelType_VISION_LEVEL_NORMAL = 0;
    /**
     * 较远视距: 160m内可见
     */
    VisionLevelType_VISION_LEVEL_LITTLE_REMOTE = 1;
    /**
     * 远视距: 1000m内可见
     */
    VisionLevelType_VISION_LEVEL_REMOTE = 2;
    /**
     * 超级视距: 4000m内可见
     */
    VisionLevelType_VISION_LEVEL_SUPER = 3;
)

