
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 方形
     */
    VolumeShape_EVS_Box = 0;
    /**
     * 圆形
     */
    VolumeShape_EVS_Sphere = 1;
)

