
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * Buff区域的BUFF移除类型
 */
const (
    /**
     * 走Buff自身的生命周期，不特殊处理
     */
    VolumeBuffRemoveType_OwnLifeTime = 0;
    /**
     * 离开区域立即删除通过该机关触发的BUFF
     */
    VolumeBuffRemoveType_RemoveOnExitVolume = 1;
)

