
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type WorldLevelTbWorldLevelTypeDesc struct {
    _dataMap map[int32]*WorldLevelWorldLevelTypeDesc
    _dataList []*WorldLevelWorldLevelTypeDesc
}

func NewWorldLevelTbWorldLevelTypeDesc(_buf []map[string]interface{}) (*WorldLevelTbWorldLevelTypeDesc, error) {
    _dataList := make([]*WorldLevelWorldLevelTypeDesc, 0, len(_buf))
    dataMap := make(map[int32]*WorldLevelWorldLevelTypeDesc)

    for _, _ele_ := range _buf {
        if _v, err2 := NewWorldLevelWorldLevelTypeDesc(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.TypeID] = _v
        }
    }
    return &WorldLevelTbWorldLevelTypeDesc{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *WorldLevelTbWorldLevelTypeDesc) GetDataMap() map[int32]*WorldLevelWorldLevelTypeDesc {
    return table._dataMap
}

func (table *WorldLevelTbWorldLevelTypeDesc) GetDataList() []*WorldLevelWorldLevelTypeDesc {
    return table._dataList
}

func (table *WorldLevelTbWorldLevelTypeDesc) Get(key int32) *WorldLevelWorldLevelTypeDesc {
    return table._dataMap[key]
}


