
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type WorldLevelTbWorldLevelExceed struct {
    _dataMap map[int32]*WorldLevelWorldLevelExceed
    _dataList []*WorldLevelWorldLevelExceed
}

func NewWorldLevelTbWorldLevelExceed(_buf []map[string]interface{}) (*WorldLevelTbWorldLevelExceed, error) {
    _dataList := make([]*WorldLevelWorldLevelExceed, 0, len(_buf))
    dataMap := make(map[int32]*WorldLevelWorldLevelExceed)

    for _, _ele_ := range _buf {
        if _v, err2 := NewWorldLevelWorldLevelExceed(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &WorldLevelTbWorldLevelExceed{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *WorldLevelTbWorldLevelExceed) GetDataMap() map[int32]*WorldLevelWorldLevelExceed {
    return table._dataMap
}

func (table *WorldLevelTbWorldLevelExceed) GetDataList() []*WorldLevelWorldLevelExceed {
    return table._dataList
}

func (table *WorldLevelTbWorldLevelExceed) Get(key int32) *WorldLevelWorldLevelExceed {
    return table._dataMap[key]
}


