
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type WorldLevelWorldLevelTypeDesc struct {
    TypeID int32
}

const TypeId_WorldLevelWorldLevelTypeDesc = -327514471

func (*WorldLevelWorldLevelTypeDesc) GetTypeId() int32 {
    return -327514471
}

func NewWorldLevelWorldLevelTypeDesc(_buf map[string]interface{}) (_v *WorldLevelWorldLevelTypeDesc, err error) {
    _v = &WorldLevelWorldLevelTypeDesc{}
    { var _ok_ bool; var __json_TypeID__ interface{}; if __json_TypeID__, _ok_ = _buf["TypeID"]; !_ok_ || __json_TypeID__ == nil { err = errors.New("TypeID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TypeID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TypeID = __x__ }}
    return
}

