
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 未定义
     */
    WorldLevelExceedLevelType_NONE = 0;
    /**
     * 世界等级突破
     */
    WorldLevelExceedLevelType_WORLDLEVELEXCEED = 1;
)

