// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: BinServer.proto

package protoGen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorBin struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SpawnerPreId       int64                  `protobuf:"varint,1,opt,name=spawnerPreId,proto3" json:"spawnerPreId,omitempty"`            //生成器的preassignedId
	PreassignedId      int64                  `protobuf:"varint,2,opt,name=preassignedId,proto3" json:"preassignedId,omitempty"`          //自身的preassignedId
	ActorType          int32                  `protobuf:"varint,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` //类型
	DataBin            []byte                 `protobuf:"bytes,4,opt,name=dataBin,proto3" json:"dataBin,omitempty"`
	Pos                *Vector3Int            `protobuf:"bytes,5,opt,name=pos,proto3" json:"pos,omitempty"`
	Rot                *Vector3Int            `protobuf:"bytes,6,opt,name=rot,proto3" json:"rot,omitempty"`
	LogicState         int32                  `protobuf:"varint,7,opt,name=logicState,proto3" json:"logicState,omitempty"`                                              //逻辑状态
	State              int32                  `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`                                                        //对应Actor在scene_object.xlsx中各自的枚举，比如Chest对应ChestState
	TriggeredGuids     []int64                `protobuf:"varint,9,rep,packed,name=triggeredGuids,proto3" json:"triggeredGuids,omitempty"`                               //触发者的GUID列表
	ExtData            []byte                 `protobuf:"bytes,10,opt,name=ext_data,json=extData,proto3" json:"ext_data,omitempty"`                                     //actor 额外数据
	ConfigId           int64                  `protobuf:"varint,11,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                                 //配置ID，有随机逻辑
	CustomInteractType int32                  `protobuf:"varint,12,opt,name=custom_interact_type,json=customInteractType,proto3" json:"custom_interact_type,omitempty"` //自定义交互类型
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActorBin) Reset() {
	*x = ActorBin{}
	mi := &file_BinServer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorBin) ProtoMessage() {}

func (x *ActorBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorBin.ProtoReflect.Descriptor instead.
func (*ActorBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{0}
}

func (x *ActorBin) GetSpawnerPreId() int64 {
	if x != nil {
		return x.SpawnerPreId
	}
	return 0
}

func (x *ActorBin) GetPreassignedId() int64 {
	if x != nil {
		return x.PreassignedId
	}
	return 0
}

func (x *ActorBin) GetActorType() int32 {
	if x != nil {
		return x.ActorType
	}
	return 0
}

func (x *ActorBin) GetDataBin() []byte {
	if x != nil {
		return x.DataBin
	}
	return nil
}

func (x *ActorBin) GetPos() *Vector3Int {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *ActorBin) GetRot() *Vector3Int {
	if x != nil {
		return x.Rot
	}
	return nil
}

func (x *ActorBin) GetLogicState() int32 {
	if x != nil {
		return x.LogicState
	}
	return 0
}

func (x *ActorBin) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ActorBin) GetTriggeredGuids() []int64 {
	if x != nil {
		return x.TriggeredGuids
	}
	return nil
}

func (x *ActorBin) GetExtData() []byte {
	if x != nil {
		return x.ExtData
	}
	return nil
}

func (x *ActorBin) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ActorBin) GetCustomInteractType() int32 {
	if x != nil {
		return x.CustomInteractType
	}
	return 0
}

// 临时用来再次触发关卡节点
type TempAvatarBin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarConfId  int64                  `protobuf:"varint,1,opt,name=avatarConfId,proto3" json:"avatarConfId,omitempty"`
	OwnerPlayerId int64                  `protobuf:"varint,2,opt,name=ownerPlayerId,proto3" json:"ownerPlayerId,omitempty"`
	IsJoin        bool                   `protobuf:"varint,3,opt,name=isJoin,proto3" json:"isJoin,omitempty"`
	IsSwitchTo    bool                   `protobuf:"varint,4,opt,name=isSwitchTo,proto3" json:"isSwitchTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempAvatarBin) Reset() {
	*x = TempAvatarBin{}
	mi := &file_BinServer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempAvatarBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempAvatarBin) ProtoMessage() {}

func (x *TempAvatarBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempAvatarBin.ProtoReflect.Descriptor instead.
func (*TempAvatarBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{1}
}

func (x *TempAvatarBin) GetAvatarConfId() int64 {
	if x != nil {
		return x.AvatarConfId
	}
	return 0
}

func (x *TempAvatarBin) GetOwnerPlayerId() int64 {
	if x != nil {
		return x.OwnerPlayerId
	}
	return 0
}

func (x *TempAvatarBin) GetIsJoin() bool {
	if x != nil {
		return x.IsJoin
	}
	return false
}

func (x *TempAvatarBin) GetIsSwitchTo() bool {
	if x != nil {
		return x.IsSwitchTo
	}
	return false
}

type MonsterBin struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CampType        int32                  `protobuf:"varint,1,opt,name=camp_type,json=campType,proto3" json:"camp_type,omitempty"`
	DlgTags         *DlgTagsProto          `protobuf:"bytes,2,opt,name=dlg_tags,json=dlgTags,proto3" json:"dlg_tags,omitempty"`
	DynamicList     []*DynamicInteractInfo `protobuf:"bytes,3,rep,name=dynamic_list,json=dynamicList,proto3" json:"dynamic_list,omitempty"`
	DifficultyId    int32                  `protobuf:"varint,4,opt,name=difficulty_id,json=difficultyId,proto3" json:"difficulty_id,omitempty"`                   //难度ID，有随机逻辑
	AdditionTagList []int32                `protobuf:"varint,5,rep,packed,name=addition_tag_list,json=additionTagList,proto3" json:"addition_tag_list,omitempty"` //自定义Tag列表，有随机逻辑
	DialogueId      int64                  `protobuf:"varint,6,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`                         //对话树ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MonsterBin) Reset() {
	*x = MonsterBin{}
	mi := &file_BinServer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterBin) ProtoMessage() {}

func (x *MonsterBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterBin.ProtoReflect.Descriptor instead.
func (*MonsterBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{2}
}

func (x *MonsterBin) GetCampType() int32 {
	if x != nil {
		return x.CampType
	}
	return 0
}

func (x *MonsterBin) GetDlgTags() *DlgTagsProto {
	if x != nil {
		return x.DlgTags
	}
	return nil
}

func (x *MonsterBin) GetDynamicList() []*DynamicInteractInfo {
	if x != nil {
		return x.DynamicList
	}
	return nil
}

func (x *MonsterBin) GetDifficultyId() int32 {
	if x != nil {
		return x.DifficultyId
	}
	return 0
}

func (x *MonsterBin) GetAdditionTagList() []int32 {
	if x != nil {
		return x.AdditionTagList
	}
	return nil
}

func (x *MonsterBin) GetDialogueId() int64 {
	if x != nil {
		return x.DialogueId
	}
	return 0
}

// 怪物小队管理器
type MonsterSquadManagerBin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurBatch      int32                  `protobuf:"varint,1,opt,name=curBatch,proto3" json:"curBatch,omitempty"` //当前生成的轮次
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterSquadManagerBin) Reset() {
	*x = MonsterSquadManagerBin{}
	mi := &file_BinServer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterSquadManagerBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterSquadManagerBin) ProtoMessage() {}

func (x *MonsterSquadManagerBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterSquadManagerBin.ProtoReflect.Descriptor instead.
func (*MonsterSquadManagerBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{3}
}

func (x *MonsterSquadManagerBin) GetCurBatch() int32 {
	if x != nil {
		return x.CurBatch
	}
	return 0
}

// 门
type DoorBin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockState     int32                  `protobuf:"varint,1,opt,name=lockState,proto3" json:"lockState,omitempty"` //锁定状态，对应LockState
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorBin) Reset() {
	*x = DoorBin{}
	mi := &file_BinServer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorBin) ProtoMessage() {}

func (x *DoorBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorBin.ProtoReflect.Descriptor instead.
func (*DoorBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{4}
}

func (x *DoorBin) GetLockState() int32 {
	if x != nil {
		return x.LockState
	}
	return 0
}

// 怪物生成器
type MonsterSpawnerBin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenActorPreID int64                  `protobuf:"varint,1,opt,name=genActorPreID,proto3" json:"genActorPreID,omitempty"` //生成的Actor的preassignedId
	CanAutoSpawn  bool                   `protobuf:"varint,2,opt,name=canAutoSpawn,proto3" json:"canAutoSpawn,omitempty"`   //是否能够
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterSpawnerBin) Reset() {
	*x = MonsterSpawnerBin{}
	mi := &file_BinServer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterSpawnerBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterSpawnerBin) ProtoMessage() {}

func (x *MonsterSpawnerBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterSpawnerBin.ProtoReflect.Descriptor instead.
func (*MonsterSpawnerBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{5}
}

func (x *MonsterSpawnerBin) GetGenActorPreID() int64 {
	if x != nil {
		return x.GenActorPreID
	}
	return 0
}

func (x *MonsterSpawnerBin) GetCanAutoSpawn() bool {
	if x != nil {
		return x.CanAutoSpawn
	}
	return false
}

// 对象生成器
type ObjectSpawnerBin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenActorPreID int64                  `protobuf:"varint,1,opt,name=genActorPreID,proto3" json:"genActorPreID,omitempty"` //生成的Actor的preassignedId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectSpawnerBin) Reset() {
	*x = ObjectSpawnerBin{}
	mi := &file_BinServer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectSpawnerBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSpawnerBin) ProtoMessage() {}

func (x *ObjectSpawnerBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSpawnerBin.ProtoReflect.Descriptor instead.
func (*ObjectSpawnerBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectSpawnerBin) GetGenActorPreID() int64 {
	if x != nil {
		return x.GenActorPreID
	}
	return 0
}

// 通用机关生成器
type TrapSpawnerBin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenActorPreID int64                  `protobuf:"varint,1,opt,name=genActorPreID,proto3" json:"genActorPreID,omitempty"` //生成的Actor的preassignedId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrapSpawnerBin) Reset() {
	*x = TrapSpawnerBin{}
	mi := &file_BinServer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrapSpawnerBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrapSpawnerBin) ProtoMessage() {}

func (x *TrapSpawnerBin) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrapSpawnerBin.ProtoReflect.Descriptor instead.
func (*TrapSpawnerBin) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{7}
}

func (x *TrapSpawnerBin) GetGenActorPreID() int64 {
	if x != nil {
		return x.GenActorPreID
	}
	return 0
}

type SceneActorData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Actors           map[int64]*ActorBin    `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BeginTime        int64                  `protobuf:"varint,2,opt,name=beginTime,proto3" json:"beginTime,omitempty"`                                                                                          //场景开始时间
	ActorDestroyTime map[int64]int64        `protobuf:"bytes,3,rep,name=actorDestroyTime,proto3" json:"actorDestroyTime,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //actor的销毁时间，只有需要记录的才会记录
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SceneActorData) Reset() {
	*x = SceneActorData{}
	mi := &file_BinServer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneActorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneActorData) ProtoMessage() {}

func (x *SceneActorData) ProtoReflect() protoreflect.Message {
	mi := &file_BinServer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneActorData.ProtoReflect.Descriptor instead.
func (*SceneActorData) Descriptor() ([]byte, []int) {
	return file_BinServer_proto_rawDescGZIP(), []int{8}
}

func (x *SceneActorData) GetActors() map[int64]*ActorBin {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *SceneActorData) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *SceneActorData) GetActorDestroyTime() map[int64]int64 {
	if x != nil {
		return x.ActorDestroyTime
	}
	return nil
}

var File_BinServer_proto protoreflect.FileDescriptor

const file_BinServer_proto_rawDesc = "" +
	"\n" +
	"\x0fBinServer.proto\x1a\x11ProtoCommon.proto\x1a\x14ProtoSceneObjs.proto\"\x93\x03\n" +
	"\bActorBin\x12\"\n" +
	"\fspawnerPreId\x18\x01 \x01(\x03R\fspawnerPreId\x12$\n" +
	"\rpreassignedId\x18\x02 \x01(\x03R\rpreassignedId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\x05R\tactorType\x12\x18\n" +
	"\adataBin\x18\x04 \x01(\fR\adataBin\x12\x1d\n" +
	"\x03pos\x18\x05 \x01(\v2\v.Vector3IntR\x03pos\x12\x1d\n" +
	"\x03rot\x18\x06 \x01(\v2\v.Vector3IntR\x03rot\x12\x1e\n" +
	"\n" +
	"logicState\x18\a \x01(\x05R\n" +
	"logicState\x12\x14\n" +
	"\x05state\x18\b \x01(\x05R\x05state\x12&\n" +
	"\x0etriggeredGuids\x18\t \x03(\x03R\x0etriggeredGuids\x12\x19\n" +
	"\bext_data\x18\n" +
	" \x01(\fR\aextData\x12\x1b\n" +
	"\tconfig_id\x18\v \x01(\x03R\bconfigId\x120\n" +
	"\x14custom_interact_type\x18\f \x01(\x05R\x12customInteractType\"\x91\x01\n" +
	"\rTempAvatarBin\x12\"\n" +
	"\favatarConfId\x18\x01 \x01(\x03R\favatarConfId\x12$\n" +
	"\rownerPlayerId\x18\x02 \x01(\x03R\rownerPlayerId\x12\x16\n" +
	"\x06isJoin\x18\x03 \x01(\bR\x06isJoin\x12\x1e\n" +
	"\n" +
	"isSwitchTo\x18\x04 \x01(\bR\n" +
	"isSwitchTo\"\xfe\x01\n" +
	"\n" +
	"MonsterBin\x12\x1b\n" +
	"\tcamp_type\x18\x01 \x01(\x05R\bcampType\x12(\n" +
	"\bdlg_tags\x18\x02 \x01(\v2\r.DlgTagsProtoR\adlgTags\x127\n" +
	"\fdynamic_list\x18\x03 \x03(\v2\x14.DynamicInteractInfoR\vdynamicList\x12#\n" +
	"\rdifficulty_id\x18\x04 \x01(\x05R\fdifficultyId\x12*\n" +
	"\x11addition_tag_list\x18\x05 \x03(\x05R\x0fadditionTagList\x12\x1f\n" +
	"\vdialogue_id\x18\x06 \x01(\x03R\n" +
	"dialogueId\"4\n" +
	"\x16MonsterSquadManagerBin\x12\x1a\n" +
	"\bcurBatch\x18\x01 \x01(\x05R\bcurBatch\"'\n" +
	"\aDoorBin\x12\x1c\n" +
	"\tlockState\x18\x01 \x01(\x05R\tlockState\"]\n" +
	"\x11MonsterSpawnerBin\x12$\n" +
	"\rgenActorPreID\x18\x01 \x01(\x03R\rgenActorPreID\x12\"\n" +
	"\fcanAutoSpawn\x18\x02 \x01(\bR\fcanAutoSpawn\"8\n" +
	"\x10ObjectSpawnerBin\x12$\n" +
	"\rgenActorPreID\x18\x01 \x01(\x03R\rgenActorPreID\"6\n" +
	"\x0eTrapSpawnerBin\x12$\n" +
	"\rgenActorPreID\x18\x01 \x01(\x03R\rgenActorPreID\"\xc1\x02\n" +
	"\x0eSceneActorData\x123\n" +
	"\x06actors\x18\x01 \x03(\v2\x1b.SceneActorData.ActorsEntryR\x06actors\x12\x1c\n" +
	"\tbeginTime\x18\x02 \x01(\x03R\tbeginTime\x12Q\n" +
	"\x10actorDestroyTime\x18\x03 \x03(\v2%.SceneActorData.ActorDestroyTimeEntryR\x10actorDestroyTime\x1aD\n" +
	"\vActorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.ActorBinR\x05value:\x028\x01\x1aC\n" +
	"\x15ActorDestroyTimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\x1e\n" +
	"\x11com.game.protoGenZ\t/protoGenb\x06proto3"

var (
	file_BinServer_proto_rawDescOnce sync.Once
	file_BinServer_proto_rawDescData []byte
)

func file_BinServer_proto_rawDescGZIP() []byte {
	file_BinServer_proto_rawDescOnce.Do(func() {
		file_BinServer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BinServer_proto_rawDesc), len(file_BinServer_proto_rawDesc)))
	})
	return file_BinServer_proto_rawDescData
}

var file_BinServer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_BinServer_proto_goTypes = []any{
	(*ActorBin)(nil),               // 0: ActorBin
	(*TempAvatarBin)(nil),          // 1: TempAvatarBin
	(*MonsterBin)(nil),             // 2: MonsterBin
	(*MonsterSquadManagerBin)(nil), // 3: MonsterSquadManagerBin
	(*DoorBin)(nil),                // 4: DoorBin
	(*MonsterSpawnerBin)(nil),      // 5: MonsterSpawnerBin
	(*ObjectSpawnerBin)(nil),       // 6: ObjectSpawnerBin
	(*TrapSpawnerBin)(nil),         // 7: TrapSpawnerBin
	(*SceneActorData)(nil),         // 8: SceneActorData
	nil,                            // 9: SceneActorData.ActorsEntry
	nil,                            // 10: SceneActorData.ActorDestroyTimeEntry
	(*Vector3Int)(nil),             // 11: Vector3Int
	(*DlgTagsProto)(nil),           // 12: DlgTagsProto
	(*DynamicInteractInfo)(nil),    // 13: DynamicInteractInfo
}
var file_BinServer_proto_depIdxs = []int32{
	11, // 0: ActorBin.pos:type_name -> Vector3Int
	11, // 1: ActorBin.rot:type_name -> Vector3Int
	12, // 2: MonsterBin.dlg_tags:type_name -> DlgTagsProto
	13, // 3: MonsterBin.dynamic_list:type_name -> DynamicInteractInfo
	9,  // 4: SceneActorData.actors:type_name -> SceneActorData.ActorsEntry
	10, // 5: SceneActorData.actorDestroyTime:type_name -> SceneActorData.ActorDestroyTimeEntry
	0,  // 6: SceneActorData.ActorsEntry.value:type_name -> ActorBin
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_BinServer_proto_init() }
func file_BinServer_proto_init() {
	if File_BinServer_proto != nil {
		return
	}
	file_ProtoCommon_proto_init()
	file_ProtoSceneObjs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BinServer_proto_rawDesc), len(file_BinServer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BinServer_proto_goTypes,
		DependencyIndexes: file_BinServer_proto_depIdxs,
		MessageInfos:      file_BinServer_proto_msgTypes,
	}.Build()
	File_BinServer_proto = out.File
	file_BinServer_proto_goTypes = nil
	file_BinServer_proto_depIdxs = nil
}
