// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: ProtoSceneObjs.proto

package protoGen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运动状态
type MotionState int32

const (
	MotionState_MOTION_NONE                     MotionState = 0
	MotionState_MOTION_WALK                     MotionState = 1  // 走
	MotionState_MOTION_NAV_WALK                 MotionState = 2  // 走
	MotionState_MOTION_FALLING                  MotionState = 3  // 掉落
	MotionState_MOTION_SWIM_MOVE                MotionState = 4  // 游泳移动
	MotionState_MOTION_FLY                      MotionState = 5  // 飞行
	MotionState_MOTION_CUSTOM                   MotionState = 6  // 自定义
	MotionState_MOTION_UE_MAX                   MotionState = 7  // 无效值
	MotionState_MOTION_RESET                    MotionState = 8  // 重置,用来强行矫正玩家的LastValidPoint
	MotionState_MOTION_STANDBY                  MotionState = 9  // 待机
	MotionState_MOTION_STANDBY_MOVE             MotionState = 10 // 待机移动
	MotionState_MOTION_RUN                      MotionState = 11 // 跑
	MotionState_MOTION_DASH                     MotionState = 12 // 冲刺
	MotionState_MOTION_CLIMB                    MotionState = 13 // 攀爬
	MotionState_MOTION_CLIMB_JUMP               MotionState = 14 // 攀爬跳跃
	MotionState_MOTION_STANDBY_TO_CLIMB         MotionState = 15 // 待机到攀爬
	MotionState_MOTION_FIGHT                    MotionState = 16 // 战斗
	MotionState_MOTION_JUMP                     MotionState = 17 // 跳
	MotionState_MOTION_SWIM_IDLE                MotionState = 18 // 游泳待机
	MotionState_MOTION_SWIM_DASH                MotionState = 19 // 游泳猛冲
	MotionState_MOTION_SWIM_JUMP                MotionState = 20 // 游泳跳跃
	MotionState_MOTION_SLIP                     MotionState = 21 // 下滑
	MotionState_MOTION_GO_UPSTAIRS              MotionState = 22 // 上下梯子
	MotionState_MOTION_FALL_ON_GROUND           MotionState = 23 // 掉到地上
	MotionState_MOTION_JUMP_UP_WALL_FOR_STANDBY MotionState = 24 // 待机上墙
	MotionState_MOTION_JUMP_OFF_WALL            MotionState = 25 // 跳下墙
	MotionState_MOTION_POWERED_FLY              MotionState = 26 // 动力飞行
	MotionState_MOTION_LADDER_IDLE              MotionState = 27 // 梯上待机
	MotionState_MOTION_LADDER_MOVE              MotionState = 28 // 梯上移动
	MotionState_MOTION_LADDER_SLIP              MotionState = 29 // 梯上下滑
	MotionState_MOTION_STANDBY_TO_LADDER        MotionState = 30 // 待机到梯上
	MotionState_MOTION_LADDER_TO_STANDBY        MotionState = 31 // 梯上到待机
	MotionState_MOTION_DANGER_STANDBY           MotionState = 32 // 危险区域中待机
	MotionState_MOTION_DANGER_STANDBY_MOVE      MotionState = 33 // 危险区域中待机移动
	MotionState_MOTION_DANGER_WALK              MotionState = 34 // 危险区域中走
	MotionState_MOTION_DANGER_RUN               MotionState = 35 // 危险区域中跑
	MotionState_MOTION_DANGER_DASH              MotionState = 36 // 危险区域中冲刺
	MotionState_MOTION_CROUCH_IDLE              MotionState = 37 // 蹲下待机
	MotionState_MOTION_CROUCH_MOVE              MotionState = 38 // 蹲下移动
	MotionState_MOTION_CROUCH_ROLL              MotionState = 39 // 蹲下翻滚
	MotionState_MOTION_NOTIFY                   MotionState = 40 // 只通知位置时使用
	MotionState_MOTION_LAND_SPEED               MotionState = 41 // 只通知落地速度时使用
	MotionState_MOTION_MOVE_FAIL_ACK            MotionState = 42 // 移动失败确认
	MotionState_MOTION_WATERFALL                MotionState = 43 // 瀑布滑落
	MotionState_MOTION_DASH_BEFORE_SHAKE        MotionState = 44 // 冲刺前摇
	MotionState_MOTION_SIT_IDLE                 MotionState = 45 // 坐下
	MotionState_MOTION_FORCE_SET_POS            MotionState = 46 // 被顶起
	MotionState_MOTION_QUEST_FORCE_DRAG         MotionState = 47 // 任务强制拖拽
	MotionState_MOTION_FOLLOW_ROUTE             MotionState = 48 // 跟随指定路径
	MotionState_MOTION_NUM                      MotionState = 49 // 运动状态数量
)

// Enum value maps for MotionState.
var (
	MotionState_name = map[int32]string{
		0:  "MOTION_NONE",
		1:  "MOTION_WALK",
		2:  "MOTION_NAV_WALK",
		3:  "MOTION_FALLING",
		4:  "MOTION_SWIM_MOVE",
		5:  "MOTION_FLY",
		6:  "MOTION_CUSTOM",
		7:  "MOTION_UE_MAX",
		8:  "MOTION_RESET",
		9:  "MOTION_STANDBY",
		10: "MOTION_STANDBY_MOVE",
		11: "MOTION_RUN",
		12: "MOTION_DASH",
		13: "MOTION_CLIMB",
		14: "MOTION_CLIMB_JUMP",
		15: "MOTION_STANDBY_TO_CLIMB",
		16: "MOTION_FIGHT",
		17: "MOTION_JUMP",
		18: "MOTION_SWIM_IDLE",
		19: "MOTION_SWIM_DASH",
		20: "MOTION_SWIM_JUMP",
		21: "MOTION_SLIP",
		22: "MOTION_GO_UPSTAIRS",
		23: "MOTION_FALL_ON_GROUND",
		24: "MOTION_JUMP_UP_WALL_FOR_STANDBY",
		25: "MOTION_JUMP_OFF_WALL",
		26: "MOTION_POWERED_FLY",
		27: "MOTION_LADDER_IDLE",
		28: "MOTION_LADDER_MOVE",
		29: "MOTION_LADDER_SLIP",
		30: "MOTION_STANDBY_TO_LADDER",
		31: "MOTION_LADDER_TO_STANDBY",
		32: "MOTION_DANGER_STANDBY",
		33: "MOTION_DANGER_STANDBY_MOVE",
		34: "MOTION_DANGER_WALK",
		35: "MOTION_DANGER_RUN",
		36: "MOTION_DANGER_DASH",
		37: "MOTION_CROUCH_IDLE",
		38: "MOTION_CROUCH_MOVE",
		39: "MOTION_CROUCH_ROLL",
		40: "MOTION_NOTIFY",
		41: "MOTION_LAND_SPEED",
		42: "MOTION_MOVE_FAIL_ACK",
		43: "MOTION_WATERFALL",
		44: "MOTION_DASH_BEFORE_SHAKE",
		45: "MOTION_SIT_IDLE",
		46: "MOTION_FORCE_SET_POS",
		47: "MOTION_QUEST_FORCE_DRAG",
		48: "MOTION_FOLLOW_ROUTE",
		49: "MOTION_NUM",
	}
	MotionState_value = map[string]int32{
		"MOTION_NONE":                     0,
		"MOTION_WALK":                     1,
		"MOTION_NAV_WALK":                 2,
		"MOTION_FALLING":                  3,
		"MOTION_SWIM_MOVE":                4,
		"MOTION_FLY":                      5,
		"MOTION_CUSTOM":                   6,
		"MOTION_UE_MAX":                   7,
		"MOTION_RESET":                    8,
		"MOTION_STANDBY":                  9,
		"MOTION_STANDBY_MOVE":             10,
		"MOTION_RUN":                      11,
		"MOTION_DASH":                     12,
		"MOTION_CLIMB":                    13,
		"MOTION_CLIMB_JUMP":               14,
		"MOTION_STANDBY_TO_CLIMB":         15,
		"MOTION_FIGHT":                    16,
		"MOTION_JUMP":                     17,
		"MOTION_SWIM_IDLE":                18,
		"MOTION_SWIM_DASH":                19,
		"MOTION_SWIM_JUMP":                20,
		"MOTION_SLIP":                     21,
		"MOTION_GO_UPSTAIRS":              22,
		"MOTION_FALL_ON_GROUND":           23,
		"MOTION_JUMP_UP_WALL_FOR_STANDBY": 24,
		"MOTION_JUMP_OFF_WALL":            25,
		"MOTION_POWERED_FLY":              26,
		"MOTION_LADDER_IDLE":              27,
		"MOTION_LADDER_MOVE":              28,
		"MOTION_LADDER_SLIP":              29,
		"MOTION_STANDBY_TO_LADDER":        30,
		"MOTION_LADDER_TO_STANDBY":        31,
		"MOTION_DANGER_STANDBY":           32,
		"MOTION_DANGER_STANDBY_MOVE":      33,
		"MOTION_DANGER_WALK":              34,
		"MOTION_DANGER_RUN":               35,
		"MOTION_DANGER_DASH":              36,
		"MOTION_CROUCH_IDLE":              37,
		"MOTION_CROUCH_MOVE":              38,
		"MOTION_CROUCH_ROLL":              39,
		"MOTION_NOTIFY":                   40,
		"MOTION_LAND_SPEED":               41,
		"MOTION_MOVE_FAIL_ACK":            42,
		"MOTION_WATERFALL":                43,
		"MOTION_DASH_BEFORE_SHAKE":        44,
		"MOTION_SIT_IDLE":                 45,
		"MOTION_FORCE_SET_POS":            46,
		"MOTION_QUEST_FORCE_DRAG":         47,
		"MOTION_FOLLOW_ROUTE":             48,
		"MOTION_NUM":                      49,
	}
)

func (x MotionState) Enum() *MotionState {
	p := new(MotionState)
	*p = x
	return p
}

func (x MotionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotionState) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[0].Descriptor()
}

func (MotionState) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[0]
}

func (x MotionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotionState.Descriptor instead.
func (MotionState) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{0}
}

type EnterReason int32

const (
	EnterReason_ENTER_REASON_NONE               EnterReason = 0
	EnterReason_ENTER_REASON_LOGIN              EnterReason = 1  // 登录时进入场景
	EnterReason_ENTER_REASON_BACK               EnterReason = 2  // 玩家回到自己的世界
	EnterReason_ENTER_REASON_GM                 EnterReason = 21 // GM指令
	EnterReason_ENTER_REASON_LEVEL_QUEST_TRANS  EnterReason = 30 //关卡任务传送
	EnterReason_ENTER_REASON_QUEST_ROLLBACK     EnterReason = 31 // 任务回滚
	EnterReason_ENTER_REASON_TRANS_POINT        EnterReason = 42 // 地图传送点
	EnterReason_ENTER_REASON_CLIENT_TRANSMIT    EnterReason = 43 // 客户端发起的传送
	EnterReason_ENTER_REASON_TEAM_KICK          EnterReason = 51 // 联机被踢出其他人的世界
	EnterReason_ENTER_REASON_TEAM_JOIN          EnterReason = 52 // 联机进入其他人的世界
	EnterReason_ENTER_REASON_TEAM_BACK          EnterReason = 53 // 联机回到自己的世界
	EnterReason_ENTER_REASON_ENTER_HOME         EnterReason = 64 // 进入家园
	EnterReason_ENTER_REASON_EXIT_HOME          EnterReason = 65 // 离开家园
	EnterReason_ENTER_REASON_CHANGE_HOME_MODULE EnterReason = 66 // 改变家园模组
	EnterReason_ENTER_REASON_GALLERY            EnterReason = 67 // 小游戏传送
	EnterReason_ENTER_REASON_HOME_SCENE_JUMP    EnterReason = 68 // 家园室外、室内切换
	EnterReason_ENTER_REASON_HIDE_AND_SEEK      EnterReason = 69 // 躲猫猫
	EnterReason_ENTER_REASON_ENTER_MAZE_NODE    EnterReason = 70 // 进入深渊节点
	EnterReason_ENTER_REASON_EXIT_MAZE_NODE     EnterReason = 71 // 离开深渊节点
)

// Enum value maps for EnterReason.
var (
	EnterReason_name = map[int32]string{
		0:  "ENTER_REASON_NONE",
		1:  "ENTER_REASON_LOGIN",
		2:  "ENTER_REASON_BACK",
		21: "ENTER_REASON_GM",
		30: "ENTER_REASON_LEVEL_QUEST_TRANS",
		31: "ENTER_REASON_QUEST_ROLLBACK",
		42: "ENTER_REASON_TRANS_POINT",
		43: "ENTER_REASON_CLIENT_TRANSMIT",
		51: "ENTER_REASON_TEAM_KICK",
		52: "ENTER_REASON_TEAM_JOIN",
		53: "ENTER_REASON_TEAM_BACK",
		64: "ENTER_REASON_ENTER_HOME",
		65: "ENTER_REASON_EXIT_HOME",
		66: "ENTER_REASON_CHANGE_HOME_MODULE",
		67: "ENTER_REASON_GALLERY",
		68: "ENTER_REASON_HOME_SCENE_JUMP",
		69: "ENTER_REASON_HIDE_AND_SEEK",
		70: "ENTER_REASON_ENTER_MAZE_NODE",
		71: "ENTER_REASON_EXIT_MAZE_NODE",
	}
	EnterReason_value = map[string]int32{
		"ENTER_REASON_NONE":               0,
		"ENTER_REASON_LOGIN":              1,
		"ENTER_REASON_BACK":               2,
		"ENTER_REASON_GM":                 21,
		"ENTER_REASON_LEVEL_QUEST_TRANS":  30,
		"ENTER_REASON_QUEST_ROLLBACK":     31,
		"ENTER_REASON_TRANS_POINT":        42,
		"ENTER_REASON_CLIENT_TRANSMIT":    43,
		"ENTER_REASON_TEAM_KICK":          51,
		"ENTER_REASON_TEAM_JOIN":          52,
		"ENTER_REASON_TEAM_BACK":          53,
		"ENTER_REASON_ENTER_HOME":         64,
		"ENTER_REASON_EXIT_HOME":          65,
		"ENTER_REASON_CHANGE_HOME_MODULE": 66,
		"ENTER_REASON_GALLERY":            67,
		"ENTER_REASON_HOME_SCENE_JUMP":    68,
		"ENTER_REASON_HIDE_AND_SEEK":      69,
		"ENTER_REASON_ENTER_MAZE_NODE":    70,
		"ENTER_REASON_EXIT_MAZE_NODE":     71,
	}
)

func (x EnterReason) Enum() *EnterReason {
	p := new(EnterReason)
	*p = x
	return p
}

func (x EnterReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnterReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[1].Descriptor()
}

func (EnterReason) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[1]
}

func (x EnterReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnterReason.Descriptor instead.
func (EnterReason) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{1}
}

type VisionType int32

const (
	VisionType_VISION_NONE            VisionType = 0
	VisionType_VISION_MEET            VisionType = 1  // 出现(进入视野)
	VisionType_VISION_REBORN          VisionType = 2  // 重生
	VisionType_VISION_REPLACE         VisionType = 3  // 主动更换
	VisionType_VISION_WAYPOINT_REBORN VisionType = 4  // 副本路点重生
	VisionType_VISION_MISS            VisionType = 5  // 消失(离开视野)
	VisionType_VISION_DIE             VisionType = 6  // 死亡
	VisionType_VISION_GATHER_ESCAPE   VisionType = 7  // 目前只用于环境小动物采集时逃走
	VisionType_VISION_REFRESH         VisionType = 8  // group刷新导致物件消失(TODO...暂且不会发给客户端)
	VisionType_VISION_TRANSPORT       VisionType = 9  // 在同一个场景内传送
	VisionType_VISION_REPLACE_DIE     VisionType = 10 // 客户端需要区分死亡换人和主动换人
	VisionType_VISION_REPLACE_SERVER  VisionType = 11 // 服务器主动发起的换人,比如任务节点触发 与队伍更新公用
	VisionType_VISION_BORN            VisionType = 12 // entityAppear()的默认情况
	VisionType_VISION_PICKUP          VisionType = 13 // 拾取
	VisionType_VISION_REMOVE          VisionType = 14 // LD无声息移除entity
	VisionType_VISION_DE_ACTIVE       VisionType = 15 // 机关DeActive
)

// Enum value maps for VisionType.
var (
	VisionType_name = map[int32]string{
		0:  "VISION_NONE",
		1:  "VISION_MEET",
		2:  "VISION_REBORN",
		3:  "VISION_REPLACE",
		4:  "VISION_WAYPOINT_REBORN",
		5:  "VISION_MISS",
		6:  "VISION_DIE",
		7:  "VISION_GATHER_ESCAPE",
		8:  "VISION_REFRESH",
		9:  "VISION_TRANSPORT",
		10: "VISION_REPLACE_DIE",
		11: "VISION_REPLACE_SERVER",
		12: "VISION_BORN",
		13: "VISION_PICKUP",
		14: "VISION_REMOVE",
		15: "VISION_DE_ACTIVE",
	}
	VisionType_value = map[string]int32{
		"VISION_NONE":            0,
		"VISION_MEET":            1,
		"VISION_REBORN":          2,
		"VISION_REPLACE":         3,
		"VISION_WAYPOINT_REBORN": 4,
		"VISION_MISS":            5,
		"VISION_DIE":             6,
		"VISION_GATHER_ESCAPE":   7,
		"VISION_REFRESH":         8,
		"VISION_TRANSPORT":       9,
		"VISION_REPLACE_DIE":     10,
		"VISION_REPLACE_SERVER":  11,
		"VISION_BORN":            12,
		"VISION_PICKUP":          13,
		"VISION_REMOVE":          14,
		"VISION_DE_ACTIVE":       15,
	}
)

func (x VisionType) Enum() *VisionType {
	p := new(VisionType)
	*p = x
	return p
}

func (x VisionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[2].Descriptor()
}

func (VisionType) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[2]
}

func (x VisionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisionType.Descriptor instead.
func (VisionType) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{2}
}

type GroupVisionType int32

const (
	GroupVisionType_GVT_ALWAYS_SHOW GroupVisionType = 0
	GroupVisionType_GVT_DEFAULT     GroupVisionType = 1
)

// Enum value maps for GroupVisionType.
var (
	GroupVisionType_name = map[int32]string{
		0: "GVT_ALWAYS_SHOW",
		1: "GVT_DEFAULT",
	}
	GroupVisionType_value = map[string]int32{
		"GVT_ALWAYS_SHOW": 0,
		"GVT_DEFAULT":     1,
	}
)

func (x GroupVisionType) Enum() *GroupVisionType {
	p := new(GroupVisionType)
	*p = x
	return p
}

func (x GroupVisionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupVisionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[3].Descriptor()
}

func (GroupVisionType) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[3]
}

func (x GroupVisionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupVisionType.Descriptor instead.
func (GroupVisionType) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{3}
}

// 跳点类型
type EntityJumpType int32

const (
	EntityJumpType_EJT_NONE    EntityJumpType = 0
	EntityJumpType_EJT_ACTIVE  EntityJumpType = 1 // 主动跳点
	EntityJumpType_EJT_PASSIVE EntityJumpType = 2 // 被动跳点
)

// Enum value maps for EntityJumpType.
var (
	EntityJumpType_name = map[int32]string{
		0: "EJT_NONE",
		1: "EJT_ACTIVE",
		2: "EJT_PASSIVE",
	}
	EntityJumpType_value = map[string]int32{
		"EJT_NONE":    0,
		"EJT_ACTIVE":  1,
		"EJT_PASSIVE": 2,
	}
)

func (x EntityJumpType) Enum() *EntityJumpType {
	p := new(EntityJumpType)
	*p = x
	return p
}

func (x EntityJumpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityJumpType) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[4].Descriptor()
}

func (EntityJumpType) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[4]
}

func (x EntityJumpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityJumpType.Descriptor instead.
func (EntityJumpType) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{4}
}

// 传送原因
type TeleportReason int32

const (
	TeleportReason_TELEPORT_NONE           TeleportReason = 0
	TeleportReason_TELEPORT_LEVEL_QUEST    TeleportReason = 1 //关卡节点
	TeleportReason_TELEPORT_AVATAR_RE_BORN TeleportReason = 2 //单角色重生传送
	TeleportReason_TELEPORT_TEAM_RE_BORN   TeleportReason = 3 //小队重生传送
	TeleportReason_TELEPORT_BIGMAP         TeleportReason = 4 //大地图传送功能
	TeleportReason_TELEPORT_ACTOR          TeleportReason = 5 //传送门
	TeleportReason_TELEPORT_STUCK_RESET    TeleportReason = 6 //卡死重置
)

// Enum value maps for TeleportReason.
var (
	TeleportReason_name = map[int32]string{
		0: "TELEPORT_NONE",
		1: "TELEPORT_LEVEL_QUEST",
		2: "TELEPORT_AVATAR_RE_BORN",
		3: "TELEPORT_TEAM_RE_BORN",
		4: "TELEPORT_BIGMAP",
		5: "TELEPORT_ACTOR",
		6: "TELEPORT_STUCK_RESET",
	}
	TeleportReason_value = map[string]int32{
		"TELEPORT_NONE":           0,
		"TELEPORT_LEVEL_QUEST":    1,
		"TELEPORT_AVATAR_RE_BORN": 2,
		"TELEPORT_TEAM_RE_BORN":   3,
		"TELEPORT_BIGMAP":         4,
		"TELEPORT_ACTOR":          5,
		"TELEPORT_STUCK_RESET":    6,
	}
)

func (x TeleportReason) Enum() *TeleportReason {
	p := new(TeleportReason)
	*p = x
	return p
}

func (x TeleportReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeleportReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[5].Descriptor()
}

func (TeleportReason) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[5]
}

func (x TeleportReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeleportReason.Descriptor instead.
func (TeleportReason) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{5}
}

// 重生原因
type ReBornReason int32

const (
	ReBornReason_REASON_NONE              ReBornReason = 0
	ReBornReason_REASON_AVATAR_ALL_DEAD   ReBornReason = 1 //小队死亡重生
	ReBornReason_REASON_AVATAR_JUMP_CLIFF ReBornReason = 2 //跳崖重生
	ReBornReason_REASON_REBORN_AREA       ReBornReason = 3 //重生区域
	ReBornReason_REASON_FLOW_KILL         ReBornReason = 4 //游戏流程删除
	ReBornReason_REASON_REST_POINT        ReBornReason = 5 //坐火重生
	ReBornReason_REASON_VISUAL_REBORN     ReBornReason = 6 //visual重生
	ReBornReason_REASON_FOOD_REBORN       ReBornReason = 7 //食物重生
)

// Enum value maps for ReBornReason.
var (
	ReBornReason_name = map[int32]string{
		0: "REASON_NONE",
		1: "REASON_AVATAR_ALL_DEAD",
		2: "REASON_AVATAR_JUMP_CLIFF",
		3: "REASON_REBORN_AREA",
		4: "REASON_FLOW_KILL",
		5: "REASON_REST_POINT",
		6: "REASON_VISUAL_REBORN",
		7: "REASON_FOOD_REBORN",
	}
	ReBornReason_value = map[string]int32{
		"REASON_NONE":              0,
		"REASON_AVATAR_ALL_DEAD":   1,
		"REASON_AVATAR_JUMP_CLIFF": 2,
		"REASON_REBORN_AREA":       3,
		"REASON_FLOW_KILL":         4,
		"REASON_REST_POINT":        5,
		"REASON_VISUAL_REBORN":     6,
		"REASON_FOOD_REBORN":       7,
	}
)

func (x ReBornReason) Enum() *ReBornReason {
	p := new(ReBornReason)
	*p = x
	return p
}

func (x ReBornReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReBornReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[6].Descriptor()
}

func (ReBornReason) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[6]
}

func (x ReBornReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReBornReason.Descriptor instead.
func (ReBornReason) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{6}
}

// 运动包的状态(预测用)
type MotionPacketState int32

const (
	MotionPacketState_PACKET_MOVE     MotionPacketState = 0 //移动
	MotionPacketState_PACKET_MOVE_END MotionPacketState = 1 //移动结束
)

// Enum value maps for MotionPacketState.
var (
	MotionPacketState_name = map[int32]string{
		0: "PACKET_MOVE",
		1: "PACKET_MOVE_END",
	}
	MotionPacketState_value = map[string]int32{
		"PACKET_MOVE":     0,
		"PACKET_MOVE_END": 1,
	}
)

func (x MotionPacketState) Enum() *MotionPacketState {
	p := new(MotionPacketState)
	*p = x
	return p
}

func (x MotionPacketState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotionPacketState) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[7].Descriptor()
}

func (MotionPacketState) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[7]
}

func (x MotionPacketState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotionPacketState.Descriptor instead.
func (MotionPacketState) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{7}
}

type DynamicInteractType int32

const (
	DynamicInteractType_PLAY_AVG       DynamicInteractType = 0 //ACG
	DynamicInteractType_PLAY_NARRATIVE DynamicInteractType = 1 //旁白
)

// Enum value maps for DynamicInteractType.
var (
	DynamicInteractType_name = map[int32]string{
		0: "PLAY_AVG",
		1: "PLAY_NARRATIVE",
	}
	DynamicInteractType_value = map[string]int32{
		"PLAY_AVG":       0,
		"PLAY_NARRATIVE": 1,
	}
)

func (x DynamicInteractType) Enum() *DynamicInteractType {
	p := new(DynamicInteractType)
	*p = x
	return p
}

func (x DynamicInteractType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DynamicInteractType) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoSceneObjs_proto_enumTypes[8].Descriptor()
}

func (DynamicInteractType) Type() protoreflect.EnumType {
	return &file_ProtoSceneObjs_proto_enumTypes[8]
}

func (x DynamicInteractType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DynamicInteractType.Descriptor instead.
func (DynamicInteractType) EnumDescriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{8}
}

// ================================ 场景 物件基本信息（状态的变更）=============
// 场景上的实体信息
type SceneEntityBase struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EntityId          int64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`                // entity id
	CnfId             int64                  `protobuf:"varint,2,opt,name=cnf_id,json=cnfId,proto3" json:"cnf_id,omitempty"`                         // actor config id
	OwnerId           int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                   // owner player id 所属玩家id
	HostId            int64                  `protobuf:"varint,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                      // host player id 该实体的host主机的玩家id
	PreassignedId     int64                  `protobuf:"varint,5,opt,name=preassigned_id,json=preassignedId,proto3" json:"preassigned_id,omitempty"` //编辑器预分配的实例ID
	Pos               *Vector3Int            `protobuf:"bytes,6,opt,name=pos,proto3" json:"pos,omitempty"`
	Rot               *Vector3Int            `protobuf:"bytes,7,opt,name=rot,proto3" json:"rot,omitempty"`
	EntityType        int32                  `protobuf:"varint,9,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                         // 实体类型,对应scene_object.xlsx的ActorType
	ObjectState       int32                  `protobuf:"varint,10,opt,name=object_state,json=objectState,proto3" json:"object_state,omitempty"`                     //物件的状态,对应各自物件的枚举类型
	SpawnerSystemGuid int64                  `protobuf:"varint,11,opt,name=spawner_system_guid,json=spawnerSystemGuid,proto3" json:"spawner_system_guid,omitempty"` //生成器的System_GUID
	LogicState        int32                  `protobuf:"varint,12,opt,name=logic_state,json=logicState,proto3" json:"logic_state,omitempty"`                        //位标志的复合值，对应LevelLogicState.IsActivated|CanInteract|IsLocked
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SceneEntityBase) Reset() {
	*x = SceneEntityBase{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneEntityBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEntityBase) ProtoMessage() {}

func (x *SceneEntityBase) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEntityBase.ProtoReflect.Descriptor instead.
func (*SceneEntityBase) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{0}
}

func (x *SceneEntityBase) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SceneEntityBase) GetCnfId() int64 {
	if x != nil {
		return x.CnfId
	}
	return 0
}

func (x *SceneEntityBase) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *SceneEntityBase) GetHostId() int64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *SceneEntityBase) GetPreassignedId() int64 {
	if x != nil {
		return x.PreassignedId
	}
	return 0
}

func (x *SceneEntityBase) GetPos() *Vector3Int {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SceneEntityBase) GetRot() *Vector3Int {
	if x != nil {
		return x.Rot
	}
	return nil
}

func (x *SceneEntityBase) GetEntityType() int32 {
	if x != nil {
		return x.EntityType
	}
	return 0
}

func (x *SceneEntityBase) GetObjectState() int32 {
	if x != nil {
		return x.ObjectState
	}
	return 0
}

func (x *SceneEntityBase) GetSpawnerSystemGuid() int64 {
	if x != nil {
		return x.SpawnerSystemGuid
	}
	return 0
}

func (x *SceneEntityBase) GetLogicState() int32 {
	if x != nil {
		return x.LogicState
	}
	return 0
}

type SceneEntityInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseData         *SceneEntityBase       `protobuf:"bytes,1,opt,name=base_data,json=baseData,proto3" json:"base_data,omitempty"`
	EntityData       []byte                 `protobuf:"bytes,2,opt,name=entity_data,json=entityData,proto3" json:"entity_data,omitempty"`
	BattleInfo       *EntityBattleInfo      `protobuf:"bytes,3,opt,name=battle_info,json=battleInfo,proto3" json:"battle_info,omitempty"`                      //战斗相关 包括 基本属性，技能, BUFF 相关
	RoleInfo         *RoleSummaryInfo       `protobuf:"bytes,4,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`                            //实体所属的玩家简略信息,只有在需要显示玩家数据的实体上携带数据,比如Avatar
	BuffUidStart     int64                  `protobuf:"varint,5,opt,name=buff_uid_start,json=buffUidStart,proto3" json:"buff_uid_start,omitempty"`             // buff uid  起始位值
	RandomStartIndex int32                  `protobuf:"varint,6,opt,name=random_start_index,json=randomStartIndex,proto3" json:"random_start_index,omitempty"` // random table index
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SceneEntityInfo) Reset() {
	*x = SceneEntityInfo{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneEntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEntityInfo) ProtoMessage() {}

func (x *SceneEntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEntityInfo.ProtoReflect.Descriptor instead.
func (*SceneEntityInfo) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{1}
}

func (x *SceneEntityInfo) GetBaseData() *SceneEntityBase {
	if x != nil {
		return x.BaseData
	}
	return nil
}

func (x *SceneEntityInfo) GetEntityData() []byte {
	if x != nil {
		return x.EntityData
	}
	return nil
}

func (x *SceneEntityInfo) GetBattleInfo() *EntityBattleInfo {
	if x != nil {
		return x.BattleInfo
	}
	return nil
}

func (x *SceneEntityInfo) GetRoleInfo() *RoleSummaryInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

func (x *SceneEntityInfo) GetBuffUidStart() int64 {
	if x != nil {
		return x.BuffUidStart
	}
	return 0
}

func (x *SceneEntityInfo) GetRandomStartIndex() int32 {
	if x != nil {
		return x.RandomStartIndex
	}
	return 0
}

type SceneEntityHostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // entity id
	HostId        int64                  `protobuf:"varint,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`       // host player id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneEntityHostInfo) Reset() {
	*x = SceneEntityHostInfo{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneEntityHostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEntityHostInfo) ProtoMessage() {}

func (x *SceneEntityHostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEntityHostInfo.ProtoReflect.Descriptor instead.
func (*SceneEntityHostInfo) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{2}
}

func (x *SceneEntityHostInfo) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SceneEntityHostInfo) GetHostId() int64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

// 玩家的位置信息
type PlayerLocationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // UID
	Pos           *Vector3Int            `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`  // 位置
	Rot           *Vector3Int            `protobuf:"bytes,3,opt,name=rot,proto3" json:"rot,omitempty"`  // 朝向
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLocationInfo) Reset() {
	*x = PlayerLocationInfo{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLocationInfo) ProtoMessage() {}

func (x *PlayerLocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLocationInfo.ProtoReflect.Descriptor instead.
func (*PlayerLocationInfo) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLocationInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerLocationInfo) GetPos() *Vector3Int {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlayerLocationInfo) GetRot() *Vector3Int {
	if x != nil {
		return x.Rot
	}
	return nil
}

// 运动信息
type MotionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Vector3Int            `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`                       // 位置
	Rot           *Vector3Int            `protobuf:"bytes,2,opt,name=rot,proto3" json:"rot,omitempty"`                       // 旋转
	Speed         *Vector3Int            `protobuf:"bytes,3,opt,name=speed,proto3" json:"speed,omitempty"`                   // 速度
	State         MotionState            `protobuf:"varint,4,opt,name=state,proto3,enum=MotionState" json:"state,omitempty"` // 状态
	SceneTime     int64                  `protobuf:"varint,5,opt,name=scene_time,json=sceneTime,proto3" json:"scene_time,omitempty"`
	MaxSpeed      float32                `protobuf:"fixed32,6,opt,name=max_speed,json=maxSpeed,proto3" json:"max_speed,omitempty"`
	Acceleration  *Vector3Int            `protobuf:"bytes,7,opt,name=acceleration,proto3" json:"acceleration,omitempty"`                                          //加速度
	PacketState   MotionPacketState      `protobuf:"varint,8,opt,name=packet_state,json=packetState,proto3,enum=MotionPacketState" json:"packet_state,omitempty"` //运动包的状态（预测用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotionInfo) Reset() {
	*x = MotionInfo{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotionInfo) ProtoMessage() {}

func (x *MotionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotionInfo.ProtoReflect.Descriptor instead.
func (*MotionInfo) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{4}
}

func (x *MotionInfo) GetPos() *Vector3Int {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *MotionInfo) GetRot() *Vector3Int {
	if x != nil {
		return x.Rot
	}
	return nil
}

func (x *MotionInfo) GetSpeed() *Vector3Int {
	if x != nil {
		return x.Speed
	}
	return nil
}

func (x *MotionInfo) GetState() MotionState {
	if x != nil {
		return x.State
	}
	return MotionState_MOTION_NONE
}

func (x *MotionInfo) GetSceneTime() int64 {
	if x != nil {
		return x.SceneTime
	}
	return 0
}

func (x *MotionInfo) GetMaxSpeed() float32 {
	if x != nil {
		return x.MaxSpeed
	}
	return 0
}

func (x *MotionInfo) GetAcceleration() *Vector3Int {
	if x != nil {
		return x.Acceleration
	}
	return nil
}

func (x *MotionInfo) GetPacketState() MotionPacketState {
	if x != nil {
		return x.PacketState
	}
	return MotionPacketState_PACKET_MOVE
}

type DlgTagProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DlgId         int64                  `protobuf:"varint,1,opt,name=dlg_id,json=dlgId,proto3" json:"dlg_id,omitempty"`
	LinkId        int64                  `protobuf:"varint,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlgTagProto) Reset() {
	*x = DlgTagProto{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlgTagProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlgTagProto) ProtoMessage() {}

func (x *DlgTagProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlgTagProto.ProtoReflect.Descriptor instead.
func (*DlgTagProto) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{5}
}

func (x *DlgTagProto) GetDlgId() int64 {
	if x != nil {
		return x.DlgId
	}
	return 0
}

func (x *DlgTagProto) GetLinkId() int64 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

func (x *DlgTagProto) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type DlgTagsProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*DlgTagProto         `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlgTagsProto) Reset() {
	*x = DlgTagsProto{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlgTagsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlgTagsProto) ProtoMessage() {}

func (x *DlgTagsProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlgTagsProto.ProtoReflect.Descriptor instead.
func (*DlgTagsProto) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{6}
}

func (x *DlgTagsProto) GetTags() []*DlgTagProto {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 动态交互选项
type DynamicInteractInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DynamicInteractType    `protobuf:"varint,1,opt,name=type,proto3,enum=DynamicInteractType" json:"type,omitempty"` //类型
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	ParamList     []string               `protobuf:"bytes,3,rep,name=param_list,json=paramList,proto3" json:"param_list,omitempty"`                       //参数列表
	LongParamList []int64                `protobuf:"varint,4,rep,packed,name=long_param_list,json=longParamList,proto3" json:"long_param_list,omitempty"` //long参数列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicInteractInfo) Reset() {
	*x = DynamicInteractInfo{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicInteractInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicInteractInfo) ProtoMessage() {}

func (x *DynamicInteractInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicInteractInfo.ProtoReflect.Descriptor instead.
func (*DynamicInteractInfo) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{7}
}

func (x *DynamicInteractInfo) GetType() DynamicInteractType {
	if x != nil {
		return x.Type
	}
	return DynamicInteractType_PLAY_AVG
}

func (x *DynamicInteractInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DynamicInteractInfo) GetParamList() []string {
	if x != nil {
		return x.ParamList
	}
	return nil
}

func (x *DynamicInteractInfo) GetLongParamList() []int64 {
	if x != nil {
		return x.LongParamList
	}
	return nil
}

// ======================================   场景 actor ---------------- 结构体-------------------------
// 场景上的怪物信息
type SceneMonster struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupId           int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                                 // 组ID
	SpawnerSystemGuid int64                  `protobuf:"varint,2,opt,name=spawner_system_guid,json=spawnerSystemGuid,proto3" json:"spawner_system_guid,omitempty"` //生成器的System_GUID
	CampType          int32                  `protobuf:"varint,3,opt,name=camp_type,json=campType,proto3" json:"camp_type,omitempty"`                              //阵营
	SquadManagerId    int64                  `protobuf:"varint,4,opt,name=squad_manager_id,json=squadManagerId,proto3" json:"squad_manager_id,omitempty"`          //管理器的System_GUID
	DialogueId        int64                  `protobuf:"varint,5,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`                        //对话树Id
	DialogueTags      *DlgTagsProto          `protobuf:"bytes,6,opt,name=dialogue_tags,json=dialogueTags,proto3" json:"dialogue_tags,omitempty"`
	DynamicList       []*DynamicInteractInfo `protobuf:"bytes,7,rep,name=dynamic_list,json=dynamicList,proto3" json:"dynamic_list,omitempty"`
	Difficulty        int32                  `protobuf:"varint,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`                                //难度系数
	AdditionTags      []int32                `protobuf:"varint,9,rep,packed,name=addition_tags,json=additionTags,proto3" json:"addition_tags,omitempty"` //自定义Tag列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SceneMonster) Reset() {
	*x = SceneMonster{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneMonster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneMonster) ProtoMessage() {}

func (x *SceneMonster) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneMonster.ProtoReflect.Descriptor instead.
func (*SceneMonster) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{8}
}

func (x *SceneMonster) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SceneMonster) GetSpawnerSystemGuid() int64 {
	if x != nil {
		return x.SpawnerSystemGuid
	}
	return 0
}

func (x *SceneMonster) GetCampType() int32 {
	if x != nil {
		return x.CampType
	}
	return 0
}

func (x *SceneMonster) GetSquadManagerId() int64 {
	if x != nil {
		return x.SquadManagerId
	}
	return 0
}

func (x *SceneMonster) GetDialogueId() int64 {
	if x != nil {
		return x.DialogueId
	}
	return 0
}

func (x *SceneMonster) GetDialogueTags() *DlgTagsProto {
	if x != nil {
		return x.DialogueTags
	}
	return nil
}

func (x *SceneMonster) GetDynamicList() []*DynamicInteractInfo {
	if x != nil {
		return x.DynamicList
	}
	return nil
}

func (x *SceneMonster) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *SceneMonster) GetAdditionTags() []int32 {
	if x != nil {
		return x.AdditionTags
	}
	return nil
}

type SceneForbiddenVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FobiddenMode  int32                  `protobuf:"varint,1,opt,name=fobidden_mode,json=fobiddenMode,proto3" json:"fobidden_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneForbiddenVolume) Reset() {
	*x = SceneForbiddenVolume{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneForbiddenVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneForbiddenVolume) ProtoMessage() {}

func (x *SceneForbiddenVolume) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneForbiddenVolume.ProtoReflect.Descriptor instead.
func (*SceneForbiddenVolume) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{9}
}

func (x *SceneForbiddenVolume) GetFobiddenMode() int32 {
	if x != nil {
		return x.FobiddenMode
	}
	return 0
}

// 召唤物
type SceneSummons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      int64                  `protobuf:"varint,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"` //主人的EntityID
	CampType      int32                  `protobuf:"varint,2,opt,name=camp_type,json=campType,proto3" json:"camp_type,omitempty"` //阵营
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneSummons) Reset() {
	*x = SceneSummons{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneSummons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneSummons) ProtoMessage() {}

func (x *SceneSummons) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneSummons.ProtoReflect.Descriptor instead.
func (*SceneSummons) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{10}
}

func (x *SceneSummons) GetMasterId() int64 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *SceneSummons) GetCampType() int32 {
	if x != nil {
		return x.CampType
	}
	return 0
}

// 场景上的NPC信息
type SceneNpc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         int32                  `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	RoomId        int32                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ParentQuestId int32                  `protobuf:"varint,3,opt,name=parent_quest_id,json=parentQuestId,proto3" json:"parent_quest_id,omitempty"` // 关联的父任务id
	BlockId       int32                  `protobuf:"varint,4,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`                     // 客户端需要
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneNpc) Reset() {
	*x = SceneNpc{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneNpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneNpc) ProtoMessage() {}

func (x *SceneNpc) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneNpc.ProtoReflect.Descriptor instead.
func (*SceneNpc) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{11}
}

func (x *SceneNpc) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *SceneNpc) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SceneNpc) GetParentQuestId() int32 {
	if x != nil {
		return x.ParentQuestId
	}
	return 0
}

func (x *SceneNpc) GetBlockId() int32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

// 场景上的角色信息
type SceneAvatar struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Level           int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Exp             int32                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	ExceedId        int32                  `protobuf:"varint,3,opt,name=exceed_id,json=exceedId,proto3" json:"exceed_id,omitempty"` // 突破Id
	IsPlayerControl bool                   `protobuf:"varint,4,opt,name=is_player_control,json=isPlayerControl,proto3" json:"is_player_control,omitempty"`
	CampType        int32                  `protobuf:"varint,5,opt,name=camp_type,json=campType,proto3" json:"camp_type,omitempty"` //阵营
	LifeState       int32                  `protobuf:"varint,6,opt,name=life_state,json=lifeState,proto3" json:"life_state,omitempty"`
	SubType         int32                  `protobuf:"varint,7,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"` //Avatar的子类型,SceneAvatarSubType
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SceneAvatar) Reset() {
	*x = SceneAvatar{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneAvatar) ProtoMessage() {}

func (x *SceneAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneAvatar.ProtoReflect.Descriptor instead.
func (*SceneAvatar) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{12}
}

func (x *SceneAvatar) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SceneAvatar) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *SceneAvatar) GetExceedId() int32 {
	if x != nil {
		return x.ExceedId
	}
	return 0
}

func (x *SceneAvatar) GetIsPlayerControl() bool {
	if x != nil {
		return x.IsPlayerControl
	}
	return false
}

func (x *SceneAvatar) GetCampType() int32 {
	if x != nil {
		return x.CampType
	}
	return 0
}

func (x *SceneAvatar) GetLifeState() int32 {
	if x != nil {
		return x.LifeState
	}
	return 0
}

func (x *SceneAvatar) GetSubType() int32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

// 海巡兽炮台装置
type SceneShipMod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampType      int32                  `protobuf:"varint,1,opt,name=camp_type,json=campType,proto3" json:"camp_type,omitempty"` //阵营
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneShipMod) Reset() {
	*x = SceneShipMod{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneShipMod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneShipMod) ProtoMessage() {}

func (x *SceneShipMod) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneShipMod.ProtoReflect.Descriptor instead.
func (*SceneShipMod) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{13}
}

func (x *SceneShipMod) GetCampType() int32 {
	if x != nil {
		return x.CampType
	}
	return 0
}

// 子弹飞行物
type SceneProjectile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientProjectileId int64                  `protobuf:"varint,1,opt,name=client_projectile_id,json=clientProjectileId,proto3" json:"client_projectile_id,omitempty"` //客户端子弹唯一id
	MasterEntityId     int64                  `protobuf:"varint,2,opt,name=master_entity_id,json=masterEntityId,proto3" json:"master_entity_id,omitempty"`             //主人的EntityID，如炮弹的master是炮台
	CampType           int32                  `protobuf:"varint,3,opt,name=camp_type,json=campType,proto3" json:"camp_type,omitempty"`                                 //阵营
	Speed              *Vector3Int            `protobuf:"bytes,4,opt,name=speed,proto3" json:"speed,omitempty"`                                                        //速度
	InstancedStruct    string                 `protobuf:"bytes,5,opt,name=instanced_struct,json=instancedStruct,proto3" json:"instanced_struct,omitempty"`             //客户端透传参数
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SceneProjectile) Reset() {
	*x = SceneProjectile{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneProjectile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneProjectile) ProtoMessage() {}

func (x *SceneProjectile) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneProjectile.ProtoReflect.Descriptor instead.
func (*SceneProjectile) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{14}
}

func (x *SceneProjectile) GetClientProjectileId() int64 {
	if x != nil {
		return x.ClientProjectileId
	}
	return 0
}

func (x *SceneProjectile) GetMasterEntityId() int64 {
	if x != nil {
		return x.MasterEntityId
	}
	return 0
}

func (x *SceneProjectile) GetCampType() int32 {
	if x != nil {
		return x.CampType
	}
	return 0
}

func (x *SceneProjectile) GetSpeed() *Vector3Int {
	if x != nil {
		return x.Speed
	}
	return nil
}

func (x *SceneProjectile) GetInstancedStruct() string {
	if x != nil {
		return x.InstancedStruct
	}
	return ""
}

// 休息点
type SceneRestPoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpawnerSystemGuid int64                  `protobuf:"varint,1,opt,name=spawner_system_guid,json=spawnerSystemGuid,proto3" json:"spawner_system_guid,omitempty"` //生成器的System_GUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SceneRestPoint) Reset() {
	*x = SceneRestPoint{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneRestPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneRestPoint) ProtoMessage() {}

func (x *SceneRestPoint) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneRestPoint.ProtoReflect.Descriptor instead.
func (*SceneRestPoint) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{15}
}

func (x *SceneRestPoint) GetSpawnerSystemGuid() int64 {
	if x != nil {
		return x.SpawnerSystemGuid
	}
	return 0
}

// 门
type SceneDoor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpawnerSystemGuid int64                  `protobuf:"varint,1,opt,name=spawner_system_guid,json=spawnerSystemGuid,proto3" json:"spawner_system_guid,omitempty"` //生成器的System_GUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SceneDoor) Reset() {
	*x = SceneDoor{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneDoor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneDoor) ProtoMessage() {}

func (x *SceneDoor) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneDoor.ProtoReflect.Descriptor instead.
func (*SceneDoor) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{16}
}

func (x *SceneDoor) GetSpawnerSystemGuid() int64 {
	if x != nil {
		return x.SpawnerSystemGuid
	}
	return 0
}

// 宝箱
type SceneChest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpawnerSystemGuid int64                  `protobuf:"varint,1,opt,name=spawner_system_guid,json=spawnerSystemGuid,proto3" json:"spawner_system_guid,omitempty"` //生成器的System_GUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SceneChest) Reset() {
	*x = SceneChest{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneChest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneChest) ProtoMessage() {}

func (x *SceneChest) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneChest.ProtoReflect.Descriptor instead.
func (*SceneChest) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{17}
}

func (x *SceneChest) GetSpawnerSystemGuid() int64 {
	if x != nil {
		return x.SpawnerSystemGuid
	}
	return 0
}

// 掉落物
type ScenePickup struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpawnerSystemGuid int64                  `protobuf:"varint,1,opt,name=spawner_system_guid,json=spawnerSystemGuid,proto3" json:"spawner_system_guid,omitempty"` //生成器的System_GUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScenePickup) Reset() {
	*x = ScenePickup{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenePickup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenePickup) ProtoMessage() {}

func (x *ScenePickup) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenePickup.ProtoReflect.Descriptor instead.
func (*ScenePickup) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{18}
}

func (x *ScenePickup) GetSpawnerSystemGuid() int64 {
	if x != nil {
		return x.SpawnerSystemGuid
	}
	return 0
}

// 电梯
type SceneLift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartRunTime  int64                  `protobuf:"varint,1,opt,name=start_run_time,json=startRunTime,proto3" json:"start_run_time,omitempty"` //电梯开始运行时间(毫秒)
	FromFloor     int32                  `protobuf:"varint,2,opt,name=from_floor,json=fromFloor,proto3" json:"from_floor,omitempty"`            //起始楼层
	ToFloor       int32                  `protobuf:"varint,3,opt,name=to_floor,json=toFloor,proto3" json:"to_floor,omitempty"`                  //到达楼层
	FloorRunTime  int64                  `protobuf:"varint,4,opt,name=floor_run_time,json=floorRunTime,proto3" json:"floor_run_time,omitempty"` //电梯本次单层运行时间(毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneLift) Reset() {
	*x = SceneLift{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneLift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneLift) ProtoMessage() {}

func (x *SceneLift) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneLift.ProtoReflect.Descriptor instead.
func (*SceneLift) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{19}
}

func (x *SceneLift) GetStartRunTime() int64 {
	if x != nil {
		return x.StartRunTime
	}
	return 0
}

func (x *SceneLift) GetFromFloor() int32 {
	if x != nil {
		return x.FromFloor
	}
	return 0
}

func (x *SceneLift) GetToFloor() int32 {
	if x != nil {
		return x.ToFloor
	}
	return 0
}

func (x *SceneLift) GetFloorRunTime() int64 {
	if x != nil {
		return x.FloorRunTime
	}
	return 0
}

// 升降平台
type SceneMovingPlatform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartRunTime  int64                  `protobuf:"varint,1,opt,name=start_run_time,json=startRunTime,proto3" json:"start_run_time,omitempty"` //启动时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneMovingPlatform) Reset() {
	*x = SceneMovingPlatform{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneMovingPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneMovingPlatform) ProtoMessage() {}

func (x *SceneMovingPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneMovingPlatform.ProtoReflect.Descriptor instead.
func (*SceneMovingPlatform) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{20}
}

func (x *SceneMovingPlatform) GetStartRunTime() int64 {
	if x != nil {
		return x.StartRunTime
	}
	return 0
}

// 场景物件，目前只有状态改变，比如地板塌陷，限定区域
type SceneGadget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneGadget) Reset() {
	*x = SceneGadget{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneGadget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneGadget) ProtoMessage() {}

func (x *SceneGadget) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneGadget.ProtoReflect.Descriptor instead.
func (*SceneGadget) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{21}
}

// 传送数据
type TeleporterData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneId       int32                  `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`                       //场景Id
	TeleportList  []int64                `protobuf:"varint,2,rep,packed,name=teleport_list,json=teleportList,proto3" json:"teleport_list,omitempty"` //传送点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeleporterData) Reset() {
	*x = TeleporterData{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeleporterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleporterData) ProtoMessage() {}

func (x *TeleporterData) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleporterData.ProtoReflect.Descriptor instead.
func (*TeleporterData) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{22}
}

func (x *TeleporterData) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *TeleporterData) GetTeleportList() []int64 {
	if x != nil {
		return x.TeleportList
	}
	return nil
}

// 传送门
type SceneTeleporter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []*TeleporterData      `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"` //传送数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneTeleporter) Reset() {
	*x = SceneTeleporter{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneTeleporter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneTeleporter) ProtoMessage() {}

func (x *SceneTeleporter) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneTeleporter.ProtoReflect.Descriptor instead.
func (*SceneTeleporter) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{23}
}

func (x *SceneTeleporter) GetDatas() []*TeleporterData {
	if x != nil {
		return x.Datas
	}
	return nil
}

// 随机岛礁
type SceneRandomIsland struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneRandomIsland) Reset() {
	*x = SceneRandomIsland{}
	mi := &file_ProtoSceneObjs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneRandomIsland) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneRandomIsland) ProtoMessage() {}

func (x *SceneRandomIsland) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoSceneObjs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneRandomIsland.ProtoReflect.Descriptor instead.
func (*SceneRandomIsland) Descriptor() ([]byte, []int) {
	return file_ProtoSceneObjs_proto_rawDescGZIP(), []int{24}
}

var File_ProtoSceneObjs_proto protoreflect.FileDescriptor

const file_ProtoSceneObjs_proto_rawDesc = "" +
	"\n" +
	"\x14ProtoSceneObjs.proto\x1a\x11ProtoCommon.proto\x1a\x11ProtoBattle.proto\"\xf3\x02\n" +
	"\x0fSceneEntityBase\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x03R\bentityId\x12\x15\n" +
	"\x06cnf_id\x18\x02 \x01(\x03R\x05cnfId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\x03R\x06hostId\x12%\n" +
	"\x0epreassigned_id\x18\x05 \x01(\x03R\rpreassignedId\x12\x1d\n" +
	"\x03pos\x18\x06 \x01(\v2\v.Vector3IntR\x03pos\x12\x1d\n" +
	"\x03rot\x18\a \x01(\v2\v.Vector3IntR\x03rot\x12\x1f\n" +
	"\ventity_type\x18\t \x01(\x05R\n" +
	"entityType\x12!\n" +
	"\fobject_state\x18\n" +
	" \x01(\x05R\vobjectState\x12.\n" +
	"\x13spawner_system_guid\x18\v \x01(\x03R\x11spawnerSystemGuid\x12\x1f\n" +
	"\vlogic_state\x18\f \x01(\x05R\n" +
	"logicState\"\x98\x02\n" +
	"\x0fSceneEntityInfo\x12-\n" +
	"\tbase_data\x18\x01 \x01(\v2\x10.SceneEntityBaseR\bbaseData\x12\x1f\n" +
	"\ventity_data\x18\x02 \x01(\fR\n" +
	"entityData\x122\n" +
	"\vbattle_info\x18\x03 \x01(\v2\x11.EntityBattleInfoR\n" +
	"battleInfo\x12-\n" +
	"\trole_info\x18\x04 \x01(\v2\x10.RoleSummaryInfoR\broleInfo\x12$\n" +
	"\x0ebuff_uid_start\x18\x05 \x01(\x03R\fbuffUidStart\x12,\n" +
	"\x12random_start_index\x18\x06 \x01(\x05R\x10randomStartIndex\"K\n" +
	"\x13SceneEntityHostInfo\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x03R\bentityId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\x03R\x06hostId\"d\n" +
	"\x12PlayerLocationInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1d\n" +
	"\x03pos\x18\x02 \x01(\v2\v.Vector3IntR\x03pos\x12\x1d\n" +
	"\x03rot\x18\x03 \x01(\v2\v.Vector3IntR\x03rot\"\xb5\x02\n" +
	"\n" +
	"MotionInfo\x12\x1d\n" +
	"\x03pos\x18\x01 \x01(\v2\v.Vector3IntR\x03pos\x12\x1d\n" +
	"\x03rot\x18\x02 \x01(\v2\v.Vector3IntR\x03rot\x12!\n" +
	"\x05speed\x18\x03 \x01(\v2\v.Vector3IntR\x05speed\x12\"\n" +
	"\x05state\x18\x04 \x01(\x0e2\f.MotionStateR\x05state\x12\x1d\n" +
	"\n" +
	"scene_time\x18\x05 \x01(\x03R\tsceneTime\x12\x1b\n" +
	"\tmax_speed\x18\x06 \x01(\x02R\bmaxSpeed\x12/\n" +
	"\facceleration\x18\a \x01(\v2\v.Vector3IntR\facceleration\x125\n" +
	"\fpacket_state\x18\b \x01(\x0e2\x12.MotionPacketStateR\vpacketState\"O\n" +
	"\vDlgTagProto\x12\x15\n" +
	"\x06dlg_id\x18\x01 \x01(\x03R\x05dlgId\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\x03R\x06linkId\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"0\n" +
	"\fDlgTagsProto\x12 \n" +
	"\x04tags\x18\x01 \x03(\v2\f.DlgTagProtoR\x04tags\"\x9c\x01\n" +
	"\x13DynamicInteractInfo\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.DynamicInteractTypeR\x04type\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x1d\n" +
	"\n" +
	"param_list\x18\x03 \x03(\tR\tparamList\x12&\n" +
	"\x0flong_param_list\x18\x04 \x03(\x03R\rlongParamList\"\xf3\x02\n" +
	"\fSceneMonster\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12.\n" +
	"\x13spawner_system_guid\x18\x02 \x01(\x03R\x11spawnerSystemGuid\x12\x1b\n" +
	"\tcamp_type\x18\x03 \x01(\x05R\bcampType\x12(\n" +
	"\x10squad_manager_id\x18\x04 \x01(\x03R\x0esquadManagerId\x12\x1f\n" +
	"\vdialogue_id\x18\x05 \x01(\x03R\n" +
	"dialogueId\x122\n" +
	"\rdialogue_tags\x18\x06 \x01(\v2\r.DlgTagsProtoR\fdialogueTags\x127\n" +
	"\fdynamic_list\x18\a \x03(\v2\x14.DynamicInteractInfoR\vdynamicList\x12\x1e\n" +
	"\n" +
	"difficulty\x18\b \x01(\x05R\n" +
	"difficulty\x12#\n" +
	"\raddition_tags\x18\t \x03(\x05R\fadditionTags\";\n" +
	"\x14SceneForbiddenVolume\x12#\n" +
	"\rfobidden_mode\x18\x01 \x01(\x05R\ffobiddenMode\"H\n" +
	"\fSceneSummons\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\x03R\bmasterId\x12\x1b\n" +
	"\tcamp_type\x18\x02 \x01(\x05R\bcampType\"}\n" +
	"\bSceneNpc\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x05R\x05npcId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x05R\x06roomId\x12&\n" +
	"\x0fparent_quest_id\x18\x03 \x01(\x05R\rparentQuestId\x12\x19\n" +
	"\bblock_id\x18\x04 \x01(\x05R\ablockId\"\xd5\x01\n" +
	"\vSceneAvatar\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x05R\x03exp\x12\x1b\n" +
	"\texceed_id\x18\x03 \x01(\x05R\bexceedId\x12*\n" +
	"\x11is_player_control\x18\x04 \x01(\bR\x0fisPlayerControl\x12\x1b\n" +
	"\tcamp_type\x18\x05 \x01(\x05R\bcampType\x12\x1d\n" +
	"\n" +
	"life_state\x18\x06 \x01(\x05R\tlifeState\x12\x19\n" +
	"\bsub_type\x18\a \x01(\x05R\asubType\"+\n" +
	"\fSceneShipMod\x12\x1b\n" +
	"\tcamp_type\x18\x01 \x01(\x05R\bcampType\"\xd8\x01\n" +
	"\x0fSceneProjectile\x120\n" +
	"\x14client_projectile_id\x18\x01 \x01(\x03R\x12clientProjectileId\x12(\n" +
	"\x10master_entity_id\x18\x02 \x01(\x03R\x0emasterEntityId\x12\x1b\n" +
	"\tcamp_type\x18\x03 \x01(\x05R\bcampType\x12!\n" +
	"\x05speed\x18\x04 \x01(\v2\v.Vector3IntR\x05speed\x12)\n" +
	"\x10instanced_struct\x18\x05 \x01(\tR\x0finstancedStruct\"@\n" +
	"\x0eSceneRestPoint\x12.\n" +
	"\x13spawner_system_guid\x18\x01 \x01(\x03R\x11spawnerSystemGuid\";\n" +
	"\tSceneDoor\x12.\n" +
	"\x13spawner_system_guid\x18\x01 \x01(\x03R\x11spawnerSystemGuid\"<\n" +
	"\n" +
	"SceneChest\x12.\n" +
	"\x13spawner_system_guid\x18\x01 \x01(\x03R\x11spawnerSystemGuid\"=\n" +
	"\vScenePickup\x12.\n" +
	"\x13spawner_system_guid\x18\x01 \x01(\x03R\x11spawnerSystemGuid\"\x91\x01\n" +
	"\tSceneLift\x12$\n" +
	"\x0estart_run_time\x18\x01 \x01(\x03R\fstartRunTime\x12\x1d\n" +
	"\n" +
	"from_floor\x18\x02 \x01(\x05R\tfromFloor\x12\x19\n" +
	"\bto_floor\x18\x03 \x01(\x05R\atoFloor\x12$\n" +
	"\x0efloor_run_time\x18\x04 \x01(\x03R\ffloorRunTime\";\n" +
	"\x13SceneMovingPlatform\x12$\n" +
	"\x0estart_run_time\x18\x01 \x01(\x03R\fstartRunTime\"\r\n" +
	"\vSceneGadget\"P\n" +
	"\x0eTeleporterData\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x05R\asceneId\x12#\n" +
	"\rteleport_list\x18\x02 \x03(\x03R\fteleportList\"8\n" +
	"\x0fSceneTeleporter\x12%\n" +
	"\x05datas\x18\x01 \x03(\v2\x0f.TeleporterDataR\x05datas\"\x13\n" +
	"\x11SceneRandomIsland*\x85\t\n" +
	"\vMotionState\x12\x0f\n" +
	"\vMOTION_NONE\x10\x00\x12\x0f\n" +
	"\vMOTION_WALK\x10\x01\x12\x13\n" +
	"\x0fMOTION_NAV_WALK\x10\x02\x12\x12\n" +
	"\x0eMOTION_FALLING\x10\x03\x12\x14\n" +
	"\x10MOTION_SWIM_MOVE\x10\x04\x12\x0e\n" +
	"\n" +
	"MOTION_FLY\x10\x05\x12\x11\n" +
	"\rMOTION_CUSTOM\x10\x06\x12\x11\n" +
	"\rMOTION_UE_MAX\x10\a\x12\x10\n" +
	"\fMOTION_RESET\x10\b\x12\x12\n" +
	"\x0eMOTION_STANDBY\x10\t\x12\x17\n" +
	"\x13MOTION_STANDBY_MOVE\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"MOTION_RUN\x10\v\x12\x0f\n" +
	"\vMOTION_DASH\x10\f\x12\x10\n" +
	"\fMOTION_CLIMB\x10\r\x12\x15\n" +
	"\x11MOTION_CLIMB_JUMP\x10\x0e\x12\x1b\n" +
	"\x17MOTION_STANDBY_TO_CLIMB\x10\x0f\x12\x10\n" +
	"\fMOTION_FIGHT\x10\x10\x12\x0f\n" +
	"\vMOTION_JUMP\x10\x11\x12\x14\n" +
	"\x10MOTION_SWIM_IDLE\x10\x12\x12\x14\n" +
	"\x10MOTION_SWIM_DASH\x10\x13\x12\x14\n" +
	"\x10MOTION_SWIM_JUMP\x10\x14\x12\x0f\n" +
	"\vMOTION_SLIP\x10\x15\x12\x16\n" +
	"\x12MOTION_GO_UPSTAIRS\x10\x16\x12\x19\n" +
	"\x15MOTION_FALL_ON_GROUND\x10\x17\x12#\n" +
	"\x1fMOTION_JUMP_UP_WALL_FOR_STANDBY\x10\x18\x12\x18\n" +
	"\x14MOTION_JUMP_OFF_WALL\x10\x19\x12\x16\n" +
	"\x12MOTION_POWERED_FLY\x10\x1a\x12\x16\n" +
	"\x12MOTION_LADDER_IDLE\x10\x1b\x12\x16\n" +
	"\x12MOTION_LADDER_MOVE\x10\x1c\x12\x16\n" +
	"\x12MOTION_LADDER_SLIP\x10\x1d\x12\x1c\n" +
	"\x18MOTION_STANDBY_TO_LADDER\x10\x1e\x12\x1c\n" +
	"\x18MOTION_LADDER_TO_STANDBY\x10\x1f\x12\x19\n" +
	"\x15MOTION_DANGER_STANDBY\x10 \x12\x1e\n" +
	"\x1aMOTION_DANGER_STANDBY_MOVE\x10!\x12\x16\n" +
	"\x12MOTION_DANGER_WALK\x10\"\x12\x15\n" +
	"\x11MOTION_DANGER_RUN\x10#\x12\x16\n" +
	"\x12MOTION_DANGER_DASH\x10$\x12\x16\n" +
	"\x12MOTION_CROUCH_IDLE\x10%\x12\x16\n" +
	"\x12MOTION_CROUCH_MOVE\x10&\x12\x16\n" +
	"\x12MOTION_CROUCH_ROLL\x10'\x12\x11\n" +
	"\rMOTION_NOTIFY\x10(\x12\x15\n" +
	"\x11MOTION_LAND_SPEED\x10)\x12\x18\n" +
	"\x14MOTION_MOVE_FAIL_ACK\x10*\x12\x14\n" +
	"\x10MOTION_WATERFALL\x10+\x12\x1c\n" +
	"\x18MOTION_DASH_BEFORE_SHAKE\x10,\x12\x13\n" +
	"\x0fMOTION_SIT_IDLE\x10-\x12\x18\n" +
	"\x14MOTION_FORCE_SET_POS\x10.\x12\x1b\n" +
	"\x17MOTION_QUEST_FORCE_DRAG\x10/\x12\x17\n" +
	"\x13MOTION_FOLLOW_ROUTE\x100\x12\x0e\n" +
	"\n" +
	"MOTION_NUM\x101*\xbe\x04\n" +
	"\vEnterReason\x12\x15\n" +
	"\x11ENTER_REASON_NONE\x10\x00\x12\x16\n" +
	"\x12ENTER_REASON_LOGIN\x10\x01\x12\x15\n" +
	"\x11ENTER_REASON_BACK\x10\x02\x12\x13\n" +
	"\x0fENTER_REASON_GM\x10\x15\x12\"\n" +
	"\x1eENTER_REASON_LEVEL_QUEST_TRANS\x10\x1e\x12\x1f\n" +
	"\x1bENTER_REASON_QUEST_ROLLBACK\x10\x1f\x12\x1c\n" +
	"\x18ENTER_REASON_TRANS_POINT\x10*\x12 \n" +
	"\x1cENTER_REASON_CLIENT_TRANSMIT\x10+\x12\x1a\n" +
	"\x16ENTER_REASON_TEAM_KICK\x103\x12\x1a\n" +
	"\x16ENTER_REASON_TEAM_JOIN\x104\x12\x1a\n" +
	"\x16ENTER_REASON_TEAM_BACK\x105\x12\x1b\n" +
	"\x17ENTER_REASON_ENTER_HOME\x10@\x12\x1a\n" +
	"\x16ENTER_REASON_EXIT_HOME\x10A\x12#\n" +
	"\x1fENTER_REASON_CHANGE_HOME_MODULE\x10B\x12\x18\n" +
	"\x14ENTER_REASON_GALLERY\x10C\x12 \n" +
	"\x1cENTER_REASON_HOME_SCENE_JUMP\x10D\x12\x1e\n" +
	"\x1aENTER_REASON_HIDE_AND_SEEK\x10E\x12 \n" +
	"\x1cENTER_REASON_ENTER_MAZE_NODE\x10F\x12\x1f\n" +
	"\x1bENTER_REASON_EXIT_MAZE_NODE\x10G*\xd6\x02\n" +
	"\n" +
	"VisionType\x12\x0f\n" +
	"\vVISION_NONE\x10\x00\x12\x0f\n" +
	"\vVISION_MEET\x10\x01\x12\x11\n" +
	"\rVISION_REBORN\x10\x02\x12\x12\n" +
	"\x0eVISION_REPLACE\x10\x03\x12\x1a\n" +
	"\x16VISION_WAYPOINT_REBORN\x10\x04\x12\x0f\n" +
	"\vVISION_MISS\x10\x05\x12\x0e\n" +
	"\n" +
	"VISION_DIE\x10\x06\x12\x18\n" +
	"\x14VISION_GATHER_ESCAPE\x10\a\x12\x12\n" +
	"\x0eVISION_REFRESH\x10\b\x12\x14\n" +
	"\x10VISION_TRANSPORT\x10\t\x12\x16\n" +
	"\x12VISION_REPLACE_DIE\x10\n" +
	"\x12\x19\n" +
	"\x15VISION_REPLACE_SERVER\x10\v\x12\x0f\n" +
	"\vVISION_BORN\x10\f\x12\x11\n" +
	"\rVISION_PICKUP\x10\r\x12\x11\n" +
	"\rVISION_REMOVE\x10\x0e\x12\x14\n" +
	"\x10VISION_DE_ACTIVE\x10\x0f*7\n" +
	"\x0fGroupVisionType\x12\x13\n" +
	"\x0fGVT_ALWAYS_SHOW\x10\x00\x12\x0f\n" +
	"\vGVT_DEFAULT\x10\x01*?\n" +
	"\x0eEntityJumpType\x12\f\n" +
	"\bEJT_NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"EJT_ACTIVE\x10\x01\x12\x0f\n" +
	"\vEJT_PASSIVE\x10\x02*\xb8\x01\n" +
	"\x0eTeleportReason\x12\x11\n" +
	"\rTELEPORT_NONE\x10\x00\x12\x18\n" +
	"\x14TELEPORT_LEVEL_QUEST\x10\x01\x12\x1b\n" +
	"\x17TELEPORT_AVATAR_RE_BORN\x10\x02\x12\x19\n" +
	"\x15TELEPORT_TEAM_RE_BORN\x10\x03\x12\x13\n" +
	"\x0fTELEPORT_BIGMAP\x10\x04\x12\x12\n" +
	"\x0eTELEPORT_ACTOR\x10\x05\x12\x18\n" +
	"\x14TELEPORT_STUCK_RESET\x10\x06*\xd0\x01\n" +
	"\fReBornReason\x12\x0f\n" +
	"\vREASON_NONE\x10\x00\x12\x1a\n" +
	"\x16REASON_AVATAR_ALL_DEAD\x10\x01\x12\x1c\n" +
	"\x18REASON_AVATAR_JUMP_CLIFF\x10\x02\x12\x16\n" +
	"\x12REASON_REBORN_AREA\x10\x03\x12\x14\n" +
	"\x10REASON_FLOW_KILL\x10\x04\x12\x15\n" +
	"\x11REASON_REST_POINT\x10\x05\x12\x18\n" +
	"\x14REASON_VISUAL_REBORN\x10\x06\x12\x16\n" +
	"\x12REASON_FOOD_REBORN\x10\a*9\n" +
	"\x11MotionPacketState\x12\x0f\n" +
	"\vPACKET_MOVE\x10\x00\x12\x13\n" +
	"\x0fPACKET_MOVE_END\x10\x01*7\n" +
	"\x13DynamicInteractType\x12\f\n" +
	"\bPLAY_AVG\x10\x00\x12\x12\n" +
	"\x0ePLAY_NARRATIVE\x10\x01B\x1e\n" +
	"\x11com.game.protoGenZ\t/protoGenb\x06proto3"

var (
	file_ProtoSceneObjs_proto_rawDescOnce sync.Once
	file_ProtoSceneObjs_proto_rawDescData []byte
)

func file_ProtoSceneObjs_proto_rawDescGZIP() []byte {
	file_ProtoSceneObjs_proto_rawDescOnce.Do(func() {
		file_ProtoSceneObjs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ProtoSceneObjs_proto_rawDesc), len(file_ProtoSceneObjs_proto_rawDesc)))
	})
	return file_ProtoSceneObjs_proto_rawDescData
}

var file_ProtoSceneObjs_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_ProtoSceneObjs_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_ProtoSceneObjs_proto_goTypes = []any{
	(MotionState)(0),             // 0: MotionState
	(EnterReason)(0),             // 1: EnterReason
	(VisionType)(0),              // 2: VisionType
	(GroupVisionType)(0),         // 3: GroupVisionType
	(EntityJumpType)(0),          // 4: EntityJumpType
	(TeleportReason)(0),          // 5: TeleportReason
	(ReBornReason)(0),            // 6: ReBornReason
	(MotionPacketState)(0),       // 7: MotionPacketState
	(DynamicInteractType)(0),     // 8: DynamicInteractType
	(*SceneEntityBase)(nil),      // 9: SceneEntityBase
	(*SceneEntityInfo)(nil),      // 10: SceneEntityInfo
	(*SceneEntityHostInfo)(nil),  // 11: SceneEntityHostInfo
	(*PlayerLocationInfo)(nil),   // 12: PlayerLocationInfo
	(*MotionInfo)(nil),           // 13: MotionInfo
	(*DlgTagProto)(nil),          // 14: DlgTagProto
	(*DlgTagsProto)(nil),         // 15: DlgTagsProto
	(*DynamicInteractInfo)(nil),  // 16: DynamicInteractInfo
	(*SceneMonster)(nil),         // 17: SceneMonster
	(*SceneForbiddenVolume)(nil), // 18: SceneForbiddenVolume
	(*SceneSummons)(nil),         // 19: SceneSummons
	(*SceneNpc)(nil),             // 20: SceneNpc
	(*SceneAvatar)(nil),          // 21: SceneAvatar
	(*SceneShipMod)(nil),         // 22: SceneShipMod
	(*SceneProjectile)(nil),      // 23: SceneProjectile
	(*SceneRestPoint)(nil),       // 24: SceneRestPoint
	(*SceneDoor)(nil),            // 25: SceneDoor
	(*SceneChest)(nil),           // 26: SceneChest
	(*ScenePickup)(nil),          // 27: ScenePickup
	(*SceneLift)(nil),            // 28: SceneLift
	(*SceneMovingPlatform)(nil),  // 29: SceneMovingPlatform
	(*SceneGadget)(nil),          // 30: SceneGadget
	(*TeleporterData)(nil),       // 31: TeleporterData
	(*SceneTeleporter)(nil),      // 32: SceneTeleporter
	(*SceneRandomIsland)(nil),    // 33: SceneRandomIsland
	(*Vector3Int)(nil),           // 34: Vector3Int
	(*EntityBattleInfo)(nil),     // 35: EntityBattleInfo
	(*RoleSummaryInfo)(nil),      // 36: RoleSummaryInfo
}
var file_ProtoSceneObjs_proto_depIdxs = []int32{
	34, // 0: SceneEntityBase.pos:type_name -> Vector3Int
	34, // 1: SceneEntityBase.rot:type_name -> Vector3Int
	9,  // 2: SceneEntityInfo.base_data:type_name -> SceneEntityBase
	35, // 3: SceneEntityInfo.battle_info:type_name -> EntityBattleInfo
	36, // 4: SceneEntityInfo.role_info:type_name -> RoleSummaryInfo
	34, // 5: PlayerLocationInfo.pos:type_name -> Vector3Int
	34, // 6: PlayerLocationInfo.rot:type_name -> Vector3Int
	34, // 7: MotionInfo.pos:type_name -> Vector3Int
	34, // 8: MotionInfo.rot:type_name -> Vector3Int
	34, // 9: MotionInfo.speed:type_name -> Vector3Int
	0,  // 10: MotionInfo.state:type_name -> MotionState
	34, // 11: MotionInfo.acceleration:type_name -> Vector3Int
	7,  // 12: MotionInfo.packet_state:type_name -> MotionPacketState
	14, // 13: DlgTagsProto.tags:type_name -> DlgTagProto
	8,  // 14: DynamicInteractInfo.type:type_name -> DynamicInteractType
	15, // 15: SceneMonster.dialogue_tags:type_name -> DlgTagsProto
	16, // 16: SceneMonster.dynamic_list:type_name -> DynamicInteractInfo
	34, // 17: SceneProjectile.speed:type_name -> Vector3Int
	31, // 18: SceneTeleporter.datas:type_name -> TeleporterData
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_ProtoSceneObjs_proto_init() }
func file_ProtoSceneObjs_proto_init() {
	if File_ProtoSceneObjs_proto != nil {
		return
	}
	file_ProtoCommon_proto_init()
	file_ProtoBattle_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ProtoSceneObjs_proto_rawDesc), len(file_ProtoSceneObjs_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ProtoSceneObjs_proto_goTypes,
		DependencyIndexes: file_ProtoSceneObjs_proto_depIdxs,
		EnumInfos:         file_ProtoSceneObjs_proto_enumTypes,
		MessageInfos:      file_ProtoSceneObjs_proto_msgTypes,
	}.Build()
	File_ProtoSceneObjs_proto = out.File
	file_ProtoSceneObjs_proto_goTypes = nil
	file_ProtoSceneObjs_proto_depIdxs = nil
}
